-- refresh_tokens table
CREATE TABLE refresh_tokens (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uid uuid NOT NULL UNIQUE,
    token text NOT NULL UNIQUE,
    expires_at timestamptz NOT NULL,
    created_at timestamptz NOT NULL DEFAULT now()
);
