-- files table
CREATE TYPE file_status AS ENUM ('NORMAL', 'ARCHIVED');
CREATE TABLE files (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    url text NOT NULL UNIQUE,
    name text NOT NULL,
    content_type text NOT NULL,
    size bigint NOT NULL,
    checksum text NOT NULL,
    uploader uuid NOT NULL,
    status file_status NOT NULL DEFAULT 'NORMAL',
    created_at timestamptz NOT NULL DEFAULT now()
);
