// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: comment.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const archiveCommentByUidAndAuthor = `-- name: ArchiveCommentByUidAndAuthor :execrows
UPDATE post_comments
SET status = 'ARCHIVED'::comment_status,
  updated_at = now()
WHERE uid = $1
  AND author_uid = $2
  AND status = 'NORMAL'::comment_status
`

type ArchiveCommentByUidAndAuthorParams struct {
	Uid       uuid.UUID
	AuthorUid uuid.UUID
}

func (q *Queries) ArchiveCommentByUidAndAuthor(ctx context.Context, arg ArchiveCommentByUidAndAuthorParams) (int64, error) {
	result, err := q.db.Exec(ctx, archiveCommentByUidAndAuthor, arg.Uid, arg.AuthorUid)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const createComment = `-- name: CreateComment :one
INSERT INTO post_comments (
  uid,
  post_uid,
  author_uid,
  root_uid,
  parent_uid,
  reply_to_author_uid,
  content,
  images,
  ip
)
VALUES (
  $1,
  $2,
  $3,
  $4,
  $5,
  $6,
  $7,
  $8,
  $9
)
RETURNING
  id,
  uid,
  author_uid,
  post_uid,
  root_uid,
  parent_uid,
  content,
  images,
  reply_count,
  like_count,
  created_at,
  updated_at
`

type CreateCommentParams struct {
	Uid              uuid.UUID
	PostUid          uuid.UUID
	AuthorUid        uuid.UUID
	RootUid          uuid.UUID
	ParentUid        uuid.NullUUID
	ReplyToAuthorUid uuid.NullUUID
	Content          string
	Images           []string
	Ip               string
}

type CreateCommentRow struct {
	ID         int32
	Uid        uuid.UUID
	AuthorUid  uuid.UUID
	PostUid    uuid.UUID
	RootUid    uuid.UUID
	ParentUid  uuid.NullUUID
	Content    string
	Images     []string
	ReplyCount int32
	LikeCount  int32
	CreatedAt  pgtype.Timestamptz
	UpdatedAt  pgtype.Timestamptz
}

func (q *Queries) CreateComment(ctx context.Context, arg CreateCommentParams) (CreateCommentRow, error) {
	row := q.db.QueryRow(ctx, createComment,
		arg.Uid,
		arg.PostUid,
		arg.AuthorUid,
		arg.RootUid,
		arg.ParentUid,
		arg.ReplyToAuthorUid,
		arg.Content,
		arg.Images,
		arg.Ip,
	)
	var i CreateCommentRow
	err := row.Scan(
		&i.ID,
		&i.Uid,
		&i.AuthorUid,
		&i.PostUid,
		&i.RootUid,
		&i.ParentUid,
		&i.Content,
		&i.Images,
		&i.ReplyCount,
		&i.LikeCount,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const decrementCommentLikeCount = `-- name: DecrementCommentLikeCount :one
UPDATE post_comments
SET like_count = GREATEST(like_count - 1, 0),
    updated_at = now()
WHERE uid = $1
RETURNING like_count
`

func (q *Queries) DecrementCommentLikeCount(ctx context.Context, commentUid uuid.UUID) (int32, error) {
	row := q.db.QueryRow(ctx, decrementCommentLikeCount, commentUid)
	var like_count int32
	err := row.Scan(&like_count)
	return like_count, err
}

const decrementCommentReplyCount = `-- name: DecrementCommentReplyCount :one
UPDATE post_comments
SET reply_count = GREATEST(reply_count - 1, 0),
    updated_at = now()
WHERE uid = $1
  AND status = 'NORMAL'::comment_status
RETURNING reply_count
`

func (q *Queries) DecrementCommentReplyCount(ctx context.Context, commentUid uuid.UUID) (int32, error) {
	row := q.db.QueryRow(ctx, decrementCommentReplyCount, commentUid)
	var reply_count int32
	err := row.Scan(&reply_count)
	return reply_count, err
}

const deleteCommentLikeEdge = `-- name: DeleteCommentLikeEdge :execrows
DELETE FROM comment_likes
WHERE comment_uid = $1
  AND user_uid = $2
`

type DeleteCommentLikeEdgeParams struct {
	CommentUid uuid.UUID
	UserUid    uuid.UUID
}

func (q *Queries) DeleteCommentLikeEdge(ctx context.Context, arg DeleteCommentLikeEdgeParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteCommentLikeEdge, arg.CommentUid, arg.UserUid)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getCommentByUid = `-- name: GetCommentByUid :one
SELECT
  id,
  uid,
  author_uid,
  post_uid,
  root_uid,
  parent_uid,
  reply_to_author_uid,
  content,
  images,
  reply_count,
  like_count,
  (parent_uid IS NULL)::boolean AS is_top_level,
  created_at,
  updated_at
FROM post_comments
WHERE uid = $1
  AND status = 'NORMAL'::comment_status
LIMIT 1
`

type GetCommentByUidRow struct {
	ID               int32
	Uid              uuid.UUID
	AuthorUid        uuid.UUID
	PostUid          uuid.UUID
	RootUid          uuid.UUID
	ParentUid        uuid.NullUUID
	ReplyToAuthorUid uuid.NullUUID
	Content          string
	Images           []string
	ReplyCount       int32
	LikeCount        int32
	IsTopLevel       bool
	CreatedAt        pgtype.Timestamptz
	UpdatedAt        pgtype.Timestamptz
}

func (q *Queries) GetCommentByUid(ctx context.Context, uid uuid.UUID) (GetCommentByUidRow, error) {
	row := q.db.QueryRow(ctx, getCommentByUid, uid)
	var i GetCommentByUidRow
	err := row.Scan(
		&i.ID,
		&i.Uid,
		&i.AuthorUid,
		&i.PostUid,
		&i.RootUid,
		&i.ParentUid,
		&i.ReplyToAuthorUid,
		&i.Content,
		&i.Images,
		&i.ReplyCount,
		&i.LikeCount,
		&i.IsTopLevel,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getCommentsByUIDs = `-- name: GetCommentsByUIDs :many
SELECT
  id,
  uid,
  author_uid,
  post_uid,
  root_uid,
  parent_uid,
  reply_to_author_uid,
  content,
  images,
  reply_count,
  like_count,
  (parent_uid IS NULL)::boolean AS is_top_level,
  created_at,
  updated_at
FROM post_comments
WHERE uid = ANY($1::uuid[])
  AND status = 'NORMAL'::comment_status
`

type GetCommentsByUIDsRow struct {
	ID               int32
	Uid              uuid.UUID
	AuthorUid        uuid.UUID
	PostUid          uuid.UUID
	RootUid          uuid.UUID
	ParentUid        uuid.NullUUID
	ReplyToAuthorUid uuid.NullUUID
	Content          string
	Images           []string
	ReplyCount       int32
	LikeCount        int32
	IsTopLevel       bool
	CreatedAt        pgtype.Timestamptz
	UpdatedAt        pgtype.Timestamptz
}

func (q *Queries) GetCommentsByUIDs(ctx context.Context, uids []uuid.UUID) ([]GetCommentsByUIDsRow, error) {
	rows, err := q.db.Query(ctx, getCommentsByUIDs, uids)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetCommentsByUIDsRow
	for rows.Next() {
		var i GetCommentsByUIDsRow
		if err := rows.Scan(
			&i.ID,
			&i.Uid,
			&i.AuthorUid,
			&i.PostUid,
			&i.RootUid,
			&i.ParentUid,
			&i.ReplyToAuthorUid,
			&i.Content,
			&i.Images,
			&i.ReplyCount,
			&i.LikeCount,
			&i.IsTopLevel,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const incrementCommentLikeCount = `-- name: IncrementCommentLikeCount :one
UPDATE post_comments
SET like_count = like_count + 1,
    updated_at = now()
WHERE uid = $1
RETURNING like_count
`

func (q *Queries) IncrementCommentLikeCount(ctx context.Context, commentUid uuid.UUID) (int32, error) {
	row := q.db.QueryRow(ctx, incrementCommentLikeCount, commentUid)
	var like_count int32
	err := row.Scan(&like_count)
	return like_count, err
}

const incrementCommentReplyCount = `-- name: IncrementCommentReplyCount :one
UPDATE post_comments
SET reply_count = reply_count + 1,
    updated_at = now()
WHERE uid = $1
  AND status = 'NORMAL'::comment_status
RETURNING reply_count
`

func (q *Queries) IncrementCommentReplyCount(ctx context.Context, commentUid uuid.UUID) (int32, error) {
	row := q.db.QueryRow(ctx, incrementCommentReplyCount, commentUid)
	var reply_count int32
	err := row.Scan(&reply_count)
	return reply_count, err
}

const insertCommentLikeEdge = `-- name: InsertCommentLikeEdge :execrows
INSERT INTO comment_likes (comment_uid, user_uid)
VALUES ($1, $2)
ON CONFLICT DO NOTHING
`

type InsertCommentLikeEdgeParams struct {
	CommentUid uuid.UUID
	UserUid    uuid.UUID
}

func (q *Queries) InsertCommentLikeEdge(ctx context.Context, arg InsertCommentLikeEdgeParams) (int64, error) {
	result, err := q.db.Exec(ctx, insertCommentLikeEdge, arg.CommentUid, arg.UserUid)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const listLikedCommentUIDsByUserAndCommentUIDs = `-- name: ListLikedCommentUIDsByUserAndCommentUIDs :many
SELECT comment_uid
FROM comment_likes
WHERE user_uid = $1
  AND comment_uid = ANY($2::uuid[])
`

type ListLikedCommentUIDsByUserAndCommentUIDsParams struct {
	UserUid     uuid.UUID
	CommentUids []uuid.UUID
}

func (q *Queries) ListLikedCommentUIDsByUserAndCommentUIDs(ctx context.Context, arg ListLikedCommentUIDsByUserAndCommentUIDsParams) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, listLikedCommentUIDsByUserAndCommentUIDs, arg.UserUid, arg.CommentUids)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []uuid.UUID
	for rows.Next() {
		var comment_uid uuid.UUID
		if err := rows.Scan(&comment_uid); err != nil {
			return nil, err
		}
		items = append(items, comment_uid)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listReplies = `-- name: ListReplies :many
SELECT
  uid,
  author_uid,
  post_uid,
  root_uid,
  parent_uid,
  reply_to_author_uid,
  content,
  images,
  reply_count,
  like_count,
  created_at,
  updated_at,
  COUNT(*) OVER ()::int AS total
FROM post_comments
WHERE status = 'NORMAL'::comment_status
  AND root_uid = $1
  AND root_uid <> uid
ORDER BY created_at ASC, uid ASC
LIMIT 10 OFFSET ($2::int - 1) * 10
`

type ListRepliesParams struct {
	RootUid uuid.UUID
	Page    int32
}

type ListRepliesRow struct {
	Uid              uuid.UUID
	AuthorUid        uuid.UUID
	PostUid          uuid.UUID
	RootUid          uuid.UUID
	ParentUid        uuid.NullUUID
	ReplyToAuthorUid uuid.NullUUID
	Content          string
	Images           []string
	ReplyCount       int32
	LikeCount        int32
	CreatedAt        pgtype.Timestamptz
	UpdatedAt        pgtype.Timestamptz
	Total            int32
}

func (q *Queries) ListReplies(ctx context.Context, arg ListRepliesParams) ([]ListRepliesRow, error) {
	rows, err := q.db.Query(ctx, listReplies, arg.RootUid, arg.Page)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListRepliesRow
	for rows.Next() {
		var i ListRepliesRow
		if err := rows.Scan(
			&i.Uid,
			&i.AuthorUid,
			&i.PostUid,
			&i.RootUid,
			&i.ParentUid,
			&i.ReplyToAuthorUid,
			&i.Content,
			&i.Images,
			&i.ReplyCount,
			&i.LikeCount,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Total,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTopComments = `-- name: ListTopComments :many
SELECT
  uid,
  author_uid,
  post_uid,
  root_uid,
  parent_uid,
  content,
  images,
  reply_count,
  like_count,
  created_at,
  updated_at
FROM post_comments
WHERE status = 'NORMAL'::comment_status
  AND post_uid = $1
  AND parent_uid IS NULL
  AND (created_at, uid) < (
    $2::timestamptz,
    $3::uuid
  )
ORDER BY created_at DESC, uid DESC
LIMIT 20
`

type ListTopCommentsParams struct {
	PostUid         uuid.UUID
	CursorCreatedAt pgtype.Timestamptz
	CursorID        uuid.UUID
}

type ListTopCommentsRow struct {
	Uid        uuid.UUID
	AuthorUid  uuid.UUID
	PostUid    uuid.UUID
	RootUid    uuid.UUID
	ParentUid  uuid.NullUUID
	Content    string
	Images     []string
	ReplyCount int32
	LikeCount  int32
	CreatedAt  pgtype.Timestamptz
	UpdatedAt  pgtype.Timestamptz
}

func (q *Queries) ListTopComments(ctx context.Context, arg ListTopCommentsParams) ([]ListTopCommentsRow, error) {
	rows, err := q.db.Query(ctx, listTopComments, arg.PostUid, arg.CursorCreatedAt, arg.CursorID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListTopCommentsRow
	for rows.Next() {
		var i ListTopCommentsRow
		if err := rows.Scan(
			&i.Uid,
			&i.AuthorUid,
			&i.PostUid,
			&i.RootUid,
			&i.ParentUid,
			&i.Content,
			&i.Images,
			&i.ReplyCount,
			&i.LikeCount,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
