// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: follow.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const deleteFollowEdge = `-- name: DeleteFollowEdge :execrows
DELETE FROM user_follows
WHERE follower_uid = $1
  AND followee_uid = $2
`

type DeleteFollowEdgeParams struct {
	FollowerUid uuid.UUID
	FolloweeUid uuid.UUID
}

func (q *Queries) DeleteFollowEdge(ctx context.Context, arg DeleteFollowEdgeParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteFollowEdge, arg.FollowerUid, arg.FolloweeUid)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const insertFollowEdge = `-- name: InsertFollowEdge :execrows
INSERT INTO user_follows (follower_uid, followee_uid)
VALUES ($1, $2)
ON CONFLICT DO NOTHING
`

type InsertFollowEdgeParams struct {
	FollowerUid uuid.UUID
	FolloweeUid uuid.UUID
}

func (q *Queries) InsertFollowEdge(ctx context.Context, arg InsertFollowEdgeParams) (int64, error) {
	result, err := q.db.Exec(ctx, insertFollowEdge, arg.FollowerUid, arg.FolloweeUid)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const isFollowing = `-- name: IsFollowing :one
SELECT EXISTS (
  SELECT 1
  FROM user_follows
  WHERE follower_uid = $1
    AND followee_uid = $2
) AS is_following
`

type IsFollowingParams struct {
	FollowerUid uuid.UUID
	FolloweeUid uuid.UUID
}

func (q *Queries) IsFollowing(ctx context.Context, arg IsFollowingParams) (bool, error) {
	row := q.db.QueryRow(ctx, isFollowing, arg.FollowerUid, arg.FolloweeUid)
	var is_following bool
	err := row.Scan(&is_following)
	return is_following, err
}

const listFollowers = `-- name: ListFollowers :many
SELECT
  uf.created_at AS followed_at,
  u.uid,
  u.role,
  u.nickname,
  u.avatar_url,
  u.followers_count,
  u.following_count
FROM user_follows uf
JOIN users u ON u.uid = uf.follower_uid
WHERE uf.followee_uid = $1
  AND u.status = 'NORMAL'::user_status
  AND (
    $2::text IS NULL
    OR u.nickname ILIKE '%' || $2::text || '%'
  )
  AND (uf.created_at, uf.follower_uid) < (
    $3::timestamptz,
    $4::uuid
  )
ORDER BY uf.created_at DESC, uf.follower_uid DESC
LIMIT 20
`

type ListFollowersParams struct {
	Uid             uuid.UUID
	Query           pgtype.Text
	CursorCreatedAt pgtype.Timestamptz
	CursorID        uuid.UUID
}

type ListFollowersRow struct {
	FollowedAt     pgtype.Timestamptz
	Uid            uuid.UUID
	Role           UserRole
	Nickname       string
	AvatarUrl      string
	FollowersCount int32
	FollowingCount int32
}

func (q *Queries) ListFollowers(ctx context.Context, arg ListFollowersParams) ([]ListFollowersRow, error) {
	rows, err := q.db.Query(ctx, listFollowers,
		arg.Uid,
		arg.Query,
		arg.CursorCreatedAt,
		arg.CursorID,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListFollowersRow
	for rows.Next() {
		var i ListFollowersRow
		if err := rows.Scan(
			&i.FollowedAt,
			&i.Uid,
			&i.Role,
			&i.Nickname,
			&i.AvatarUrl,
			&i.FollowersCount,
			&i.FollowingCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFollowing = `-- name: ListFollowing :many
SELECT
  uf.created_at AS followed_at,
  u.uid,
  u.role,
  u.nickname,
  u.avatar_url,
  u.followers_count,
  u.following_count
FROM user_follows uf
JOIN users u ON u.uid = uf.followee_uid
WHERE uf.follower_uid = $1
  AND u.status = 'NORMAL'::user_status
  AND (
    $2::text IS NULL
    OR u.nickname ILIKE '%' || $2::text || '%'
  )
  AND (uf.created_at, uf.followee_uid) < (
    $3::timestamptz,
    $4::uuid
  )
ORDER BY uf.created_at DESC, uf.followee_uid DESC
LIMIT 20
`

type ListFollowingParams struct {
	Uid             uuid.UUID
	Query           pgtype.Text
	CursorCreatedAt pgtype.Timestamptz
	CursorID        uuid.UUID
}

type ListFollowingRow struct {
	FollowedAt     pgtype.Timestamptz
	Uid            uuid.UUID
	Role           UserRole
	Nickname       string
	AvatarUrl      string
	FollowersCount int32
	FollowingCount int32
}

func (q *Queries) ListFollowing(ctx context.Context, arg ListFollowingParams) ([]ListFollowingRow, error) {
	rows, err := q.db.Query(ctx, listFollowing,
		arg.Uid,
		arg.Query,
		arg.CursorCreatedAt,
		arg.CursorID,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListFollowingRow
	for rows.Next() {
		var i ListFollowingRow
		if err := rows.Scan(
			&i.FollowedAt,
			&i.Uid,
			&i.Role,
			&i.Nickname,
			&i.AvatarUrl,
			&i.FollowersCount,
			&i.FollowingCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFollowingUIDsByFollowerAndFolloweeUIDs = `-- name: ListFollowingUIDsByFollowerAndFolloweeUIDs :many
SELECT followee_uid
FROM user_follows
WHERE follower_uid = $1
  AND followee_uid = ANY($2::uuid[])
`

type ListFollowingUIDsByFollowerAndFolloweeUIDsParams struct {
	FollowerUid  uuid.UUID
	FolloweeUids []uuid.UUID
}

func (q *Queries) ListFollowingUIDsByFollowerAndFolloweeUIDs(ctx context.Context, arg ListFollowingUIDsByFollowerAndFolloweeUIDsParams) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, listFollowingUIDsByFollowerAndFolloweeUIDs, arg.FollowerUid, arg.FolloweeUids)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []uuid.UUID
	for rows.Next() {
		var followee_uid uuid.UUID
		if err := rows.Scan(&followee_uid); err != nil {
			return nil, err
		}
		items = append(items, followee_uid)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
