// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: inbox.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const archiveCommentInboxMessageByUIDAndReceiver = `-- name: ArchiveCommentInboxMessageByUIDAndReceiver :execrows
UPDATE inbox_comment_messages
SET status = 'ARCHIVED'::inbox_message_status
WHERE uid = $1
  AND receiver_uid = $2
  AND status = 'NORMAL'::inbox_message_status
`

type ArchiveCommentInboxMessageByUIDAndReceiverParams struct {
	Uid         uuid.UUID
	ReceiverUid uuid.UUID
}

func (q *Queries) ArchiveCommentInboxMessageByUIDAndReceiver(ctx context.Context, arg ArchiveCommentInboxMessageByUIDAndReceiverParams) (int64, error) {
	result, err := q.db.Exec(ctx, archiveCommentInboxMessageByUIDAndReceiver, arg.Uid, arg.ReceiverUid)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const archiveFollowInboxMessageByUIDAndReceiver = `-- name: ArchiveFollowInboxMessageByUIDAndReceiver :execrows
UPDATE inbox_follow_messages
SET status = 'ARCHIVED'::inbox_message_status
WHERE uid = $1
  AND receiver_uid = $2
  AND status = 'NORMAL'::inbox_message_status
`

type ArchiveFollowInboxMessageByUIDAndReceiverParams struct {
	Uid         uuid.UUID
	ReceiverUid uuid.UUID
}

func (q *Queries) ArchiveFollowInboxMessageByUIDAndReceiver(ctx context.Context, arg ArchiveFollowInboxMessageByUIDAndReceiverParams) (int64, error) {
	result, err := q.db.Exec(ctx, archiveFollowInboxMessageByUIDAndReceiver, arg.Uid, arg.ReceiverUid)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const countUnreadCommentInboxMessagesByReceiver = `-- name: CountUnreadCommentInboxMessagesByReceiver :one
SELECT COUNT(*)::int4 AS unread_count
FROM inbox_comment_messages
WHERE receiver_uid = $1
  AND status = 'NORMAL'::inbox_message_status
  AND read_at IS NULL
`

func (q *Queries) CountUnreadCommentInboxMessagesByReceiver(ctx context.Context, receiverUid uuid.UUID) (int32, error) {
	row := q.db.QueryRow(ctx, countUnreadCommentInboxMessagesByReceiver, receiverUid)
	var unread_count int32
	err := row.Scan(&unread_count)
	return unread_count, err
}

const countUnreadFollowInboxMessagesByReceiver = `-- name: CountUnreadFollowInboxMessagesByReceiver :one
SELECT COUNT(*)::int4 AS unread_count
FROM inbox_follow_messages
WHERE receiver_uid = $1
  AND status = 'NORMAL'::inbox_message_status
  AND read_at IS NULL
`

func (q *Queries) CountUnreadFollowInboxMessagesByReceiver(ctx context.Context, receiverUid uuid.UUID) (int32, error) {
	row := q.db.QueryRow(ctx, countUnreadFollowInboxMessagesByReceiver, receiverUid)
	var unread_count int32
	err := row.Scan(&unread_count)
	return unread_count, err
}

const createCommentInboxMessage = `-- name: CreateCommentInboxMessage :one
INSERT INTO inbox_comment_messages (
  uid,
  receiver_uid,
  actor_uid,
  comment_uid,
  post_uid,
  parent_comment_uid
)
VALUES (
  $1,
  $2,
  $3,
  $4,
  $5,
  $6
)
RETURNING
  id,
  uid,
  receiver_uid,
  actor_uid,
  comment_uid,
  post_uid,
  parent_comment_uid,
  read_at,
  created_at
`

type CreateCommentInboxMessageParams struct {
	Uid              uuid.UUID
	ReceiverUid      uuid.UUID
	ActorUid         uuid.UUID
	CommentUid       uuid.UUID
	PostUid          uuid.UUID
	ParentCommentUid uuid.NullUUID
}

type CreateCommentInboxMessageRow struct {
	ID               int32
	Uid              uuid.UUID
	ReceiverUid      uuid.UUID
	ActorUid         uuid.UUID
	CommentUid       uuid.UUID
	PostUid          uuid.UUID
	ParentCommentUid uuid.NullUUID
	ReadAt           pgtype.Timestamptz
	CreatedAt        pgtype.Timestamptz
}

func (q *Queries) CreateCommentInboxMessage(ctx context.Context, arg CreateCommentInboxMessageParams) (CreateCommentInboxMessageRow, error) {
	row := q.db.QueryRow(ctx, createCommentInboxMessage,
		arg.Uid,
		arg.ReceiverUid,
		arg.ActorUid,
		arg.CommentUid,
		arg.PostUid,
		arg.ParentCommentUid,
	)
	var i CreateCommentInboxMessageRow
	err := row.Scan(
		&i.ID,
		&i.Uid,
		&i.ReceiverUid,
		&i.ActorUid,
		&i.CommentUid,
		&i.PostUid,
		&i.ParentCommentUid,
		&i.ReadAt,
		&i.CreatedAt,
	)
	return i, err
}

const createFollowInboxMessage = `-- name: CreateFollowInboxMessage :one
INSERT INTO inbox_follow_messages (
  uid,
  receiver_uid,
  actor_uid
)
VALUES (
  $1,
  $2,
  $3
)
RETURNING
  id,
  uid,
  receiver_uid,
  actor_uid,
  read_at,
  created_at
`

type CreateFollowInboxMessageParams struct {
	Uid         uuid.UUID
	ReceiverUid uuid.UUID
	ActorUid    uuid.UUID
}

type CreateFollowInboxMessageRow struct {
	ID          int32
	Uid         uuid.UUID
	ReceiverUid uuid.UUID
	ActorUid    uuid.UUID
	ReadAt      pgtype.Timestamptz
	CreatedAt   pgtype.Timestamptz
}

func (q *Queries) CreateFollowInboxMessage(ctx context.Context, arg CreateFollowInboxMessageParams) (CreateFollowInboxMessageRow, error) {
	row := q.db.QueryRow(ctx, createFollowInboxMessage, arg.Uid, arg.ReceiverUid, arg.ActorUid)
	var i CreateFollowInboxMessageRow
	err := row.Scan(
		&i.ID,
		&i.Uid,
		&i.ReceiverUid,
		&i.ActorUid,
		&i.ReadAt,
		&i.CreatedAt,
	)
	return i, err
}

const followInboxMessageNotExists = `-- name: FollowInboxMessageNotExists :one
SELECT NOT EXISTS (
  SELECT 1
  FROM inbox_follow_messages
  WHERE receiver_uid = $1
    AND actor_uid = $2
    AND status = 'NORMAL'::inbox_message_status
) AS not_exists
`

type FollowInboxMessageNotExistsParams struct {
	ReceiverUid uuid.UUID
	ActorUid    uuid.UUID
}

func (q *Queries) FollowInboxMessageNotExists(ctx context.Context, arg FollowInboxMessageNotExistsParams) (bool, error) {
	row := q.db.QueryRow(ctx, followInboxMessageNotExists, arg.ReceiverUid, arg.ActorUid)
	var not_exists bool
	err := row.Scan(&not_exists)
	return not_exists, err
}

const listCommentInboxMessages = `-- name: ListCommentInboxMessages :many
SELECT
  id,
  uid,
  receiver_uid,
  actor_uid,
  comment_uid,
  post_uid,
  parent_comment_uid,
  read_at,
  created_at
FROM inbox_comment_messages
WHERE receiver_uid = $1
  AND status = 'NORMAL'::inbox_message_status
  AND (
    $2::boolean IS NULL
    OR (read_at IS NOT NULL) = $2::boolean
  )
  AND (created_at, uid) < (
    $3::timestamptz,
    $4::uuid
  )
ORDER BY created_at DESC, uid DESC
LIMIT 20
`

type ListCommentInboxMessagesParams struct {
	ReceiverUid     uuid.UUID
	IsRead          pgtype.Bool
	CursorCreatedAt pgtype.Timestamptz
	CursorID        uuid.UUID
}

type ListCommentInboxMessagesRow struct {
	ID               int32
	Uid              uuid.UUID
	ReceiverUid      uuid.UUID
	ActorUid         uuid.UUID
	CommentUid       uuid.UUID
	PostUid          uuid.UUID
	ParentCommentUid uuid.NullUUID
	ReadAt           pgtype.Timestamptz
	CreatedAt        pgtype.Timestamptz
}

func (q *Queries) ListCommentInboxMessages(ctx context.Context, arg ListCommentInboxMessagesParams) ([]ListCommentInboxMessagesRow, error) {
	rows, err := q.db.Query(ctx, listCommentInboxMessages,
		arg.ReceiverUid,
		arg.IsRead,
		arg.CursorCreatedAt,
		arg.CursorID,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListCommentInboxMessagesRow
	for rows.Next() {
		var i ListCommentInboxMessagesRow
		if err := rows.Scan(
			&i.ID,
			&i.Uid,
			&i.ReceiverUid,
			&i.ActorUid,
			&i.CommentUid,
			&i.PostUid,
			&i.ParentCommentUid,
			&i.ReadAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFollowInboxMessages = `-- name: ListFollowInboxMessages :many
SELECT
  id,
  uid,
  receiver_uid,
  actor_uid,
  read_at,
  created_at
FROM inbox_follow_messages
WHERE receiver_uid = $1
  AND status = 'NORMAL'::inbox_message_status
  AND (
    $2::boolean IS NULL
    OR (read_at IS NOT NULL) = $2::boolean
  )
  AND (created_at, uid) < (
    $3::timestamptz,
    $4::uuid
  )
ORDER BY created_at DESC, uid DESC
LIMIT 20
`

type ListFollowInboxMessagesParams struct {
	ReceiverUid     uuid.UUID
	IsRead          pgtype.Bool
	CursorCreatedAt pgtype.Timestamptz
	CursorID        uuid.UUID
}

type ListFollowInboxMessagesRow struct {
	ID          int32
	Uid         uuid.UUID
	ReceiverUid uuid.UUID
	ActorUid    uuid.UUID
	ReadAt      pgtype.Timestamptz
	CreatedAt   pgtype.Timestamptz
}

func (q *Queries) ListFollowInboxMessages(ctx context.Context, arg ListFollowInboxMessagesParams) ([]ListFollowInboxMessagesRow, error) {
	rows, err := q.db.Query(ctx, listFollowInboxMessages,
		arg.ReceiverUid,
		arg.IsRead,
		arg.CursorCreatedAt,
		arg.CursorID,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListFollowInboxMessagesRow
	for rows.Next() {
		var i ListFollowInboxMessagesRow
		if err := rows.Scan(
			&i.ID,
			&i.Uid,
			&i.ReceiverUid,
			&i.ActorUid,
			&i.ReadAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markAllCommentInboxMessagesReadByReceiver = `-- name: MarkAllCommentInboxMessagesReadByReceiver :execrows
UPDATE inbox_comment_messages
SET read_at = now()
WHERE receiver_uid = $1
  AND status = 'NORMAL'::inbox_message_status
  AND read_at IS NULL
`

func (q *Queries) MarkAllCommentInboxMessagesReadByReceiver(ctx context.Context, receiverUid uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, markAllCommentInboxMessagesReadByReceiver, receiverUid)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const markAllFollowInboxMessagesReadByReceiver = `-- name: MarkAllFollowInboxMessagesReadByReceiver :execrows
UPDATE inbox_follow_messages
SET read_at = now()
WHERE receiver_uid = $1
  AND status = 'NORMAL'::inbox_message_status
  AND read_at IS NULL
`

func (q *Queries) MarkAllFollowInboxMessagesReadByReceiver(ctx context.Context, receiverUid uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, markAllFollowInboxMessagesReadByReceiver, receiverUid)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const markCommentInboxMessagesReadByUIDsAndReceiver = `-- name: MarkCommentInboxMessagesReadByUIDsAndReceiver :execrows
UPDATE inbox_comment_messages
SET read_at = now()
WHERE receiver_uid = $1
  AND uid = ANY($2::uuid[])
  AND status = 'NORMAL'::inbox_message_status
  AND read_at IS NULL
`

type MarkCommentInboxMessagesReadByUIDsAndReceiverParams struct {
	ReceiverUid uuid.UUID
	Uids        []uuid.UUID
}

func (q *Queries) MarkCommentInboxMessagesReadByUIDsAndReceiver(ctx context.Context, arg MarkCommentInboxMessagesReadByUIDsAndReceiverParams) (int64, error) {
	result, err := q.db.Exec(ctx, markCommentInboxMessagesReadByUIDsAndReceiver, arg.ReceiverUid, arg.Uids)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const markFollowInboxMessagesReadByUIDsAndReceiver = `-- name: MarkFollowInboxMessagesReadByUIDsAndReceiver :execrows
UPDATE inbox_follow_messages
SET read_at = now()
WHERE receiver_uid = $1
  AND uid = ANY($2::uuid[])
  AND status = 'NORMAL'::inbox_message_status
  AND read_at IS NULL
`

type MarkFollowInboxMessagesReadByUIDsAndReceiverParams struct {
	ReceiverUid uuid.UUID
	Uids        []uuid.UUID
}

func (q *Queries) MarkFollowInboxMessagesReadByUIDsAndReceiver(ctx context.Context, arg MarkFollowInboxMessagesReadByUIDsAndReceiverParams) (int64, error) {
	result, err := q.db.Exec(ctx, markFollowInboxMessagesReadByUIDsAndReceiver, arg.ReceiverUid, arg.Uids)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
