// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: inbox_message.sql

package db

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
	"github.com/lib/pq"
)

const archiveInboxMessageByUidAndReceiver = `-- name: ArchiveInboxMessageByUidAndReceiver :execrows
UPDATE inbox_messages
SET status = 'ARCHIVED'::message_status
WHERE uid = $1
  AND receiver_uid = $2
  AND status = 'NORMAL'::message_status
`

type ArchiveInboxMessageByUidAndReceiverParams struct {
	Uid         uuid.UUID
	ReceiverUid uuid.UUID
}

func (q *Queries) ArchiveInboxMessageByUidAndReceiver(ctx context.Context, arg ArchiveInboxMessageByUidAndReceiverParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, archiveInboxMessageByUidAndReceiver, arg.Uid, arg.ReceiverUid)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const countUnreadInboxMessagesByReceiver = `-- name: CountUnreadInboxMessagesByReceiver :one
SELECT COUNT(*)::int4 AS unread_count,
  COUNT(*) FILTER (
      WHERE type = 'FOLLOW'::message_type
    )::int4 AS follow_unread_count,
  COUNT(*) FILTER (
      WHERE type = 'COMMENT'::message_type
    )::int4 AS comment_unread_count
FROM inbox_messages
WHERE receiver_uid = $1
  AND status = 'NORMAL'::message_status
  AND is_read = false
`

type CountUnreadInboxMessagesByReceiverRow struct {
	UnreadCount        int32
	FollowUnreadCount  int32
	CommentUnreadCount int32
}

func (q *Queries) CountUnreadInboxMessagesByReceiver(ctx context.Context, receiverUid uuid.UUID) (CountUnreadInboxMessagesByReceiverRow, error) {
	row := q.db.QueryRowContext(ctx, countUnreadInboxMessagesByReceiver, receiverUid)
	var i CountUnreadInboxMessagesByReceiverRow
	err := row.Scan(&i.UnreadCount, &i.FollowUnreadCount, &i.CommentUnreadCount)
	return i, err
}

const createCommentInboxMessage = `-- name: CreateCommentInboxMessage :one
INSERT INTO inbox_messages (
    uid,
    receiver_uid,
    type,
    actor_uid,
    comment_uid,
    post_uid,
    parent_uid
  )
VALUES (
    $1,
    $2,
    'COMMENT'::message_type,
    $3,
    $4,
    $5,
    $6
  )
RETURNING id,
  uid
`

type CreateCommentInboxMessageParams struct {
	Uid         uuid.UUID
	ReceiverUid uuid.UUID
	ActorUid    uuid.UUID
	CommentUid  uuid.NullUUID
	PostUid     uuid.NullUUID
	ParentUid   uuid.NullUUID
}

type CreateCommentInboxMessageRow struct {
	ID  int32
	Uid uuid.UUID
}

func (q *Queries) CreateCommentInboxMessage(ctx context.Context, arg CreateCommentInboxMessageParams) (CreateCommentInboxMessageRow, error) {
	row := q.db.QueryRowContext(ctx, createCommentInboxMessage,
		arg.Uid,
		arg.ReceiverUid,
		arg.ActorUid,
		arg.CommentUid,
		arg.PostUid,
		arg.ParentUid,
	)
	var i CreateCommentInboxMessageRow
	err := row.Scan(&i.ID, &i.Uid)
	return i, err
}

const createFollowInboxMessage = `-- name: CreateFollowInboxMessage :execrows
INSERT INTO inbox_messages (uid, receiver_uid, type, actor_uid)
SELECT $1,
  $2,
  'FOLLOW'::message_type,
  $3
WHERE NOT EXISTS (
    SELECT 1
    FROM inbox_messages im
    WHERE im.receiver_uid = $2
      AND im.actor_uid = $3
      AND im.type = 'FOLLOW'::message_type
      AND im.status = 'NORMAL'::message_status
  )
`

type CreateFollowInboxMessageParams struct {
	Uid         uuid.UUID
	ReceiverUid uuid.UUID
	ActorUid    uuid.UUID
}

func (q *Queries) CreateFollowInboxMessage(ctx context.Context, arg CreateFollowInboxMessageParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, createFollowInboxMessage, arg.Uid, arg.ReceiverUid, arg.ActorUid)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const listCommentInboxMessages = `-- name: ListCommentInboxMessages :many
SELECT m.uid,
  m.receiver_uid,
  m.type,
  m.is_read,
  m.actor_uid,
  u.nickname AS actor_nickname,
  u.avatar_url AS actor_avatar_url,
  m.created_at,
  m.status,
  m.comment_uid,
  c.content AS comment_content,
  m.post_uid,
  m.parent_uid,
  COALESCE(pc.content, p.text, ''::text) AS parent_content
FROM inbox_messages m
  JOIN users u ON u.uid = m.actor_uid
  AND u.status = 'NORMAL'::user_status
  LEFT JOIN post_comments c ON c.uid = m.comment_uid
  AND c.status = 'NORMAL'::comment_status
  LEFT JOIN post_comments pc ON pc.uid = m.parent_uid
  AND pc.status = 'NORMAL'::comment_status
  LEFT JOIN posts p ON p.uid = m.parent_uid
  AND p.status = 'NORMAL'::post_status
WHERE m.receiver_uid = $1
  AND m.status = 'NORMAL'::message_status
  AND m.type = 'COMMENT'::message_type
  AND (
    $2::boolean IS NULL
    OR m.is_read = $2::boolean
  )
  AND (
    (
      $3::timestamptz IS NULL
      AND $4::uuid IS NULL
    )
    OR (m.created_at, m.uid) < (
      $3::timestamptz,
      $4::uuid
    )
  )
ORDER BY m.created_at DESC,
  m.uid DESC
LIMIT 20
`

type ListCommentInboxMessagesParams struct {
	ReceiverUid     uuid.UUID
	IsRead          sql.NullBool
	CursorCreatedAt sql.NullTime
	CursorID        uuid.NullUUID
}

type ListCommentInboxMessagesRow struct {
	Uid            uuid.UUID
	ReceiverUid    uuid.UUID
	Type           MessageType
	IsRead         bool
	ActorUid       uuid.UUID
	ActorNickname  string
	ActorAvatarUrl string
	CreatedAt      time.Time
	Status         MessageStatus
	CommentUid     uuid.NullUUID
	CommentContent sql.NullString
	PostUid        uuid.NullUUID
	ParentUid      uuid.NullUUID
	ParentContent  string
}

func (q *Queries) ListCommentInboxMessages(ctx context.Context, arg ListCommentInboxMessagesParams) ([]ListCommentInboxMessagesRow, error) {
	rows, err := q.db.QueryContext(ctx, listCommentInboxMessages,
		arg.ReceiverUid,
		arg.IsRead,
		arg.CursorCreatedAt,
		arg.CursorID,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListCommentInboxMessagesRow
	for rows.Next() {
		var i ListCommentInboxMessagesRow
		if err := rows.Scan(
			&i.Uid,
			&i.ReceiverUid,
			&i.Type,
			&i.IsRead,
			&i.ActorUid,
			&i.ActorNickname,
			&i.ActorAvatarUrl,
			&i.CreatedAt,
			&i.Status,
			&i.CommentUid,
			&i.CommentContent,
			&i.PostUid,
			&i.ParentUid,
			&i.ParentContent,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFollowInboxMessages = `-- name: ListFollowInboxMessages :many
SELECT m.uid,
  m.receiver_uid,
  m.type,
  m.is_read,
  m.actor_uid,
  u.nickname AS actor_nickname,
  u.avatar_url AS actor_avatar_url,
  m.created_at,
  m.status
FROM inbox_messages m
  JOIN users u ON u.uid = m.actor_uid
  AND u.status = 'NORMAL'::user_status
WHERE m.receiver_uid = $1
  AND m.status = 'NORMAL'::message_status
  AND m.type = 'FOLLOW'::message_type
  AND (
    $2::boolean IS NULL
    OR m.is_read = $2::boolean
  )
  AND (
    (
      $3::timestamptz IS NULL
      AND $4::uuid IS NULL
    )
    OR (m.created_at, m.uid) < (
      $3::timestamptz,
      $4::uuid
    )
  )
ORDER BY m.created_at DESC,
  m.uid DESC
LIMIT 20
`

type ListFollowInboxMessagesParams struct {
	ReceiverUid     uuid.UUID
	IsRead          sql.NullBool
	CursorCreatedAt sql.NullTime
	CursorID        uuid.NullUUID
}

type ListFollowInboxMessagesRow struct {
	Uid            uuid.UUID
	ReceiverUid    uuid.UUID
	Type           MessageType
	IsRead         bool
	ActorUid       uuid.UUID
	ActorNickname  string
	ActorAvatarUrl string
	CreatedAt      time.Time
	Status         MessageStatus
}

func (q *Queries) ListFollowInboxMessages(ctx context.Context, arg ListFollowInboxMessagesParams) ([]ListFollowInboxMessagesRow, error) {
	rows, err := q.db.QueryContext(ctx, listFollowInboxMessages,
		arg.ReceiverUid,
		arg.IsRead,
		arg.CursorCreatedAt,
		arg.CursorID,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListFollowInboxMessagesRow
	for rows.Next() {
		var i ListFollowInboxMessagesRow
		if err := rows.Scan(
			&i.Uid,
			&i.ReceiverUid,
			&i.Type,
			&i.IsRead,
			&i.ActorUid,
			&i.ActorNickname,
			&i.ActorAvatarUrl,
			&i.CreatedAt,
			&i.Status,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markAllInboxMessagesReadByReceiver = `-- name: MarkAllInboxMessagesReadByReceiver :execrows
UPDATE inbox_messages
SET is_read = true
WHERE receiver_uid = $1
  AND status = 'NORMAL'::message_status
  AND is_read = false
`

func (q *Queries) MarkAllInboxMessagesReadByReceiver(ctx context.Context, receiverUid uuid.UUID) (int64, error) {
	result, err := q.db.ExecContext(ctx, markAllInboxMessagesReadByReceiver, receiverUid)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const markInboxMessagesReadByUidsAndReceiver = `-- name: MarkInboxMessagesReadByUidsAndReceiver :execrows
UPDATE inbox_messages
SET is_read = true
WHERE receiver_uid = $1
  AND uid = ANY($2::uuid [])
  AND status = 'NORMAL'::message_status
  AND is_read = false
`

type MarkInboxMessagesReadByUidsAndReceiverParams struct {
	ReceiverUid uuid.UUID
	Uids        []uuid.UUID
}

func (q *Queries) MarkInboxMessagesReadByUidsAndReceiver(ctx context.Context, arg MarkInboxMessagesReadByUidsAndReceiverParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, markInboxMessagesReadByUidsAndReceiver, arg.ReceiverUid, pq.Array(arg.Uids))
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
