// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"database/sql/driver"
	"fmt"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type CommentStatus string

const (
	CommentStatusNORMAL   CommentStatus = "NORMAL"
	CommentStatusARCHIVED CommentStatus = "ARCHIVED"
)

func (e *CommentStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = CommentStatus(s)
	case string:
		*e = CommentStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for CommentStatus: %T", src)
	}
	return nil
}

type NullCommentStatus struct {
	CommentStatus CommentStatus
	Valid         bool // Valid is true if CommentStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullCommentStatus) Scan(value interface{}) error {
	if value == nil {
		ns.CommentStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.CommentStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullCommentStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.CommentStatus), nil
}

type FileStatus string

const (
	FileStatusNORMAL   FileStatus = "NORMAL"
	FileStatusARCHIVED FileStatus = "ARCHIVED"
)

func (e *FileStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = FileStatus(s)
	case string:
		*e = FileStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for FileStatus: %T", src)
	}
	return nil
}

type NullFileStatus struct {
	FileStatus FileStatus
	Valid      bool // Valid is true if FileStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullFileStatus) Scan(value interface{}) error {
	if value == nil {
		ns.FileStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.FileStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullFileStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.FileStatus), nil
}

type MessageStatus string

const (
	MessageStatusNORMAL   MessageStatus = "NORMAL"
	MessageStatusARCHIVED MessageStatus = "ARCHIVED"
)

func (e *MessageStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = MessageStatus(s)
	case string:
		*e = MessageStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for MessageStatus: %T", src)
	}
	return nil
}

type NullMessageStatus struct {
	MessageStatus MessageStatus
	Valid         bool // Valid is true if MessageStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullMessageStatus) Scan(value interface{}) error {
	if value == nil {
		ns.MessageStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.MessageStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullMessageStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.MessageStatus), nil
}

type MessageType string

const (
	MessageTypeCOMMENT MessageType = "COMMENT"
	MessageTypeFOLLOW  MessageType = "FOLLOW"
)

func (e *MessageType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = MessageType(s)
	case string:
		*e = MessageType(s)
	default:
		return fmt.Errorf("unsupported scan type for MessageType: %T", src)
	}
	return nil
}

type NullMessageType struct {
	MessageType MessageType
	Valid       bool // Valid is true if MessageType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullMessageType) Scan(value interface{}) error {
	if value == nil {
		ns.MessageType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.MessageType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullMessageType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.MessageType), nil
}

type PostStatus string

const (
	PostStatusNORMAL   PostStatus = "NORMAL"
	PostStatusARCHIVED PostStatus = "ARCHIVED"
)

func (e *PostStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = PostStatus(s)
	case string:
		*e = PostStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for PostStatus: %T", src)
	}
	return nil
}

type NullPostStatus struct {
	PostStatus PostStatus
	Valid      bool // Valid is true if PostStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullPostStatus) Scan(value interface{}) error {
	if value == nil {
		ns.PostStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.PostStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullPostStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.PostStatus), nil
}

type PostVisibility string

const (
	PostVisibilityPUBLIC  PostVisibility = "PUBLIC"
	PostVisibilityPRIVATE PostVisibility = "PRIVATE"
)

func (e *PostVisibility) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = PostVisibility(s)
	case string:
		*e = PostVisibility(s)
	default:
		return fmt.Errorf("unsupported scan type for PostVisibility: %T", src)
	}
	return nil
}

type NullPostVisibility struct {
	PostVisibility PostVisibility
	Valid          bool // Valid is true if PostVisibility is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullPostVisibility) Scan(value interface{}) error {
	if value == nil {
		ns.PostVisibility, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.PostVisibility.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullPostVisibility) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.PostVisibility), nil
}

type ReportStatus string

const (
	ReportStatusNORMAL   ReportStatus = "NORMAL"
	ReportStatusARCHIVED ReportStatus = "ARCHIVED"
)

func (e *ReportStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ReportStatus(s)
	case string:
		*e = ReportStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for ReportStatus: %T", src)
	}
	return nil
}

type NullReportStatus struct {
	ReportStatus ReportStatus
	Valid        bool // Valid is true if ReportStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullReportStatus) Scan(value interface{}) error {
	if value == nil {
		ns.ReportStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ReportStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullReportStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ReportStatus), nil
}

type ReportTargetType string

const (
	ReportTargetTypePOST    ReportTargetType = "POST"
	ReportTargetTypeCOMMENT ReportTargetType = "COMMENT"
	ReportTargetTypeUSER    ReportTargetType = "USER"
)

func (e *ReportTargetType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ReportTargetType(s)
	case string:
		*e = ReportTargetType(s)
	default:
		return fmt.Errorf("unsupported scan type for ReportTargetType: %T", src)
	}
	return nil
}

type NullReportTargetType struct {
	ReportTargetType ReportTargetType
	Valid            bool // Valid is true if ReportTargetType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullReportTargetType) Scan(value interface{}) error {
	if value == nil {
		ns.ReportTargetType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ReportTargetType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullReportTargetType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ReportTargetType), nil
}

type UserRole string

const (
	UserRoleHOST  UserRole = "HOST"
	UserRoleADMIN UserRole = "ADMIN"
	UserRoleUSER  UserRole = "USER"
)

func (e *UserRole) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = UserRole(s)
	case string:
		*e = UserRole(s)
	default:
		return fmt.Errorf("unsupported scan type for UserRole: %T", src)
	}
	return nil
}

type NullUserRole struct {
	UserRole UserRole
	Valid    bool // Valid is true if UserRole is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullUserRole) Scan(value interface{}) error {
	if value == nil {
		ns.UserRole, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.UserRole.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullUserRole) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.UserRole), nil
}

type UserStatus string

const (
	UserStatusNORMAL   UserStatus = "NORMAL"
	UserStatusARCHIVED UserStatus = "ARCHIVED"
)

func (e *UserStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = UserStatus(s)
	case string:
		*e = UserStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for UserStatus: %T", src)
	}
	return nil
}

type NullUserStatus struct {
	UserStatus UserStatus
	Valid      bool // Valid is true if UserStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullUserStatus) Scan(value interface{}) error {
	if value == nil {
		ns.UserStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.UserStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullUserStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.UserStatus), nil
}

type CommentLike struct {
	CommentUid uuid.UUID
	UserUid    uuid.UUID
	CreatedAt  pgtype.Timestamptz
}

type File struct {
	ID          int32
	Url         string
	Name        string
	ContentType string
	Size        int64
	Checksum    string
	Uploader    uuid.UUID
	Status      FileStatus
	CreatedAt   pgtype.Timestamptz
}

type InboxMessage struct {
	ID          int32
	Uid         uuid.UUID
	ReceiverUid uuid.UUID
	Type        MessageType
	IsRead      bool
	ActorUid    uuid.UUID
	CreatedAt   pgtype.Timestamptz
	Status      MessageStatus
	CommentUid  uuid.NullUUID
	PostUid     uuid.NullUUID
	ParentUid   uuid.NullUUID
}

type Post struct {
	ID              int32
	Uid             uuid.UUID
	Author          uuid.UUID
	Text            string
	Images          []string
	Attachments     []string
	CommentCount    int32
	CollectionCount int32
	LikeCount       int32
	Pinned          bool
	Visibility      PostVisibility
	LatestRepliedOn pgtype.Timestamptz
	Ip              string
	Status          PostStatus
	CreatedAt       pgtype.Timestamptz
	UpdatedAt       pgtype.Timestamptz
}

type PostCollection struct {
	PostUid   uuid.UUID
	UserUid   uuid.UUID
	CreatedAt pgtype.Timestamptz
}

type PostComment struct {
	ID               int32
	Uid              uuid.UUID
	PostUid          uuid.UUID
	AuthorUid        uuid.UUID
	RootUid          uuid.UUID
	ParentUid        uuid.NullUUID
	ReplyToAuthorUid uuid.NullUUID
	Content          string
	Images           []string
	ReplyCount       int32
	LikeCount        int32
	Ip               string
	Status           CommentStatus
	CreatedAt        pgtype.Timestamptz
	UpdatedAt        pgtype.Timestamptz
}

type PostLike struct {
	PostUid   uuid.UUID
	UserUid   uuid.UUID
	CreatedAt pgtype.Timestamptz
}

type PostTag struct {
	PostID int32
	TagID  int32
}

type RefreshToken struct {
	ID        int32
	Uid       uuid.UUID
	Token     string
	ExpiresAt pgtype.Timestamptz
	CreatedAt pgtype.Timestamptz
}

type Report struct {
	ID               int32
	Uid              uuid.UUID
	ReporterUid      uuid.UUID
	ReportTargetType ReportTargetType
	TargetUid        uuid.UUID
	Content          string
	Status           ReportStatus
	CreatedAt        pgtype.Timestamptz
	UpdatedAt        pgtype.Timestamptz
}

type Tag struct {
	ID   int32
	Name string
}

type User struct {
	ID             int32
	Uid            uuid.UUID
	Username       string
	Role           UserRole
	Email          string
	Nickname       string
	PasswordHash   string
	AvatarUrl      string
	FollowersCount int32
	FollowingCount int32
	Description    string
	Status         UserStatus
	CreatedAt      pgtype.Timestamptz
	UpdatedAt      pgtype.Timestamptz
}

type UserFollow struct {
	FollowerUid uuid.UUID
	FolloweeUid uuid.UUID
	CreatedAt   pgtype.Timestamptz
}
