// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: post_collection.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const decrementPostCollectionCount = `-- name: DecrementPostCollectionCount :one
UPDATE posts
SET collection_count = GREATEST(collection_count - 1, 0),
    updated_at = now()
WHERE uid = $1
RETURNING collection_count::int4
`

func (q *Queries) DecrementPostCollectionCount(ctx context.Context, postUid uuid.UUID) (int32, error) {
	row := q.db.QueryRow(ctx, decrementPostCollectionCount, postUid)
	var collection_count int32
	err := row.Scan(&collection_count)
	return collection_count, err
}

const deletePostCollectionEdge = `-- name: DeletePostCollectionEdge :execrows
DELETE FROM post_collections
WHERE post_uid = $1
  AND user_uid = $2
`

type DeletePostCollectionEdgeParams struct {
	PostUid uuid.UUID
	UserUid uuid.UUID
}

func (q *Queries) DeletePostCollectionEdge(ctx context.Context, arg DeletePostCollectionEdgeParams) (int64, error) {
	result, err := q.db.Exec(ctx, deletePostCollectionEdge, arg.PostUid, arg.UserUid)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getPostCollectionCount = `-- name: GetPostCollectionCount :one
SELECT collection_count::int4
FROM posts
WHERE uid = $1
`

func (q *Queries) GetPostCollectionCount(ctx context.Context, postUid uuid.UUID) (int32, error) {
	row := q.db.QueryRow(ctx, getPostCollectionCount, postUid)
	var collection_count int32
	err := row.Scan(&collection_count)
	return collection_count, err
}

const incrementPostCollectionCount = `-- name: IncrementPostCollectionCount :one
UPDATE posts
SET collection_count = collection_count + 1,
    updated_at = now()
WHERE uid = $1
RETURNING collection_count::int4
`

func (q *Queries) IncrementPostCollectionCount(ctx context.Context, postUid uuid.UUID) (int32, error) {
	row := q.db.QueryRow(ctx, incrementPostCollectionCount, postUid)
	var collection_count int32
	err := row.Scan(&collection_count)
	return collection_count, err
}

const insertPostCollectionEdge = `-- name: InsertPostCollectionEdge :execrows
INSERT INTO post_collections (post_uid, user_uid)
VALUES ($1, $2)
ON CONFLICT DO NOTHING
`

type InsertPostCollectionEdgeParams struct {
	PostUid uuid.UUID
	UserUid uuid.UUID
}

func (q *Queries) InsertPostCollectionEdge(ctx context.Context, arg InsertPostCollectionEdgeParams) (int64, error) {
	result, err := q.db.Exec(ctx, insertPostCollectionEdge, arg.PostUid, arg.UserUid)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const listPostsByCollector = `-- name: ListPostsByCollector :many
SELECT p.uid,
  p.author,
  u.uid AS author_uid,
  u.nickname AS author_nickname,
  u.avatar_url AS author_avatar_url,
  p.text,
  p.images,
  p.attachments,
  p.comment_count,
  p.collection_count,
  p.like_count,
  p.pinned,
  p.visibility,
  p.latest_replied_on,
  p.ip,
  p.status,
  p.created_at,
  p.updated_at,
  true AS collected,
  (pl.user_uid IS NOT NULL)::boolean AS liked,
  (uf.follower_uid IS NOT NULL)::boolean AS following,
  COALESCE(
    (
      SELECT array_agg(
          t.name
          ORDER BY t.name
        )
      FROM post_tags pt
        JOIN tags t ON t.id = pt.tag_id
      WHERE pt.post_id = p.id
    ),
    '{}'::text []
  )::text [] AS tag_names
FROM post_collections c
  JOIN posts p ON p.uid = c.post_uid
  JOIN users u ON u.uid = p.author
  AND u.status = 'NORMAL'::user_status
  LEFT JOIN post_likes pl ON pl.post_uid = p.uid
  AND pl.user_uid = $1
  LEFT JOIN user_follows uf ON uf.follower_uid = $1
  AND uf.followee_uid = p.author
WHERE p.status = 'NORMAL'::post_status
  AND c.user_uid = $1
  AND (
    p.visibility = 'PUBLIC'::post_visibility
    OR p.author = $1
  )
  AND (
    (
      $2::timestamptz IS NULL
      AND $3::uuid IS NULL
    )
    OR (p.created_at, p.uid) < (
      $2::timestamptz,
      $3::uuid
    )
  )
ORDER BY p.created_at DESC,
  p.uid DESC
LIMIT 20
`

type ListPostsByCollectorParams struct {
	Collector       uuid.UUID
	CursorCreatedAt pgtype.Timestamptz
	CursorID        uuid.NullUUID
}

type ListPostsByCollectorRow struct {
	Uid             uuid.UUID
	Author          uuid.UUID
	AuthorUid       uuid.UUID
	AuthorNickname  string
	AuthorAvatarUrl string
	Text            string
	Images          []string
	Attachments     []string
	CommentCount    int32
	CollectionCount int32
	LikeCount       int32
	Pinned          bool
	Visibility      PostVisibility
	LatestRepliedOn pgtype.Timestamptz
	Ip              string
	Status          PostStatus
	CreatedAt       pgtype.Timestamptz
	UpdatedAt       pgtype.Timestamptz
	Collected       bool
	Liked           bool
	Following       bool
	TagNames        []string
}

func (q *Queries) ListPostsByCollector(ctx context.Context, arg ListPostsByCollectorParams) ([]ListPostsByCollectorRow, error) {
	rows, err := q.db.Query(ctx, listPostsByCollector, arg.Collector, arg.CursorCreatedAt, arg.CursorID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPostsByCollectorRow
	for rows.Next() {
		var i ListPostsByCollectorRow
		if err := rows.Scan(
			&i.Uid,
			&i.Author,
			&i.AuthorUid,
			&i.AuthorNickname,
			&i.AuthorAvatarUrl,
			&i.Text,
			&i.Images,
			&i.Attachments,
			&i.CommentCount,
			&i.CollectionCount,
			&i.LikeCount,
			&i.Pinned,
			&i.Visibility,
			&i.LatestRepliedOn,
			&i.Ip,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Collected,
			&i.Liked,
			&i.Following,
			&i.TagNames,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
