// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: post.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const archivePostByUidAndAuthor = `-- name: ArchivePostByUidAndAuthor :execrows
UPDATE posts
SET status = 'ARCHIVED'::post_status,
  updated_at = now()
WHERE uid = $1
  AND author_uid = $2
  AND status = 'NORMAL'::post_status
`

type ArchivePostByUidAndAuthorParams struct {
	Uid       uuid.UUID
	AuthorUid uuid.UUID
}

func (q *Queries) ArchivePostByUidAndAuthor(ctx context.Context, arg ArchivePostByUidAndAuthorParams) (int64, error) {
	result, err := q.db.Exec(ctx, archivePostByUidAndAuthor, arg.Uid, arg.AuthorUid)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const createPost = `-- name: CreatePost :one
INSERT INTO posts (
  uid,
  author_uid,
  text,
  images,
  attachments,
  tags,
  visibility,
  pinned,
  ip
)
VALUES (
  $1,
  $2,
  $3,
  $4,
  $5,
  $6,
  $7,
  $8,
  $9
)
RETURNING
  id,
  uid,
  author_uid,
  text,
  images,
  attachments,
  tags,
  comment_count,
  collection_count,
  like_count,
  pinned,
  visibility,
  latest_replied_on,
  ip,
  status,
  created_at,
  updated_at
`

type CreatePostParams struct {
	Uid         uuid.UUID
	AuthorUid   uuid.UUID
	Text        string
	Images      []string
	Attachments []string
	Tags        []string
	Visibility  PostVisibility
	Pinned      bool
	Ip          string
}

func (q *Queries) CreatePost(ctx context.Context, arg CreatePostParams) (Post, error) {
	row := q.db.QueryRow(ctx, createPost,
		arg.Uid,
		arg.AuthorUid,
		arg.Text,
		arg.Images,
		arg.Attachments,
		arg.Tags,
		arg.Visibility,
		arg.Pinned,
		arg.Ip,
	)
	var i Post
	err := row.Scan(
		&i.ID,
		&i.Uid,
		&i.AuthorUid,
		&i.Text,
		&i.Images,
		&i.Attachments,
		&i.Tags,
		&i.CommentCount,
		&i.CollectionCount,
		&i.LikeCount,
		&i.Pinned,
		&i.Visibility,
		&i.LatestRepliedOn,
		&i.Ip,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const decrementPostCollectionCount = `-- name: DecrementPostCollectionCount :one
UPDATE posts
SET collection_count = GREATEST(collection_count - 1, 0),
    updated_at = now()
WHERE uid = $1
RETURNING collection_count
`

func (q *Queries) DecrementPostCollectionCount(ctx context.Context, postUid uuid.UUID) (int32, error) {
	row := q.db.QueryRow(ctx, decrementPostCollectionCount, postUid)
	var collection_count int32
	err := row.Scan(&collection_count)
	return collection_count, err
}

const decrementPostCommentCount = `-- name: DecrementPostCommentCount :one
UPDATE posts
SET comment_count = GREATEST(comment_count - 1, 0),
    updated_at = now()
WHERE uid = $1
RETURNING comment_count
`

func (q *Queries) DecrementPostCommentCount(ctx context.Context, postUid uuid.UUID) (int32, error) {
	row := q.db.QueryRow(ctx, decrementPostCommentCount, postUid)
	var comment_count int32
	err := row.Scan(&comment_count)
	return comment_count, err
}

const decrementPostLikeCount = `-- name: DecrementPostLikeCount :one
UPDATE posts
SET like_count = GREATEST(like_count - 1, 0),
    updated_at = now()
WHERE uid = $1
RETURNING like_count
`

func (q *Queries) DecrementPostLikeCount(ctx context.Context, postUid uuid.UUID) (int32, error) {
	row := q.db.QueryRow(ctx, decrementPostLikeCount, postUid)
	var like_count int32
	err := row.Scan(&like_count)
	return like_count, err
}

const deletePostCollectionEdge = `-- name: DeletePostCollectionEdge :execrows
DELETE FROM post_collections
WHERE post_uid = $1
  AND user_uid = $2
`

type DeletePostCollectionEdgeParams struct {
	PostUid uuid.UUID
	UserUid uuid.UUID
}

func (q *Queries) DeletePostCollectionEdge(ctx context.Context, arg DeletePostCollectionEdgeParams) (int64, error) {
	result, err := q.db.Exec(ctx, deletePostCollectionEdge, arg.PostUid, arg.UserUid)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deletePostLikeEdge = `-- name: DeletePostLikeEdge :execrows
DELETE FROM post_likes
WHERE post_uid = $1
  AND user_uid = $2
`

type DeletePostLikeEdgeParams struct {
	PostUid uuid.UUID
	UserUid uuid.UUID
}

func (q *Queries) DeletePostLikeEdge(ctx context.Context, arg DeletePostLikeEdgeParams) (int64, error) {
	result, err := q.db.Exec(ctx, deletePostLikeEdge, arg.PostUid, arg.UserUid)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getPostByUid = `-- name: GetPostByUid :one
SELECT
  id,
  uid,
  author_uid,
  text,
  images,
  attachments,
  tags,
  comment_count,
  collection_count,
  like_count,
  pinned,
  visibility,
  latest_replied_on,
  ip,
  status,
  created_at,
  updated_at
FROM posts
WHERE uid = $1
  AND status = 'NORMAL'::post_status
LIMIT 1
`

func (q *Queries) GetPostByUid(ctx context.Context, uid uuid.UUID) (Post, error) {
	row := q.db.QueryRow(ctx, getPostByUid, uid)
	var i Post
	err := row.Scan(
		&i.ID,
		&i.Uid,
		&i.AuthorUid,
		&i.Text,
		&i.Images,
		&i.Attachments,
		&i.Tags,
		&i.CommentCount,
		&i.CollectionCount,
		&i.LikeCount,
		&i.Pinned,
		&i.Visibility,
		&i.LatestRepliedOn,
		&i.Ip,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPostCollectionCount = `-- name: GetPostCollectionCount :one
SELECT collection_count
FROM posts
WHERE uid = $1
  AND status = 'NORMAL'::post_status
`

func (q *Queries) GetPostCollectionCount(ctx context.Context, postUid uuid.UUID) (int32, error) {
	row := q.db.QueryRow(ctx, getPostCollectionCount, postUid)
	var collection_count int32
	err := row.Scan(&collection_count)
	return collection_count, err
}

const getPostCommentCount = `-- name: GetPostCommentCount :one
SELECT comment_count
FROM posts
WHERE uid = $1
  AND status = 'NORMAL'::post_status
`

func (q *Queries) GetPostCommentCount(ctx context.Context, postUid uuid.UUID) (int32, error) {
	row := q.db.QueryRow(ctx, getPostCommentCount, postUid)
	var comment_count int32
	err := row.Scan(&comment_count)
	return comment_count, err
}

const getPostLikeCount = `-- name: GetPostLikeCount :one
SELECT like_count
FROM posts
WHERE uid = $1
  AND status = 'NORMAL'::post_status
`

func (q *Queries) GetPostLikeCount(ctx context.Context, postUid uuid.UUID) (int32, error) {
	row := q.db.QueryRow(ctx, getPostLikeCount, postUid)
	var like_count int32
	err := row.Scan(&like_count)
	return like_count, err
}

const getPostsByUIDs = `-- name: GetPostsByUIDs :many
SELECT
  id,
  uid,
  author_uid,
  text,
  images,
  attachments,
  tags,
  comment_count,
  collection_count,
  like_count,
  pinned,
  visibility,
  latest_replied_on,
  ip,
  status,
  created_at,
  updated_at
FROM posts
WHERE uid = ANY($1::uuid[])
  AND status = 'NORMAL'::post_status
`

func (q *Queries) GetPostsByUIDs(ctx context.Context, uids []uuid.UUID) ([]Post, error) {
	rows, err := q.db.Query(ctx, getPostsByUIDs, uids)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Post
	for rows.Next() {
		var i Post
		if err := rows.Scan(
			&i.ID,
			&i.Uid,
			&i.AuthorUid,
			&i.Text,
			&i.Images,
			&i.Attachments,
			&i.Tags,
			&i.CommentCount,
			&i.CollectionCount,
			&i.LikeCount,
			&i.Pinned,
			&i.Visibility,
			&i.LatestRepliedOn,
			&i.Ip,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const incrementPostCollectionCount = `-- name: IncrementPostCollectionCount :one
UPDATE posts
SET collection_count = collection_count + 1,
    updated_at = now()
WHERE uid = $1
  AND status = 'NORMAL'::post_status
RETURNING collection_count
`

func (q *Queries) IncrementPostCollectionCount(ctx context.Context, postUid uuid.UUID) (int32, error) {
	row := q.db.QueryRow(ctx, incrementPostCollectionCount, postUid)
	var collection_count int32
	err := row.Scan(&collection_count)
	return collection_count, err
}

const incrementPostCommentCount = `-- name: IncrementPostCommentCount :one
UPDATE posts
SET comment_count = comment_count + 1,
    latest_replied_on = now(),
    updated_at = now()
WHERE uid = $1
  AND status = 'NORMAL'::post_status
RETURNING comment_count
`

func (q *Queries) IncrementPostCommentCount(ctx context.Context, postUid uuid.UUID) (int32, error) {
	row := q.db.QueryRow(ctx, incrementPostCommentCount, postUid)
	var comment_count int32
	err := row.Scan(&comment_count)
	return comment_count, err
}

const incrementPostLikeCount = `-- name: IncrementPostLikeCount :one
UPDATE posts
SET like_count = like_count + 1,
    updated_at = now()
WHERE uid = $1
  AND status = 'NORMAL'::post_status
RETURNING like_count
`

func (q *Queries) IncrementPostLikeCount(ctx context.Context, postUid uuid.UUID) (int32, error) {
	row := q.db.QueryRow(ctx, incrementPostLikeCount, postUid)
	var like_count int32
	err := row.Scan(&like_count)
	return like_count, err
}

const insertPostCollectionEdge = `-- name: InsertPostCollectionEdge :execrows
INSERT INTO post_collections (post_uid, user_uid)
SELECT p.uid, $1
FROM posts p
WHERE p.uid = $2
  AND p.status = 'NORMAL'::post_status
ON CONFLICT DO NOTHING
`

type InsertPostCollectionEdgeParams struct {
	UserUid uuid.UUID
	PostUid uuid.UUID
}

func (q *Queries) InsertPostCollectionEdge(ctx context.Context, arg InsertPostCollectionEdgeParams) (int64, error) {
	result, err := q.db.Exec(ctx, insertPostCollectionEdge, arg.UserUid, arg.PostUid)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const insertPostLikeEdge = `-- name: InsertPostLikeEdge :execrows
INSERT INTO post_likes (post_uid, user_uid)
SELECT p.uid, $1
FROM posts p
WHERE p.uid = $2
  AND p.status = 'NORMAL'::post_status
ON CONFLICT DO NOTHING
`

type InsertPostLikeEdgeParams struct {
	UserUid uuid.UUID
	PostUid uuid.UUID
}

func (q *Queries) InsertPostLikeEdge(ctx context.Context, arg InsertPostLikeEdgeParams) (int64, error) {
	result, err := q.db.Exec(ctx, insertPostLikeEdge, arg.UserUid, arg.PostUid)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const isPostCollected = `-- name: IsPostCollected :one
SELECT EXISTS (
  SELECT 1
  FROM post_collections pc
  JOIN posts p ON p.uid = pc.post_uid
  WHERE pc.post_uid = $1
    AND pc.user_uid = $2
    AND p.status = 'NORMAL'::post_status
) AS is_collected
`

type IsPostCollectedParams struct {
	PostUid uuid.UUID
	UserUid uuid.UUID
}

func (q *Queries) IsPostCollected(ctx context.Context, arg IsPostCollectedParams) (bool, error) {
	row := q.db.QueryRow(ctx, isPostCollected, arg.PostUid, arg.UserUid)
	var is_collected bool
	err := row.Scan(&is_collected)
	return is_collected, err
}

const isPostLiked = `-- name: IsPostLiked :one
SELECT EXISTS (
  SELECT 1
  FROM post_likes pl
  JOIN posts p ON p.uid = pl.post_uid
  WHERE pl.post_uid = $1
    AND pl.user_uid = $2
    AND p.status = 'NORMAL'::post_status
) AS is_liked
`

type IsPostLikedParams struct {
	PostUid uuid.UUID
	UserUid uuid.UUID
}

func (q *Queries) IsPostLiked(ctx context.Context, arg IsPostLikedParams) (bool, error) {
	row := q.db.QueryRow(ctx, isPostLiked, arg.PostUid, arg.UserUid)
	var is_liked bool
	err := row.Scan(&is_liked)
	return is_liked, err
}

const listCollectedPostRefsByUser = `-- name: ListCollectedPostRefsByUser :many
SELECT
  pc.post_uid,
  pc.created_at AS collected_at
FROM post_collections pc
JOIN posts p ON p.uid = pc.post_uid
WHERE pc.user_uid = $1
  AND p.status = 'NORMAL'::post_status
  AND (pc.created_at, pc.post_uid) < (
    $2::timestamptz,
    $3::uuid
  )
ORDER BY pc.created_at DESC, pc.post_uid DESC
LIMIT 20
`

type ListCollectedPostRefsByUserParams struct {
	UserUid         uuid.UUID
	CursorCreatedAt pgtype.Timestamptz
	CursorID        uuid.UUID
}

type ListCollectedPostRefsByUserRow struct {
	PostUid     uuid.UUID
	CollectedAt pgtype.Timestamptz
}

func (q *Queries) ListCollectedPostRefsByUser(ctx context.Context, arg ListCollectedPostRefsByUserParams) ([]ListCollectedPostRefsByUserRow, error) {
	rows, err := q.db.Query(ctx, listCollectedPostRefsByUser, arg.UserUid, arg.CursorCreatedAt, arg.CursorID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListCollectedPostRefsByUserRow
	for rows.Next() {
		var i ListCollectedPostRefsByUserRow
		if err := rows.Scan(&i.PostUid, &i.CollectedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCollectedPostUIDsByUserAndPostUIDs = `-- name: ListCollectedPostUIDsByUserAndPostUIDs :many
SELECT pc.post_uid
FROM post_collections pc
JOIN posts p ON p.uid = pc.post_uid
WHERE pc.user_uid = $1
  AND pc.post_uid = ANY($2::uuid[])
  AND p.status = 'NORMAL'::post_status
`

type ListCollectedPostUIDsByUserAndPostUIDsParams struct {
	UserUid  uuid.UUID
	PostUids []uuid.UUID
}

func (q *Queries) ListCollectedPostUIDsByUserAndPostUIDs(ctx context.Context, arg ListCollectedPostUIDsByUserAndPostUIDsParams) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, listCollectedPostUIDsByUserAndPostUIDs, arg.UserUid, arg.PostUids)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []uuid.UUID
	for rows.Next() {
		var post_uid uuid.UUID
		if err := rows.Scan(&post_uid); err != nil {
			return nil, err
		}
		items = append(items, post_uid)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLikedPostUIDsByUserAndPostUIDs = `-- name: ListLikedPostUIDsByUserAndPostUIDs :many
SELECT pl.post_uid
FROM post_likes pl
JOIN posts p ON p.uid = pl.post_uid
WHERE pl.user_uid = $1
  AND pl.post_uid = ANY($2::uuid[])
  AND p.status = 'NORMAL'::post_status
`

type ListLikedPostUIDsByUserAndPostUIDsParams struct {
	UserUid  uuid.UUID
	PostUids []uuid.UUID
}

func (q *Queries) ListLikedPostUIDsByUserAndPostUIDs(ctx context.Context, arg ListLikedPostUIDsByUserAndPostUIDsParams) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, listLikedPostUIDsByUserAndPostUIDs, arg.UserUid, arg.PostUids)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []uuid.UUID
	for rows.Next() {
		var post_uid uuid.UUID
		if err := rows.Scan(&post_uid); err != nil {
			return nil, err
		}
		items = append(items, post_uid)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPostsByAuthor = `-- name: ListPostsByAuthor :many
SELECT
  id,
  uid,
  author_uid,
  text,
  images,
  attachments,
  tags,
  comment_count,
  collection_count,
  like_count,
  pinned,
  visibility,
  latest_replied_on,
  ip,
  status,
  created_at,
  updated_at
FROM posts
WHERE status = 'NORMAL'::post_status
  AND author_uid = $1
  AND (
    NOT $2::boolean
    OR visibility = 'PUBLIC'::post_visibility
  )
  AND (created_at, uid) < (
    $3::timestamptz,
    $4::uuid
  )
ORDER BY created_at DESC, uid DESC
LIMIT 20
`

type ListPostsByAuthorParams struct {
	AuthorUid       uuid.UUID
	OnlyPublic      bool
	CursorCreatedAt pgtype.Timestamptz
	CursorID        uuid.UUID
}

func (q *Queries) ListPostsByAuthor(ctx context.Context, arg ListPostsByAuthorParams) ([]Post, error) {
	rows, err := q.db.Query(ctx, listPostsByAuthor,
		arg.AuthorUid,
		arg.OnlyPublic,
		arg.CursorCreatedAt,
		arg.CursorID,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Post
	for rows.Next() {
		var i Post
		if err := rows.Scan(
			&i.ID,
			&i.Uid,
			&i.AuthorUid,
			&i.Text,
			&i.Images,
			&i.Attachments,
			&i.Tags,
			&i.CommentCount,
			&i.CollectionCount,
			&i.LikeCount,
			&i.Pinned,
			&i.Visibility,
			&i.LatestRepliedOn,
			&i.Ip,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPostsByTag = `-- name: ListPostsByTag :many
SELECT
  id,
  uid,
  author_uid,
  text,
  images,
  attachments,
  tags,
  comment_count,
  collection_count,
  like_count,
  pinned,
  visibility,
  latest_replied_on,
  ip,
  status,
  created_at,
  updated_at
FROM posts
WHERE status = 'NORMAL'::post_status
  AND visibility = 'PUBLIC'::post_visibility
  AND tags @> ARRAY[$1::text]
  AND (created_at, uid) < (
    $2::timestamptz,
    $3::uuid
  )
ORDER BY created_at DESC, uid DESC
LIMIT 20
`

type ListPostsByTagParams struct {
	TagName         string
	CursorCreatedAt pgtype.Timestamptz
	CursorID        uuid.UUID
}

func (q *Queries) ListPostsByTag(ctx context.Context, arg ListPostsByTagParams) ([]Post, error) {
	rows, err := q.db.Query(ctx, listPostsByTag, arg.TagName, arg.CursorCreatedAt, arg.CursorID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Post
	for rows.Next() {
		var i Post
		if err := rows.Scan(
			&i.ID,
			&i.Uid,
			&i.AuthorUid,
			&i.Text,
			&i.Images,
			&i.Attachments,
			&i.Tags,
			&i.CommentCount,
			&i.CollectionCount,
			&i.LikeCount,
			&i.Pinned,
			&i.Visibility,
			&i.LatestRepliedOn,
			&i.Ip,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPostsPublic = `-- name: ListPostsPublic :many
SELECT
  id,
  uid,
  author_uid,
  text,
  images,
  attachments,
  tags,
  comment_count,
  collection_count,
  like_count,
  pinned,
  visibility,
  latest_replied_on,
  ip,
  status,
  created_at,
  updated_at
FROM posts
WHERE status = 'NORMAL'::post_status
  AND visibility = 'PUBLIC'::post_visibility
  AND (created_at, uid) < (
    $1::timestamptz,
    $2::uuid
  )
ORDER BY created_at DESC, uid DESC
LIMIT 20
`

type ListPostsPublicParams struct {
	CursorCreatedAt pgtype.Timestamptz
	CursorID        uuid.UUID
}

func (q *Queries) ListPostsPublic(ctx context.Context, arg ListPostsPublicParams) ([]Post, error) {
	rows, err := q.db.Query(ctx, listPostsPublic, arg.CursorCreatedAt, arg.CursorID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Post
	for rows.Next() {
		var i Post
		if err := rows.Scan(
			&i.ID,
			&i.Uid,
			&i.AuthorUid,
			&i.Text,
			&i.Images,
			&i.Attachments,
			&i.Tags,
			&i.CommentCount,
			&i.CollectionCount,
			&i.LikeCount,
			&i.Pinned,
			&i.Visibility,
			&i.LatestRepliedOn,
			&i.Ip,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updatePostByUidAndAuthor = `-- name: UpdatePostByUidAndAuthor :one
UPDATE posts
SET text = COALESCE($1, text),
  images = COALESCE($2::text [], images),
  attachments = COALESCE($3::text [], attachments),
  tags = COALESCE($4::text [], tags),
  visibility = COALESCE(
    $5::post_visibility,
    visibility
  ),
  pinned = COALESCE($6::boolean, pinned),
  updated_at = now()
WHERE uid = $7
  AND author_uid = $8
  AND status = 'NORMAL'::post_status
RETURNING
  id,
  uid,
  author_uid,
  text,
  images,
  attachments,
  tags,
  comment_count,
  collection_count,
  like_count,
  pinned,
  visibility,
  latest_replied_on,
  ip,
  status,
  created_at,
  updated_at
`

type UpdatePostByUidAndAuthorParams struct {
	Text        pgtype.Text
	Images      []string
	Attachments []string
	Tags        []string
	Visibility  NullPostVisibility
	Pinned      pgtype.Bool
	Uid         uuid.UUID
	AuthorUid   uuid.UUID
}

func (q *Queries) UpdatePostByUidAndAuthor(ctx context.Context, arg UpdatePostByUidAndAuthorParams) (Post, error) {
	row := q.db.QueryRow(ctx, updatePostByUidAndAuthor,
		arg.Text,
		arg.Images,
		arg.Attachments,
		arg.Tags,
		arg.Visibility,
		arg.Pinned,
		arg.Uid,
		arg.AuthorUid,
	)
	var i Post
	err := row.Scan(
		&i.ID,
		&i.Uid,
		&i.AuthorUid,
		&i.Text,
		&i.Images,
		&i.Attachments,
		&i.Tags,
		&i.CommentCount,
		&i.CollectionCount,
		&i.LikeCount,
		&i.Pinned,
		&i.Visibility,
		&i.LatestRepliedOn,
		&i.Ip,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
