// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: post_list.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const listPostsByAuthor = `-- name: ListPostsByAuthor :many
SELECT p.uid,
  p.author,
  u.uid AS author_uid,
  u.nickname AS author_nickname,
  u.avatar_url AS author_avatar_url,
  p.text,
  p.images,
  p.attachments,
  p.comment_count,
  p.collection_count,
  p.like_count,
  p.pinned,
  p.visibility,
  p.latest_replied_on,
  p.ip,
  p.status,
  p.created_at,
  p.updated_at,
  (pl.user_uid IS NOT NULL)::boolean AS liked,
  (pc.user_uid IS NOT NULL)::boolean AS collected,
  (uf.follower_uid IS NOT NULL)::boolean AS following,
  COALESCE(
    (
      SELECT array_agg(t.name ORDER BY t.name)
      FROM post_tags pt
      JOIN tags t ON t.id = pt.tag_id
      WHERE pt.post_id = p.id
    ),
    '{}'::text[]
  )::text[] AS tag_names
FROM posts p
JOIN users u ON u.uid = p.author
  AND u.status = 'NORMAL'::user_status
LEFT JOIN post_likes pl ON pl.post_uid = p.uid
  AND pl.user_uid = $1::uuid
LEFT JOIN post_collections pc ON pc.post_uid = p.uid
  AND pc.user_uid = $1::uuid
LEFT JOIN user_follows uf ON uf.follower_uid = $1::uuid
  AND uf.followee_uid = p.author
WHERE p.status = 'NORMAL'::post_status
  AND p.author = $2
  AND (
    p.visibility = 'PUBLIC'::post_visibility
    OR p.author = $1::uuid
  )
  AND (p.created_at, p.uid) < (
    $3::timestamptz,
    $4::uuid
  )
ORDER BY p.created_at DESC, p.uid DESC
LIMIT 20
`

type ListPostsByAuthorParams struct {
	Viewer          uuid.NullUUID
	AuthorUid       uuid.UUID
	CursorCreatedAt pgtype.Timestamptz
	CursorID        uuid.UUID
}

type ListPostsByAuthorRow struct {
	Uid             uuid.UUID
	Author          uuid.UUID
	AuthorUid       uuid.UUID
	AuthorNickname  string
	AuthorAvatarUrl string
	Text            string
	Images          []string
	Attachments     []string
	CommentCount    int32
	CollectionCount int32
	LikeCount       int32
	Pinned          bool
	Visibility      PostVisibility
	LatestRepliedOn pgtype.Timestamptz
	Ip              string
	Status          PostStatus
	CreatedAt       pgtype.Timestamptz
	UpdatedAt       pgtype.Timestamptz
	Liked           bool
	Collected       bool
	Following       bool
	TagNames        []string
}

func (q *Queries) ListPostsByAuthor(ctx context.Context, arg ListPostsByAuthorParams) ([]ListPostsByAuthorRow, error) {
	rows, err := q.db.Query(ctx, listPostsByAuthor,
		arg.Viewer,
		arg.AuthorUid,
		arg.CursorCreatedAt,
		arg.CursorID,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPostsByAuthorRow
	for rows.Next() {
		var i ListPostsByAuthorRow
		if err := rows.Scan(
			&i.Uid,
			&i.Author,
			&i.AuthorUid,
			&i.AuthorNickname,
			&i.AuthorAvatarUrl,
			&i.Text,
			&i.Images,
			&i.Attachments,
			&i.CommentCount,
			&i.CollectionCount,
			&i.LikeCount,
			&i.Pinned,
			&i.Visibility,
			&i.LatestRepliedOn,
			&i.Ip,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Liked,
			&i.Collected,
			&i.Following,
			&i.TagNames,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPostsByTag = `-- name: ListPostsByTag :many
SELECT p.uid,
  p.author,
  u.uid AS author_uid,
  u.nickname AS author_nickname,
  u.avatar_url AS author_avatar_url,
  p.text,
  p.images,
  p.attachments,
  p.comment_count,
  p.collection_count,
  p.like_count,
  p.pinned,
  p.visibility,
  p.latest_replied_on,
  p.ip,
  p.status,
  p.created_at,
  p.updated_at,
  (pl.user_uid IS NOT NULL)::boolean AS liked,
  (pc.user_uid IS NOT NULL)::boolean AS collected,
  (uf.follower_uid IS NOT NULL)::boolean AS following,
  COALESCE(
    (
      SELECT array_agg(t.name ORDER BY t.name)
      FROM post_tags pt
      JOIN tags t ON t.id = pt.tag_id
      WHERE pt.post_id = p.id
    ),
    '{}'::text[]
  )::text[] AS tag_names
FROM posts p
JOIN users u ON u.uid = p.author
  AND u.status = 'NORMAL'::user_status
LEFT JOIN post_likes pl ON pl.post_uid = p.uid
  AND pl.user_uid = $1::uuid
LEFT JOIN post_collections pc ON pc.post_uid = p.uid
  AND pc.user_uid = $1::uuid
LEFT JOIN user_follows uf ON uf.follower_uid = $1::uuid
  AND uf.followee_uid = p.author
WHERE p.status = 'NORMAL'::post_status
  AND (
    p.visibility = 'PUBLIC'::post_visibility
    OR p.author = $1::uuid
  )
  AND EXISTS (
    SELECT 1
    FROM post_tags pt
    JOIN tags t ON t.id = pt.tag_id
    WHERE pt.post_id = p.id
      AND t.name = $2
  )
  AND (p.created_at, p.uid) < (
    $3::timestamptz,
    $4::uuid
  )
ORDER BY p.created_at DESC, p.uid DESC
LIMIT 20
`

type ListPostsByTagParams struct {
	Viewer          uuid.NullUUID
	TagName         string
	CursorCreatedAt pgtype.Timestamptz
	CursorID        uuid.UUID
}

type ListPostsByTagRow struct {
	Uid             uuid.UUID
	Author          uuid.UUID
	AuthorUid       uuid.UUID
	AuthorNickname  string
	AuthorAvatarUrl string
	Text            string
	Images          []string
	Attachments     []string
	CommentCount    int32
	CollectionCount int32
	LikeCount       int32
	Pinned          bool
	Visibility      PostVisibility
	LatestRepliedOn pgtype.Timestamptz
	Ip              string
	Status          PostStatus
	CreatedAt       pgtype.Timestamptz
	UpdatedAt       pgtype.Timestamptz
	Liked           bool
	Collected       bool
	Following       bool
	TagNames        []string
}

func (q *Queries) ListPostsByTag(ctx context.Context, arg ListPostsByTagParams) ([]ListPostsByTagRow, error) {
	rows, err := q.db.Query(ctx, listPostsByTag,
		arg.Viewer,
		arg.TagName,
		arg.CursorCreatedAt,
		arg.CursorID,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPostsByTagRow
	for rows.Next() {
		var i ListPostsByTagRow
		if err := rows.Scan(
			&i.Uid,
			&i.Author,
			&i.AuthorUid,
			&i.AuthorNickname,
			&i.AuthorAvatarUrl,
			&i.Text,
			&i.Images,
			&i.Attachments,
			&i.CommentCount,
			&i.CollectionCount,
			&i.LikeCount,
			&i.Pinned,
			&i.Visibility,
			&i.LatestRepliedOn,
			&i.Ip,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Liked,
			&i.Collected,
			&i.Following,
			&i.TagNames,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPostsPublic = `-- name: ListPostsPublic :many
SELECT p.uid,
  p.author,
  u.uid AS author_uid,
  u.nickname AS author_nickname,
  u.avatar_url AS author_avatar_url,
  p.text,
  p.images,
  p.attachments,
  p.comment_count,
  p.collection_count,
  p.like_count,
  p.pinned,
  p.visibility,
  p.latest_replied_on,
  p.ip,
  p.status,
  p.created_at,
  p.updated_at,
  (pl.user_uid IS NOT NULL)::boolean AS liked,
  (pc.user_uid IS NOT NULL)::boolean AS collected,
  (uf.follower_uid IS NOT NULL)::boolean AS following,
  COALESCE(
    (
      SELECT array_agg(t.name ORDER BY t.name)
      FROM post_tags pt
      JOIN tags t ON t.id = pt.tag_id
      WHERE pt.post_id = p.id
    ),
    '{}'::text[]
  )::text[] AS tag_names
FROM posts p
JOIN users u ON u.uid = p.author
  AND u.status = 'NORMAL'::user_status
LEFT JOIN post_likes pl ON pl.post_uid = p.uid
  AND pl.user_uid = $1::uuid
LEFT JOIN post_collections pc ON pc.post_uid = p.uid
  AND pc.user_uid = $1::uuid
LEFT JOIN user_follows uf ON uf.follower_uid = $1::uuid
  AND uf.followee_uid = p.author
WHERE p.status = 'NORMAL'::post_status
  AND p.visibility = 'PUBLIC'::post_visibility
  AND (p.created_at, p.uid) < (
    $2::timestamptz,
    $3::uuid
  )
ORDER BY p.created_at DESC, p.uid DESC
LIMIT 20
`

type ListPostsPublicParams struct {
	Viewer          uuid.NullUUID
	CursorCreatedAt pgtype.Timestamptz
	CursorID        uuid.UUID
}

type ListPostsPublicRow struct {
	Uid             uuid.UUID
	Author          uuid.UUID
	AuthorUid       uuid.UUID
	AuthorNickname  string
	AuthorAvatarUrl string
	Text            string
	Images          []string
	Attachments     []string
	CommentCount    int32
	CollectionCount int32
	LikeCount       int32
	Pinned          bool
	Visibility      PostVisibility
	LatestRepliedOn pgtype.Timestamptz
	Ip              string
	Status          PostStatus
	CreatedAt       pgtype.Timestamptz
	UpdatedAt       pgtype.Timestamptz
	Liked           bool
	Collected       bool
	Following       bool
	TagNames        []string
}

func (q *Queries) ListPostsPublic(ctx context.Context, arg ListPostsPublicParams) ([]ListPostsPublicRow, error) {
	rows, err := q.db.Query(ctx, listPostsPublic, arg.Viewer, arg.CursorCreatedAt, arg.CursorID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPostsPublicRow
	for rows.Next() {
		var i ListPostsPublicRow
		if err := rows.Scan(
			&i.Uid,
			&i.Author,
			&i.AuthorUid,
			&i.AuthorNickname,
			&i.AuthorAvatarUrl,
			&i.Text,
			&i.Images,
			&i.Attachments,
			&i.CommentCount,
			&i.CollectionCount,
			&i.LikeCount,
			&i.Pinned,
			&i.Visibility,
			&i.LatestRepliedOn,
			&i.Ip,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Liked,
			&i.Collected,
			&i.Following,
			&i.TagNames,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
