// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: post_like.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const decrementPostLikeCount = `-- name: DecrementPostLikeCount :one
UPDATE posts
SET like_count = GREATEST(like_count - 1, 0),
    updated_at = now()
WHERE uid = $1
RETURNING like_count::int4
`

func (q *Queries) DecrementPostLikeCount(ctx context.Context, postUid uuid.UUID) (int32, error) {
	row := q.db.QueryRow(ctx, decrementPostLikeCount, postUid)
	var like_count int32
	err := row.Scan(&like_count)
	return like_count, err
}

const deletePostLikeEdge = `-- name: DeletePostLikeEdge :execrows
DELETE FROM post_likes
WHERE post_uid = $1
  AND user_uid = $2
`

type DeletePostLikeEdgeParams struct {
	PostUid uuid.UUID
	UserUid uuid.UUID
}

func (q *Queries) DeletePostLikeEdge(ctx context.Context, arg DeletePostLikeEdgeParams) (int64, error) {
	result, err := q.db.Exec(ctx, deletePostLikeEdge, arg.PostUid, arg.UserUid)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getPostLikeCount = `-- name: GetPostLikeCount :one
SELECT like_count::int4
FROM posts
WHERE uid = $1
`

func (q *Queries) GetPostLikeCount(ctx context.Context, postUid uuid.UUID) (int32, error) {
	row := q.db.QueryRow(ctx, getPostLikeCount, postUid)
	var like_count int32
	err := row.Scan(&like_count)
	return like_count, err
}

const incrementPostLikeCount = `-- name: IncrementPostLikeCount :one
UPDATE posts
SET like_count = like_count + 1,
    updated_at = now()
WHERE uid = $1
RETURNING like_count::int4
`

func (q *Queries) IncrementPostLikeCount(ctx context.Context, postUid uuid.UUID) (int32, error) {
	row := q.db.QueryRow(ctx, incrementPostLikeCount, postUid)
	var like_count int32
	err := row.Scan(&like_count)
	return like_count, err
}

const insertPostLikeEdge = `-- name: InsertPostLikeEdge :execrows
INSERT INTO post_likes (post_uid, user_uid)
VALUES ($1, $2)
ON CONFLICT DO NOTHING
`

type InsertPostLikeEdgeParams struct {
	PostUid uuid.UUID
	UserUid uuid.UUID
}

func (q *Queries) InsertPostLikeEdge(ctx context.Context, arg InsertPostLikeEdgeParams) (int64, error) {
	result, err := q.db.Exec(ctx, insertPostLikeEdge, arg.PostUid, arg.UserUid)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
