// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: post.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const archivePostByUidAndAuthor = `-- name: ArchivePostByUidAndAuthor :execrows
UPDATE posts
SET status = 'ARCHIVED'::post_status,
  updated_at = now()
WHERE uid = $1
  AND author = $2
  AND status = 'NORMAL'::post_status
`

type ArchivePostByUidAndAuthorParams struct {
	Uid    uuid.UUID
	Author uuid.UUID
}

func (q *Queries) ArchivePostByUidAndAuthor(ctx context.Context, arg ArchivePostByUidAndAuthorParams) (int64, error) {
	result, err := q.db.Exec(ctx, archivePostByUidAndAuthor, arg.Uid, arg.Author)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const createPost = `-- name: CreatePost :one
INSERT INTO posts (
    uid,
    author,
    text,
    images,
    attachments,
    visibility,
    pinned,
    ip
  )
VALUES (
    $1,
    $2,
    $3,
    COALESCE($4::text [], '{}'::text []),
    COALESCE($5::text [], '{}'::text []),
    COALESCE(
      $6::post_visibility,
      'PUBLIC'::post_visibility
    ),
    $7,
    $8
  )
RETURNING id,
  uid
`

type CreatePostParams struct {
	Uid         uuid.UUID
	Author      uuid.UUID
	Text        string
	Images      []string
	Attachments []string
	Visibility  NullPostVisibility
	Pinned      bool
	Ip          string
}

type CreatePostRow struct {
	ID  int32
	Uid uuid.UUID
}

func (q *Queries) CreatePost(ctx context.Context, arg CreatePostParams) (CreatePostRow, error) {
	row := q.db.QueryRow(ctx, createPost,
		arg.Uid,
		arg.Author,
		arg.Text,
		arg.Images,
		arg.Attachments,
		arg.Visibility,
		arg.Pinned,
		arg.Ip,
	)
	var i CreatePostRow
	err := row.Scan(&i.ID, &i.Uid)
	return i, err
}

const deletePostTagsNotInNames = `-- name: DeletePostTagsNotInNames :exec
DELETE FROM post_tags pt
WHERE pt.post_id = $1
  AND NOT EXISTS (
    SELECT 1
    FROM tags t
    JOIN (
      SELECT DISTINCT unnest($2::text[]) AS name
    ) i ON i.name = t.name
    WHERE t.id = pt.tag_id
  )
`

type DeletePostTagsNotInNamesParams struct {
	PostID int32
	Tags   []string
}

func (q *Queries) DeletePostTagsNotInNames(ctx context.Context, arg DeletePostTagsNotInNamesParams) error {
	_, err := q.db.Exec(ctx, deletePostTagsNotInNames, arg.PostID, arg.Tags)
	return err
}

const getPostByUid = `-- name: GetPostByUid :one
SELECT p.uid,
  p.author,
  u.uid AS author_uid,
  u.nickname AS author_nickname,
  u.avatar_url AS author_avatar_url,
  p.text,
  p.images,
  p.attachments,
  p.comment_count,
  p.collection_count,
  p.like_count,
  p.pinned,
  p.visibility,
  p.latest_replied_on,
  p.ip,
  p.status,
  p.created_at,
  p.updated_at,
  (pl.user_uid IS NOT NULL)::boolean AS liked,
  (pc.user_uid IS NOT NULL)::boolean AS collected,
  (uf.follower_uid IS NOT NULL)::boolean AS following,
  COALESCE(
    (
      SELECT array_agg(
          t.name
          ORDER BY t.name
        )
      FROM post_tags pt
        JOIN tags t ON t.id = pt.tag_id
      WHERE pt.post_id = p.id
    ),
    '{}'::text []
  )::text [] AS tag_names
FROM posts p
  JOIN users u ON u.uid = p.author
  AND u.status = 'NORMAL'::user_status
  LEFT JOIN post_likes pl ON pl.post_uid = p.uid
  AND pl.user_uid = $1::uuid
  LEFT JOIN post_collections pc ON pc.post_uid = p.uid
  AND pc.user_uid = $1::uuid
  LEFT JOIN user_follows uf ON uf.follower_uid = $1::uuid
  AND uf.followee_uid = p.author
WHERE p.uid = $2
  AND p.status = 'NORMAL'::post_status
LIMIT 1
`

type GetPostByUidParams struct {
	Viewer uuid.NullUUID
	Uid    uuid.UUID
}

type GetPostByUidRow struct {
	Uid             uuid.UUID
	Author          uuid.UUID
	AuthorUid       uuid.UUID
	AuthorNickname  string
	AuthorAvatarUrl string
	Text            string
	Images          []string
	Attachments     []string
	CommentCount    int32
	CollectionCount int32
	LikeCount       int32
	Pinned          bool
	Visibility      PostVisibility
	LatestRepliedOn pgtype.Timestamptz
	Ip              string
	Status          PostStatus
	CreatedAt       pgtype.Timestamptz
	UpdatedAt       pgtype.Timestamptz
	Liked           bool
	Collected       bool
	Following       bool
	TagNames        []string
}

func (q *Queries) GetPostByUid(ctx context.Context, arg GetPostByUidParams) (GetPostByUidRow, error) {
	row := q.db.QueryRow(ctx, getPostByUid, arg.Viewer, arg.Uid)
	var i GetPostByUidRow
	err := row.Scan(
		&i.Uid,
		&i.Author,
		&i.AuthorUid,
		&i.AuthorNickname,
		&i.AuthorAvatarUrl,
		&i.Text,
		&i.Images,
		&i.Attachments,
		&i.CommentCount,
		&i.CollectionCount,
		&i.LikeCount,
		&i.Pinned,
		&i.Visibility,
		&i.LatestRepliedOn,
		&i.Ip,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Liked,
		&i.Collected,
		&i.Following,
		&i.TagNames,
	)
	return i, err
}

const getPostSearchExtrasByUids = `-- name: GetPostSearchExtrasByUids :many
WITH input AS (
  SELECT DISTINCT ON (x.uid) x.uid,
    x.ord
  FROM unnest($2::uuid []) WITH ORDINALITY AS x(uid, ord)
  ORDER BY x.uid,
    x.ord
)
SELECT p.uid,
  u.nickname AS author_nickname,
  u.avatar_url AS author_avatar_url,
  (uf.follower_uid IS NOT NULL)::boolean AS is_following,
  (pl.user_uid IS NOT NULL)::boolean AS liked,
  (pc.user_uid IS NOT NULL)::boolean AS collected
FROM input i
  JOIN posts p ON p.uid = i.uid
  JOIN users u ON u.uid = p.author
  AND u.status = 'NORMAL'::user_status
  LEFT JOIN post_likes pl ON pl.post_uid = p.uid
  AND pl.user_uid = $1::uuid
  LEFT JOIN post_collections pc ON pc.post_uid = p.uid
  AND pc.user_uid = $1::uuid
  LEFT JOIN user_follows uf ON uf.follower_uid = $1::uuid
  AND uf.followee_uid = p.author
WHERE p.status = 'NORMAL'::post_status
  AND (
    p.visibility = 'PUBLIC'::post_visibility
    OR p.author = $1::uuid
  )
ORDER BY i.ord
`

type GetPostSearchExtrasByUidsParams struct {
	Viewer uuid.NullUUID
	Uids   []uuid.UUID
}

type GetPostSearchExtrasByUidsRow struct {
	Uid             uuid.UUID
	AuthorNickname  string
	AuthorAvatarUrl string
	IsFollowing     bool
	Liked           bool
	Collected       bool
}

func (q *Queries) GetPostSearchExtrasByUids(ctx context.Context, arg GetPostSearchExtrasByUidsParams) ([]GetPostSearchExtrasByUidsRow, error) {
	rows, err := q.db.Query(ctx, getPostSearchExtrasByUids, arg.Viewer, arg.Uids)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetPostSearchExtrasByUidsRow
	for rows.Next() {
		var i GetPostSearchExtrasByUidsRow
		if err := rows.Scan(
			&i.Uid,
			&i.AuthorNickname,
			&i.AuthorAvatarUrl,
			&i.IsFollowing,
			&i.Liked,
			&i.Collected,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertPostTagsByNames = `-- name: InsertPostTagsByNames :exec
WITH input AS (
  SELECT DISTINCT unnest($2::text[]) AS name
)
INSERT INTO post_tags (post_id, tag_id)
SELECT $1, t.id
FROM tags t
JOIN input i ON i.name = t.name
ON CONFLICT (post_id, tag_id) DO NOTHING
`

type InsertPostTagsByNamesParams struct {
	PostID int32
	Tags   []string
}

func (q *Queries) InsertPostTagsByNames(ctx context.Context, arg InsertPostTagsByNamesParams) error {
	_, err := q.db.Exec(ctx, insertPostTagsByNames, arg.PostID, arg.Tags)
	return err
}

const insertTagsIfNotExists = `-- name: InsertTagsIfNotExists :exec
WITH input AS (
  SELECT DISTINCT unnest($1::text[]) AS name
)
INSERT INTO tags (name)
SELECT name
FROM input
ON CONFLICT (name) DO NOTHING
`

func (q *Queries) InsertTagsIfNotExists(ctx context.Context, tags []string) error {
	_, err := q.db.Exec(ctx, insertTagsIfNotExists, tags)
	return err
}

const updatePostByUidAndAuthor = `-- name: UpdatePostByUidAndAuthor :one
UPDATE posts
SET text = COALESCE($1, text),
  images = COALESCE($2::text [], images),
  attachments = COALESCE($3::text [], attachments),
  visibility = COALESCE(
    $4::post_visibility,
    visibility
  ),
  pinned = COALESCE($5::boolean, pinned),
  updated_at = now()
WHERE uid = $6
  AND author = $7
  AND status = 'NORMAL'::post_status
RETURNING id
`

type UpdatePostByUidAndAuthorParams struct {
	Text        pgtype.Text
	Images      []string
	Attachments []string
	Visibility  NullPostVisibility
	Pinned      pgtype.Bool
	Uid         uuid.UUID
	Author      uuid.UUID
}

func (q *Queries) UpdatePostByUidAndAuthor(ctx context.Context, arg UpdatePostByUidAndAuthorParams) (int32, error) {
	row := q.db.QueryRow(ctx, updatePostByUidAndAuthor,
		arg.Text,
		arg.Images,
		arg.Attachments,
		arg.Visibility,
		arg.Pinned,
		arg.Uid,
		arg.Author,
	)
	var id int32
	err := row.Scan(&id)
	return id, err
}
