// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: refresh_tokens.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const deleteRefreshTokenByUid = `-- name: DeleteRefreshTokenByUid :execrows
DELETE FROM refresh_tokens
WHERE uid = $1
`

func (q *Queries) DeleteRefreshTokenByUid(ctx context.Context, uid uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteRefreshTokenByUid, uid)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const rotateRefreshToken = `-- name: RotateRefreshToken :one
UPDATE refresh_tokens
SET token = $1,
  expires_at = $2
WHERE token = $3
  AND expires_at > now()
RETURNING uid
`

type RotateRefreshTokenParams struct {
	NewToken  string
	ExpiresAt pgtype.Timestamptz
	OldToken  string
}

func (q *Queries) RotateRefreshToken(ctx context.Context, arg RotateRefreshTokenParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, rotateRefreshToken, arg.NewToken, arg.ExpiresAt, arg.OldToken)
	var uid uuid.UUID
	err := row.Scan(&uid)
	return uid, err
}

const upsertRefreshToken = `-- name: UpsertRefreshToken :exec
INSERT INTO refresh_tokens (uid, token, expires_at)
VALUES ($1, $2, $3) 
ON CONFLICT (uid) DO UPDATE
SET token = $2,
  expires_at = $3
`

type UpsertRefreshTokenParams struct {
	Uid       uuid.UUID
	Token     string
	ExpiresAt pgtype.Timestamptz
}

func (q *Queries) UpsertRefreshToken(ctx context.Context, arg UpsertRefreshTokenParams) error {
	_, err := q.db.Exec(ctx, upsertRefreshToken, arg.Uid, arg.Token, arg.ExpiresAt)
	return err
}
