// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: report.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const createReport = `-- name: CreateReport :one
INSERT INTO reports (
  uid,
  reporter_uid,
  report_target_type,
  target_uid,
  content
)
VALUES (
  $1,
  $2,
  $3,
  $4,
  $5
)
RETURNING
  id,
  uid,
  reporter_uid,
  report_target_type,
  target_uid,
  content,
  status,
  created_at,
  updated_at
`

type CreateReportParams struct {
	Uid              uuid.UUID
	ReporterUid      uuid.UUID
	ReportTargetType ReportTargetType
	TargetUid        uuid.UUID
	Content          string
}

func (q *Queries) CreateReport(ctx context.Context, arg CreateReportParams) (Report, error) {
	row := q.db.QueryRow(ctx, createReport,
		arg.Uid,
		arg.ReporterUid,
		arg.ReportTargetType,
		arg.TargetUid,
		arg.Content,
	)
	var i Report
	err := row.Scan(
		&i.ID,
		&i.Uid,
		&i.ReporterUid,
		&i.ReportTargetType,
		&i.TargetUid,
		&i.Content,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
