// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: report.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const createReport = `-- name: CreateReport :exec
INSERT INTO reports (
    uid,
    reporter_uid,
    report_target_type,
    target_uid,
    content
  )
VALUES ($1, $2, $3, $4, $5) ON CONFLICT (reporter_uid, report_target_type, target_uid)
WHERE status = 'NORMAL'::report_status DO NOTHING
`

type CreateReportParams struct {
	Uid              uuid.UUID
	ReporterUid      uuid.UUID
	ReportTargetType ReportTargetType
	TargetUid        uuid.UUID
	Content          string
}

func (q *Queries) CreateReport(ctx context.Context, arg CreateReportParams) error {
	_, err := q.db.ExecContext(ctx, createReport,
		arg.Uid,
		arg.ReporterUid,
		arg.ReportTargetType,
		arg.TargetUid,
		arg.Content,
	)
	return err
}
