// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: search.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const searchTags = `-- name: SearchTags :many
SELECT t.id,
  t.name,
  COALESCE(pgroonga_score(t.tableoid, t.ctid), 0::float8)::float8 AS score
FROM tags t
WHERE t.name &@~ $1
ORDER BY score DESC,
  t.name ASC
LIMIT 20
`

type SearchTagsRow struct {
	ID    int32
	Name  string
	Score float64
}

func (q *Queries) SearchTags(ctx context.Context, query string) ([]SearchTagsRow, error) {
	rows, err := q.db.Query(ctx, searchTags, query)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SearchTagsRow
	for rows.Next() {
		var i SearchTagsRow
		if err := rows.Scan(&i.ID, &i.Name, &i.Score); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchUsers = `-- name: SearchUsers :many
SELECT u.uid,
  u.role,
  u.nickname,
  u.avatar_url,
  u.followers_count,
  u.following_count,
  u.description,
  u.status,
  u.created_at,
  COALESCE(pgroonga_score(u.tableoid, u.ctid), 0::float8)::float8 AS score
FROM users u
WHERE u.status = 'NORMAL'::user_status
  AND ARRAY [u.nickname, u.description] &@~ $1
ORDER BY score DESC,
  u.followers_count DESC,
  u.created_at DESC,
  u.uid DESC
LIMIT 20
`

type SearchUsersRow struct {
	Uid            uuid.UUID
	Role           UserRole
	Nickname       string
	AvatarUrl      string
	FollowersCount int32
	FollowingCount int32
	Description    string
	Status         UserStatus
	CreatedAt      pgtype.Timestamptz
	Score          float64
}

func (q *Queries) SearchUsers(ctx context.Context, query string) ([]SearchUsersRow, error) {
	rows, err := q.db.Query(ctx, searchUsers, query)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SearchUsersRow
	for rows.Next() {
		var i SearchUsersRow
		if err := rows.Scan(
			&i.Uid,
			&i.Role,
			&i.Nickname,
			&i.AvatarUrl,
			&i.FollowersCount,
			&i.FollowingCount,
			&i.Description,
			&i.Status,
			&i.CreatedAt,
			&i.Score,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const suggestTagsByPrefix = `-- name: SuggestTagsByPrefix :many
SELECT t.id,
  t.name
FROM tags t
WHERE t.name &^ $1
ORDER BY char_length(t.name) ASC,
  t.name ASC
LIMIT 10
`

func (q *Queries) SuggestTagsByPrefix(ctx context.Context, prefix string) ([]Tag, error) {
	rows, err := q.db.Query(ctx, suggestTagsByPrefix, prefix)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Tag
	for rows.Next() {
		var i Tag
		if err := rows.Scan(&i.ID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const suggestUsersByNicknamePrefix = `-- name: SuggestUsersByNicknamePrefix :many
SELECT u.uid,
  u.role,
  u.nickname,
  u.avatar_url,
  u.followers_count,
  u.following_count,
  u.description
FROM users u
WHERE u.status = 'NORMAL'::user_status
  AND u.nickname &^ $1
ORDER BY u.followers_count DESC,
  u.created_at DESC,
  u.uid DESC
LIMIT 10
`

type SuggestUsersByNicknamePrefixRow struct {
	Uid            uuid.UUID
	Role           UserRole
	Nickname       string
	AvatarUrl      string
	FollowersCount int32
	FollowingCount int32
	Description    string
}

func (q *Queries) SuggestUsersByNicknamePrefix(ctx context.Context, prefix string) ([]SuggestUsersByNicknamePrefixRow, error) {
	rows, err := q.db.Query(ctx, suggestUsersByNicknamePrefix, prefix)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SuggestUsersByNicknamePrefixRow
	for rows.Next() {
		var i SuggestUsersByNicknamePrefixRow
		if err := rows.Scan(
			&i.Uid,
			&i.Role,
			&i.Nickname,
			&i.AvatarUrl,
			&i.FollowersCount,
			&i.FollowingCount,
			&i.Description,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
