// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: search.sql

package db

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
	"github.com/lib/pq"
)

const searchPosts = `-- name: SearchPosts :many
WITH scored_posts AS (
  SELECT p.id,
    p.uid,
    p.author,
    p.text,
    p.images,
    p.attachments,
    p.comment_count,
    p.collection_count,
    p.like_count,
    p.pinned,
    p.visibility,
    p.latest_replied_on,
    p.ip,
    p.status,
    p.created_at,
    p.updated_at,
    COALESCE(pgroonga_score(p.tableoid, p.ctid), 0::float8)::float8 AS score
  FROM posts p
  WHERE p.status = 'NORMAL'::post_status
    AND p.text &@~ $2
    AND (
      p.visibility = 'PUBLIC'::post_visibility
      OR p.author = $1::uuid
    )
    AND (
      $3::text IS NULL
      OR EXISTS (
        SELECT 1
        FROM post_tags pt
          JOIN tags t ON t.id = pt.tag_id
        WHERE pt.post_id = p.id
          AND t.name = $3::text
      )
    )
),
matched_posts AS (
  SELECT id, uid, author, text, images, attachments, comment_count, collection_count, like_count, pinned, visibility, latest_replied_on, ip, status, created_at, updated_at, score
  FROM scored_posts sp
  WHERE (
      (
        $4::float8 IS NULL
        AND $5::timestamptz IS NULL
        AND $6::uuid IS NULL
      )
      OR (sp.score, sp.created_at, sp.uid) < (
        $4::float8,
        $5::timestamptz,
        $6::uuid
      )
    )
)
SELECT mp.uid,
  mp.author,
  u.uid AS author_uid,
  u.nickname AS author_nickname,
  u.avatar_url AS author_avatar_url,
  mp.text,
  mp.images,
  mp.attachments,
  mp.comment_count,
  mp.collection_count,
  mp.like_count,
  mp.pinned,
  mp.visibility,
  mp.latest_replied_on,
  mp.ip,
  mp.status,
  mp.created_at,
  mp.updated_at,
  mp.score,
  (pl.user_uid IS NOT NULL)::boolean AS liked,
  (pc.user_uid IS NOT NULL)::boolean AS collected,
  (uf.follower_uid IS NOT NULL)::boolean AS following,
  COALESCE(
    (
      SELECT array_agg(
          t.name
          ORDER BY t.name
        )
      FROM post_tags pt
        JOIN tags t ON t.id = pt.tag_id
      WHERE pt.post_id = mp.id
    ),
    '{}'::text []
  )::text [] AS tag_names
FROM matched_posts mp
  JOIN users u ON u.uid = mp.author
  AND u.status = 'NORMAL'::user_status
  LEFT JOIN post_likes pl ON pl.post_uid = mp.uid
  AND pl.user_uid = $1::uuid
  LEFT JOIN post_collections pc ON pc.post_uid = mp.uid
  AND pc.user_uid = $1::uuid
  LEFT JOIN user_follows uf ON uf.follower_uid = $1::uuid
  AND uf.followee_uid = mp.author
ORDER BY mp.score DESC,
  mp.created_at DESC,
  mp.uid DESC
LIMIT 20
`

type SearchPostsParams struct {
	Viewer          uuid.NullUUID
	Query           string
	Tag             sql.NullString
	CursorScore     sql.NullFloat64
	CursorCreatedAt sql.NullTime
	CursorID        uuid.NullUUID
}

type SearchPostsRow struct {
	Uid             uuid.UUID
	Author          uuid.UUID
	AuthorUid       uuid.UUID
	AuthorNickname  string
	AuthorAvatarUrl string
	Text            string
	Images          []string
	Attachments     []string
	CommentCount    int32
	CollectionCount int32
	LikeCount       int32
	Pinned          bool
	Visibility      PostVisibility
	LatestRepliedOn time.Time
	Ip              string
	Status          PostStatus
	CreatedAt       time.Time
	UpdatedAt       time.Time
	Score           float64
	Liked           bool
	Collected       bool
	Following       bool
	TagNames        []string
}

func (q *Queries) SearchPosts(ctx context.Context, arg SearchPostsParams) ([]SearchPostsRow, error) {
	rows, err := q.db.QueryContext(ctx, searchPosts,
		arg.Viewer,
		arg.Query,
		arg.Tag,
		arg.CursorScore,
		arg.CursorCreatedAt,
		arg.CursorID,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SearchPostsRow
	for rows.Next() {
		var i SearchPostsRow
		if err := rows.Scan(
			&i.Uid,
			&i.Author,
			&i.AuthorUid,
			&i.AuthorNickname,
			&i.AuthorAvatarUrl,
			&i.Text,
			pq.Array(&i.Images),
			pq.Array(&i.Attachments),
			&i.CommentCount,
			&i.CollectionCount,
			&i.LikeCount,
			&i.Pinned,
			&i.Visibility,
			&i.LatestRepliedOn,
			&i.Ip,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Score,
			&i.Liked,
			&i.Collected,
			&i.Following,
			pq.Array(&i.TagNames),
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchTags = `-- name: SearchTags :many
SELECT t.id,
  t.name,
  COALESCE(pgroonga_score(t.tableoid, t.ctid), 0::float8)::float8 AS score
FROM tags t
WHERE t.name &@~ $1
ORDER BY score DESC,
  t.name ASC
LIMIT 20
`

type SearchTagsRow struct {
	ID    int32
	Name  string
	Score float64
}

func (q *Queries) SearchTags(ctx context.Context, query string) ([]SearchTagsRow, error) {
	rows, err := q.db.QueryContext(ctx, searchTags, query)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SearchTagsRow
	for rows.Next() {
		var i SearchTagsRow
		if err := rows.Scan(&i.ID, &i.Name, &i.Score); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchUsers = `-- name: SearchUsers :many
SELECT u.uid,
  u.role,
  u.nickname,
  u.avatar_url,
  u.followers_count,
  u.following_count,
  u.description,
  u.status,
  u.created_at,
  COALESCE(pgroonga_score(u.tableoid, u.ctid), 0::float8)::float8 AS score
FROM users u
WHERE u.status = 'NORMAL'::user_status
  AND ARRAY [u.nickname, u.description] &@~ $1
ORDER BY score DESC,
  u.followers_count DESC,
  u.created_at DESC,
  u.uid DESC
LIMIT 20
`

type SearchUsersRow struct {
	Uid            uuid.UUID
	Role           UserRole
	Nickname       string
	AvatarUrl      string
	FollowersCount int32
	FollowingCount int32
	Description    string
	Status         UserStatus
	CreatedAt      time.Time
	Score          float64
}

func (q *Queries) SearchUsers(ctx context.Context, query string) ([]SearchUsersRow, error) {
	rows, err := q.db.QueryContext(ctx, searchUsers, query)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SearchUsersRow
	for rows.Next() {
		var i SearchUsersRow
		if err := rows.Scan(
			&i.Uid,
			&i.Role,
			&i.Nickname,
			&i.AvatarUrl,
			&i.FollowersCount,
			&i.FollowingCount,
			&i.Description,
			&i.Status,
			&i.CreatedAt,
			&i.Score,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const suggestTagsByPrefix = `-- name: SuggestTagsByPrefix :many
SELECT t.id,
  t.name
FROM tags t
WHERE t.name &^ $1
ORDER BY char_length(t.name) ASC,
  t.name ASC
LIMIT 10
`

func (q *Queries) SuggestTagsByPrefix(ctx context.Context, prefix string) ([]Tag, error) {
	rows, err := q.db.QueryContext(ctx, suggestTagsByPrefix, prefix)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Tag
	for rows.Next() {
		var i Tag
		if err := rows.Scan(&i.ID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const suggestUsersByNicknamePrefix = `-- name: SuggestUsersByNicknamePrefix :many
SELECT u.uid,
  u.role,
  u.nickname,
  u.avatar_url,
  u.followers_count,
  u.following_count,
  u.description
FROM users u
WHERE u.status = 'NORMAL'::user_status
  AND u.nickname &^ $1
ORDER BY u.followers_count DESC,
  u.created_at DESC,
  u.uid DESC
LIMIT 10
`

type SuggestUsersByNicknamePrefixRow struct {
	Uid            uuid.UUID
	Role           UserRole
	Nickname       string
	AvatarUrl      string
	FollowersCount int32
	FollowingCount int32
	Description    string
}

func (q *Queries) SuggestUsersByNicknamePrefix(ctx context.Context, prefix string) ([]SuggestUsersByNicknamePrefixRow, error) {
	rows, err := q.db.QueryContext(ctx, suggestUsersByNicknamePrefix, prefix)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SuggestUsersByNicknamePrefixRow
	for rows.Next() {
		var i SuggestUsersByNicknamePrefixRow
		if err := rows.Scan(
			&i.Uid,
			&i.Role,
			&i.Nickname,
			&i.AvatarUrl,
			&i.FollowersCount,
			&i.FollowingCount,
			&i.Description,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
