// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: user.sql

package db

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const createUser = `-- name: CreateUser :exec
INSERT INTO users (
    uid,
    username,
    nickname,
    password_hash,
    email,
    avatar_url
  )
VALUES ($1, $2, $3, $4, $5, $6)
`

type CreateUserParams struct {
	Uid          uuid.UUID
	Username     string
	Nickname     string
	PasswordHash string
	Email        string
	AvatarUrl    string
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) error {
	_, err := q.db.ExecContext(ctx, createUser,
		arg.Uid,
		arg.Username,
		arg.Nickname,
		arg.PasswordHash,
		arg.Email,
		arg.AvatarUrl,
	)
	return err
}

const getUserByUid = `-- name: GetUserByUid :one
SELECT uid,
  username,
  role,
  email,
  nickname,
  avatar_url,
  followers_count,
  following_count,
  description,
  status,
  created_at
FROM users
WHERE uid = $1
  AND status = 'NORMAL'::user_status
`

type GetUserByUidRow struct {
	Uid            uuid.UUID
	Username       string
	Role           UserRole
	Email          string
	Nickname       string
	AvatarUrl      string
	FollowersCount int32
	FollowingCount int32
	Description    string
	Status         UserStatus
	CreatedAt      time.Time
}

func (q *Queries) GetUserByUid(ctx context.Context, uid uuid.UUID) (GetUserByUidRow, error) {
	row := q.db.QueryRowContext(ctx, getUserByUid, uid)
	var i GetUserByUidRow
	err := row.Scan(
		&i.Uid,
		&i.Username,
		&i.Role,
		&i.Email,
		&i.Nickname,
		&i.AvatarUrl,
		&i.FollowersCount,
		&i.FollowingCount,
		&i.Description,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const getUserByUsername = `-- name: GetUserByUsername :one
SELECT uid,
  username,
  role,
  email,
  nickname,
  avatar_url,
  followers_count,
  following_count,
  description,
  status,
  created_at,
  password_hash
FROM users
WHERE username = $1
  AND status = 'NORMAL'::user_status
`

type GetUserByUsernameRow struct {
	Uid            uuid.UUID
	Username       string
	Role           UserRole
	Email          string
	Nickname       string
	AvatarUrl      string
	FollowersCount int32
	FollowingCount int32
	Description    string
	Status         UserStatus
	CreatedAt      time.Time
	PasswordHash   string
}

func (q *Queries) GetUserByUsername(ctx context.Context, username string) (GetUserByUsernameRow, error) {
	row := q.db.QueryRowContext(ctx, getUserByUsername, username)
	var i GetUserByUsernameRow
	err := row.Scan(
		&i.Uid,
		&i.Username,
		&i.Role,
		&i.Email,
		&i.Nickname,
		&i.AvatarUrl,
		&i.FollowersCount,
		&i.FollowingCount,
		&i.Description,
		&i.Status,
		&i.CreatedAt,
		&i.PasswordHash,
	)
	return i, err
}

const getUserPasswordHashByUid = `-- name: GetUserPasswordHashByUid :one
SELECT password_hash
FROM users
WHERE uid = $1
  AND status = 'NORMAL'::user_status
`

func (q *Queries) GetUserPasswordHashByUid(ctx context.Context, uid uuid.UUID) (string, error) {
	row := q.db.QueryRowContext(ctx, getUserPasswordHashByUid, uid)
	var password_hash string
	err := row.Scan(&password_hash)
	return password_hash, err
}

const updateUser = `-- name: UpdateUser :exec
UPDATE users
SET username = COALESCE($2, username),
  email = COALESCE($3, email),
  nickname = COALESCE($4, nickname),
  avatar_url = COALESCE($5, avatar_url),
  updated_at = now()
WHERE uid = $1
  AND status = 'NORMAL'::user_status
`

type UpdateUserParams struct {
	Uid       uuid.UUID
	Username  sql.NullString
	Email     sql.NullString
	Nickname  sql.NullString
	AvatarUrl sql.NullString
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) error {
	_, err := q.db.ExecContext(ctx, updateUser,
		arg.Uid,
		arg.Username,
		arg.Email,
		arg.Nickname,
		arg.AvatarUrl,
	)
	return err
}

const updateUserPasswordByUid = `-- name: UpdateUserPasswordByUid :execrows
UPDATE users
SET password_hash = $2,
  updated_at = now()
WHERE uid = $1
  AND status = 'NORMAL'::user_status
`

type UpdateUserPasswordByUidParams struct {
	Uid          uuid.UUID
	PasswordHash string
}

func (q *Queries) UpdateUserPasswordByUid(ctx context.Context, arg UpdateUserPasswordByUidParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, updateUserPasswordByUid, arg.Uid, arg.PasswordHash)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
