-- users table
CREATE TYPE user_role AS ENUM ('HOST', 'ADMIN', 'USER');
CREATE TYPE user_status AS ENUM ('NORMAL', 'ARCHIVED');
CREATE TABLE users (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uid uuid NOT NULL UNIQUE,
    username text NOT NULL UNIQUE,
    role user_role NOT NULL DEFAULT 'USER',
    email text NOT NULL DEFAULT '',
    nickname text NOT NULL UNIQUE,
    password_hash text NOT NULL,
    avatar_url text NOT NULL DEFAULT '',
    followers_count integer NOT NULL DEFAULT 0,
    following_count integer NOT NULL DEFAULT 0,
    description text NOT NULL DEFAULT '',
    status user_status NOT NULL DEFAULT 'NORMAL',
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now()
);

-- user follows
CREATE TABLE user_follows (
    follower_uid uuid NOT NULL,
    followee_uid uuid NOT NULL,
    created_at timestamptz NOT NULL DEFAULT now(),
    PRIMARY KEY (follower_uid, followee_uid)
);

-- refresh_tokens table
CREATE TABLE refresh_tokens (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uid uuid NOT NULL UNIQUE,
    token text NOT NULL UNIQUE,
    expires_at timestamptz NOT NULL,
    created_at timestamptz NOT NULL DEFAULT now()
);

-- posts table
CREATE TYPE post_visibility AS ENUM ('PUBLIC', 'PRIVATE');
CREATE TYPE post_status AS ENUM ('NORMAL', 'ARCHIVED');
CREATE TABLE posts (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uid uuid NOT NULL UNIQUE,
    author_uid uuid NOT NULL,
    text text NOT NULL,
    images text [] NOT NULL DEFAULT ARRAY []::text [],
    attachments text [] NOT NULL DEFAULT ARRAY []::text [],
    tags text[] NOT NULL DEFAULT ARRAY []::text[],
    comment_count integer NOT NULL DEFAULT 0,
    collection_count integer NOT NULL DEFAULT 0,
    like_count integer NOT NULL DEFAULT 0,
    pinned boolean NOT NULL DEFAULT false,
    visibility post_visibility NOT NULL DEFAULT 'PUBLIC',
    latest_replied_on timestamptz NOT NULL DEFAULT now(),
    ip text NOT NULL DEFAULT '',
    status post_status NOT NULL DEFAULT 'NORMAL',
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now()
);

-- post_likes table
CREATE TABLE post_likes (
    post_uid uuid NOT NULL,
    user_uid uuid NOT NULL,
    created_at timestamptz NOT NULL DEFAULT now(),
    PRIMARY KEY (post_uid, user_uid)
);

-- post_collections table
CREATE TABLE post_collections (
    post_uid uuid NOT NULL,
    user_uid uuid NOT NULL,
    created_at timestamptz NOT NULL DEFAULT now(),
    PRIMARY KEY (post_uid, user_uid)
);

-- files table
CREATE TYPE file_status AS ENUM ('NORMAL', 'ARCHIVED');
CREATE TABLE files (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    url text NOT NULL UNIQUE,
    name text NOT NULL,
    content_type text NOT NULL,
    size bigint NOT NULL,
    checksum text NOT NULL,
    uploader uuid NOT NULL,
    status file_status NOT NULL DEFAULT 'NORMAL',
    created_at timestamptz NOT NULL DEFAULT now()
);

-- post comments table
CREATE TYPE comment_status AS ENUM ('NORMAL', 'ARCHIVED');
CREATE TABLE post_comments (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  uid uuid NOT NULL UNIQUE,
  post_uid uuid NOT NULL,
  author_uid uuid NOT NULL,
  root_uid uuid NOT NULL,
  parent_uid uuid,
  reply_to_author_uid uuid,
  content text NOT NULL,
  images text [] NOT NULL DEFAULT ARRAY []::text [],
  reply_count integer NOT NULL DEFAULT 0,
  like_count integer NOT NULL DEFAULT 0,
  ip text NOT NULL DEFAULT '',
  status comment_status NOT NULL DEFAULT 'NORMAL',
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

-- comment_likes table
CREATE TABLE comment_likes (
  comment_uid uuid NOT NULL,
  user_uid uuid NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  PRIMARY KEY (comment_uid, user_uid)
);

-- inbox tables
CREATE TYPE inbox_message_status AS ENUM ('NORMAL', 'ARCHIVED');
CREATE TABLE inbox_comment_messages (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  uid uuid NOT NULL UNIQUE,
  receiver_uid uuid NOT NULL,
  actor_uid uuid NOT NULL,
  comment_uid uuid NOT NULL,
  post_uid uuid NOT NULL,
  parent_comment_uid uuid,
  read_at timestamptz,
  created_at timestamptz NOT NULL DEFAULT now(),
  status inbox_message_status NOT NULL DEFAULT 'NORMAL'
);

CREATE TABLE inbox_follow_messages (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  uid uuid NOT NULL UNIQUE,
  receiver_uid uuid NOT NULL,
  actor_uid uuid NOT NULL,
  read_at timestamptz,
  created_at timestamptz NOT NULL DEFAULT now(),
  status inbox_message_status NOT NULL DEFAULT 'NORMAL'
);

-- reports table
CREATE TYPE report_target_type AS ENUM ('POST', 'COMMENT', 'USER');
CREATE TYPE report_status AS ENUM ('NORMAL', 'ARCHIVED');
CREATE TABLE reports (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uid uuid NOT NULL UNIQUE,
    reporter_uid uuid NOT NULL,
    report_target_type report_target_type NOT NULL,
    target_uid uuid NOT NULL,
    content text NOT NULL DEFAULT '',
    status report_status NOT NULL DEFAULT 'NORMAL',
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now()
);