-- inbox messages table
CREATE TYPE message_status AS ENUM ('NORMAL', 'ARCHIVED');
CREATE TYPE message_type AS ENUM ('COMMENT', 'FOLLOW');
CREATE TABLE inbox_messages (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uid uuid NOT NULL UNIQUE,
    receiver_uid uuid NOT NULL,
    type message_type NOT NULL,
    is_read boolean NOT NULL DEFAULT false,
    actor_uid uuid NOT NULL,
    created_at timestamptz NOT NULL DEFAULT now(),
    status message_status NOT NULL DEFAULT 'NORMAL',
    -- comment
    comment_uid uuid,
    post_uid uuid,
    parent_uid uuid
);
CREATE INDEX idx_inbox_messages_receiver_type_keyset_normal ON inbox_messages (receiver_uid, type, created_at DESC, uid DESC)
WHERE status = 'NORMAL'::message_status;
CREATE INDEX idx_inbox_messages_receiver_unread_normal ON inbox_messages (receiver_uid)
WHERE status = 'NORMAL'::message_status
    AND is_read = false;
CREATE INDEX idx_inbox_messages_follow_exists_normal ON inbox_messages (receiver_uid, actor_uid)
WHERE status = 'NORMAL'::message_status
    AND type = 'FOLLOW'::message_type;
