-- reports table
CREATE TYPE report_target_type AS ENUM ('POST', 'COMMENT', 'USER');
CREATE TYPE report_status AS ENUM ('NORMAL', 'ARCHIVED');
CREATE TABLE reports (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uid uuid NOT NULL UNIQUE DEFAULT gen_random_uuid(),
    reporter_uid uuid NOT NULL REFERENCES users(uid),
    report_target_type report_target_type NOT NULL,
    target_uid uuid NOT NULL,
    content text NOT NULL DEFAULT '',
    status report_status NOT NULL DEFAULT 'NORMAL',
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now()
);
CREATE UNIQUE INDEX uq_reports_open_unique ON reports (reporter_uid, report_target_type, target_uid)
WHERE status = 'NORMAL'::report_status;
