// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: config.proto

package api

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type FrontendConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SiteName      string                 `protobuf:"bytes,1,opt,name=site_name,json=siteName,proto3" json:"site_name,omitempty"`
	SiteIconUrl   string                 `protobuf:"bytes,2,opt,name=site_icon_url,json=siteIconUrl,proto3" json:"site_icon_url,omitempty"`
	SiteLogoUrl   string                 `protobuf:"bytes,3,opt,name=site_logo_url,json=siteLogoUrl,proto3" json:"site_logo_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FrontendConfig) Reset() {
	*x = FrontendConfig{}
	mi := &file_config_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FrontendConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FrontendConfig) ProtoMessage() {}

func (x *FrontendConfig) ProtoReflect() protoreflect.Message {
	mi := &file_config_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FrontendConfig.ProtoReflect.Descriptor instead.
func (*FrontendConfig) Descriptor() ([]byte, []int) {
	return file_config_proto_rawDescGZIP(), []int{0}
}

func (x *FrontendConfig) GetSiteName() string {
	if x != nil {
		return x.SiteName
	}
	return ""
}

func (x *FrontendConfig) GetSiteIconUrl() string {
	if x != nil {
		return x.SiteIconUrl
	}
	return ""
}

func (x *FrontendConfig) GetSiteLogoUrl() string {
	if x != nil {
		return x.SiteLogoUrl
	}
	return ""
}

type GetFrontendConfigRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetFrontendConfigRequest) Reset() {
	*x = GetFrontendConfigRequest{}
	mi := &file_config_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetFrontendConfigRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFrontendConfigRequest) ProtoMessage() {}

func (x *GetFrontendConfigRequest) ProtoReflect() protoreflect.Message {
	mi := &file_config_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFrontendConfigRequest.ProtoReflect.Descriptor instead.
func (*GetFrontendConfigRequest) Descriptor() ([]byte, []int) {
	return file_config_proto_rawDescGZIP(), []int{1}
}

type GetFrontendConfigResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Config        *FrontendConfig        `protobuf:"bytes,1,opt,name=config,proto3" json:"config,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetFrontendConfigResponse) Reset() {
	*x = GetFrontendConfigResponse{}
	mi := &file_config_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetFrontendConfigResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFrontendConfigResponse) ProtoMessage() {}

func (x *GetFrontendConfigResponse) ProtoReflect() protoreflect.Message {
	mi := &file_config_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFrontendConfigResponse.ProtoReflect.Descriptor instead.
func (*GetFrontendConfigResponse) Descriptor() ([]byte, []int) {
	return file_config_proto_rawDescGZIP(), []int{2}
}

func (x *GetFrontendConfigResponse) GetConfig() *FrontendConfig {
	if x != nil {
		return x.Config
	}
	return nil
}

type UploadConfig struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	MaxUploadSizeKb int32                  `protobuf:"varint,1,opt,name=max_upload_size_kb,json=maxUploadSizeKb,proto3" json:"max_upload_size_kb,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *UploadConfig) Reset() {
	*x = UploadConfig{}
	mi := &file_config_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadConfig) ProtoMessage() {}

func (x *UploadConfig) ProtoReflect() protoreflect.Message {
	mi := &file_config_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadConfig.ProtoReflect.Descriptor instead.
func (*UploadConfig) Descriptor() ([]byte, []int) {
	return file_config_proto_rawDescGZIP(), []int{3}
}

func (x *UploadConfig) GetMaxUploadSizeKb() int32 {
	if x != nil {
		return x.MaxUploadSizeKb
	}
	return 0
}

type GetUploadConfigRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUploadConfigRequest) Reset() {
	*x = GetUploadConfigRequest{}
	mi := &file_config_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUploadConfigRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUploadConfigRequest) ProtoMessage() {}

func (x *GetUploadConfigRequest) ProtoReflect() protoreflect.Message {
	mi := &file_config_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUploadConfigRequest.ProtoReflect.Descriptor instead.
func (*GetUploadConfigRequest) Descriptor() ([]byte, []int) {
	return file_config_proto_rawDescGZIP(), []int{4}
}

type GetUploadConfigResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Config        *UploadConfig          `protobuf:"bytes,1,opt,name=config,proto3" json:"config,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUploadConfigResponse) Reset() {
	*x = GetUploadConfigResponse{}
	mi := &file_config_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUploadConfigResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUploadConfigResponse) ProtoMessage() {}

func (x *GetUploadConfigResponse) ProtoReflect() protoreflect.Message {
	mi := &file_config_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUploadConfigResponse.ProtoReflect.Descriptor instead.
func (*GetUploadConfigResponse) Descriptor() ([]byte, []int) {
	return file_config_proto_rawDescGZIP(), []int{5}
}

func (x *GetUploadConfigResponse) GetConfig() *UploadConfig {
	if x != nil {
		return x.Config
	}
	return nil
}

var File_config_proto protoreflect.FileDescriptor

const file_config_proto_rawDesc = "" +
	"\n" +
	"\fconfig.proto\x12\x06config\x1a\x1cgoogle/api/annotations.proto\x1a\x1fgoogle/api/field_behavior.proto\"\x7f\n" +
	"\x0eFrontendConfig\x12 \n" +
	"\tsite_name\x18\x01 \x01(\tB\x03\xe0A\x02R\bsiteName\x12'\n" +
	"\rsite_icon_url\x18\x02 \x01(\tB\x03\xe0A\x02R\vsiteIconUrl\x12\"\n" +
	"\rsite_logo_url\x18\x03 \x01(\tR\vsiteLogoUrl\"\x1a\n" +
	"\x18GetFrontendConfigRequest\"P\n" +
	"\x19GetFrontendConfigResponse\x123\n" +
	"\x06config\x18\x01 \x01(\v2\x16.config.FrontendConfigB\x03\xe0A\x02R\x06config\"@\n" +
	"\fUploadConfig\x120\n" +
	"\x12max_upload_size_kb\x18\x01 \x01(\x05B\x03\xe0A\x02R\x0fmaxUploadSizeKb\"\x18\n" +
	"\x16GetUploadConfigRequest\"L\n" +
	"\x17GetUploadConfigResponse\x121\n" +
	"\x06config\x18\x01 \x01(\v2\x14.config.UploadConfigB\x03\xe0A\x02R\x06config2\xff\x01\n" +
	"\rConfigService\x12z\n" +
	"\x11GetFrontendConfig\x12 .config.GetFrontendConfigRequest\x1a!.config.GetFrontendConfigResponse\" \x82\xd3\xe4\x93\x02\x1a\x12\x18/api/v1/configs/frontend\x12r\n" +
	"\x0fGetUploadConfig\x12\x1e.config.GetUploadConfigRequest\x1a\x1f.config.GetUploadConfigResponse\"\x1e\x82\xd3\xe4\x93\x02\x18\x12\x16/api/v1/configs/uploadB\x0fZ\raeibi/api;apib\x06proto3"

var (
	file_config_proto_rawDescOnce sync.Once
	file_config_proto_rawDescData []byte
)

func file_config_proto_rawDescGZIP() []byte {
	file_config_proto_rawDescOnce.Do(func() {
		file_config_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_config_proto_rawDesc), len(file_config_proto_rawDesc)))
	})
	return file_config_proto_rawDescData
}

var file_config_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_config_proto_goTypes = []any{
	(*FrontendConfig)(nil),            // 0: config.FrontendConfig
	(*GetFrontendConfigRequest)(nil),  // 1: config.GetFrontendConfigRequest
	(*GetFrontendConfigResponse)(nil), // 2: config.GetFrontendConfigResponse
	(*UploadConfig)(nil),              // 3: config.UploadConfig
	(*GetUploadConfigRequest)(nil),    // 4: config.GetUploadConfigRequest
	(*GetUploadConfigResponse)(nil),   // 5: config.GetUploadConfigResponse
}
var file_config_proto_depIdxs = []int32{
	0, // 0: config.GetFrontendConfigResponse.config:type_name -> config.FrontendConfig
	3, // 1: config.GetUploadConfigResponse.config:type_name -> config.UploadConfig
	1, // 2: config.ConfigService.GetFrontendConfig:input_type -> config.GetFrontendConfigRequest
	4, // 3: config.ConfigService.GetUploadConfig:input_type -> config.GetUploadConfigRequest
	2, // 4: config.ConfigService.GetFrontendConfig:output_type -> config.GetFrontendConfigResponse
	5, // 5: config.ConfigService.GetUploadConfig:output_type -> config.GetUploadConfigResponse
	4, // [4:6] is the sub-list for method output_type
	2, // [2:4] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_config_proto_init() }
func file_config_proto_init() {
	if File_config_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_config_proto_rawDesc), len(file_config_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_config_proto_goTypes,
		DependencyIndexes: file_config_proto_depIdxs,
		MessageInfos:      file_config_proto_msgTypes,
	}.Build()
	File_config_proto = out.File
	file_config_proto_goTypes = nil
	file_config_proto_depIdxs = nil
}
