// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: message.proto

package api

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type InboxMessageReadFilter int32

const (
	InboxMessageReadFilter_INBOX_MESSAGE_READ_FILTER_UNSPECIFIED InboxMessageReadFilter = 0 // all
	InboxMessageReadFilter_INBOX_MESSAGE_READ_FILTER_UNREAD      InboxMessageReadFilter = 1
	InboxMessageReadFilter_INBOX_MESSAGE_READ_FILTER_READ        InboxMessageReadFilter = 2
)

// Enum value maps for InboxMessageReadFilter.
var (
	InboxMessageReadFilter_name = map[int32]string{
		0: "INBOX_MESSAGE_READ_FILTER_UNSPECIFIED",
		1: "INBOX_MESSAGE_READ_FILTER_UNREAD",
		2: "INBOX_MESSAGE_READ_FILTER_READ",
	}
	InboxMessageReadFilter_value = map[string]int32{
		"INBOX_MESSAGE_READ_FILTER_UNSPECIFIED": 0,
		"INBOX_MESSAGE_READ_FILTER_UNREAD":      1,
		"INBOX_MESSAGE_READ_FILTER_READ":        2,
	}
)

func (x InboxMessageReadFilter) Enum() *InboxMessageReadFilter {
	p := new(InboxMessageReadFilter)
	*p = x
	return p
}

func (x InboxMessageReadFilter) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (InboxMessageReadFilter) Descriptor() protoreflect.EnumDescriptor {
	return file_message_proto_enumTypes[0].Descriptor()
}

func (InboxMessageReadFilter) Type() protoreflect.EnumType {
	return &file_message_proto_enumTypes[0]
}

func (x InboxMessageReadFilter) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use InboxMessageReadFilter.Descriptor instead.
func (InboxMessageReadFilter) EnumDescriptor() ([]byte, []int) {
	return file_message_proto_rawDescGZIP(), []int{0}
}

type InboxMessageActor struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uid           string                 `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`
	Nickname      string                 `protobuf:"bytes,2,opt,name=nickname,proto3" json:"nickname,omitempty"`
	AvatarUrl     string                 `protobuf:"bytes,3,opt,name=avatar_url,json=avatarUrl,proto3" json:"avatar_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InboxMessageActor) Reset() {
	*x = InboxMessageActor{}
	mi := &file_message_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InboxMessageActor) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InboxMessageActor) ProtoMessage() {}

func (x *InboxMessageActor) ProtoReflect() protoreflect.Message {
	mi := &file_message_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InboxMessageActor.ProtoReflect.Descriptor instead.
func (*InboxMessageActor) Descriptor() ([]byte, []int) {
	return file_message_proto_rawDescGZIP(), []int{0}
}

func (x *InboxMessageActor) GetUid() string {
	if x != nil {
		return x.Uid
	}
	return ""
}

func (x *InboxMessageActor) GetNickname() string {
	if x != nil {
		return x.Nickname
	}
	return ""
}

func (x *InboxMessageActor) GetAvatarUrl() string {
	if x != nil {
		return x.AvatarUrl
	}
	return ""
}

type CommentInboxMessage struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Uid            string                 `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`
	IsRead         bool                   `protobuf:"varint,2,opt,name=is_read,json=isRead,proto3" json:"is_read,omitempty"`
	Actor          *InboxMessageActor     `protobuf:"bytes,3,opt,name=actor,proto3" json:"actor,omitempty"`
	CreatedAt      int64                  `protobuf:"varint,4,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	CommentUid     string                 `protobuf:"bytes,5,opt,name=comment_uid,json=commentUid,proto3" json:"comment_uid,omitempty"`
	CommentContent string                 `protobuf:"bytes,6,opt,name=comment_content,json=commentContent,proto3" json:"comment_content,omitempty"`
	PostUid        string                 `protobuf:"bytes,7,opt,name=post_uid,json=postUid,proto3" json:"post_uid,omitempty"`
	ParentUid      string                 `protobuf:"bytes,8,opt,name=parent_uid,json=parentUid,proto3" json:"parent_uid,omitempty"`
	ParentContent  string                 `protobuf:"bytes,9,opt,name=parent_content,json=parentContent,proto3" json:"parent_content,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CommentInboxMessage) Reset() {
	*x = CommentInboxMessage{}
	mi := &file_message_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommentInboxMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommentInboxMessage) ProtoMessage() {}

func (x *CommentInboxMessage) ProtoReflect() protoreflect.Message {
	mi := &file_message_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommentInboxMessage.ProtoReflect.Descriptor instead.
func (*CommentInboxMessage) Descriptor() ([]byte, []int) {
	return file_message_proto_rawDescGZIP(), []int{1}
}

func (x *CommentInboxMessage) GetUid() string {
	if x != nil {
		return x.Uid
	}
	return ""
}

func (x *CommentInboxMessage) GetIsRead() bool {
	if x != nil {
		return x.IsRead
	}
	return false
}

func (x *CommentInboxMessage) GetActor() *InboxMessageActor {
	if x != nil {
		return x.Actor
	}
	return nil
}

func (x *CommentInboxMessage) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *CommentInboxMessage) GetCommentUid() string {
	if x != nil {
		return x.CommentUid
	}
	return ""
}

func (x *CommentInboxMessage) GetCommentContent() string {
	if x != nil {
		return x.CommentContent
	}
	return ""
}

func (x *CommentInboxMessage) GetPostUid() string {
	if x != nil {
		return x.PostUid
	}
	return ""
}

func (x *CommentInboxMessage) GetParentUid() string {
	if x != nil {
		return x.ParentUid
	}
	return ""
}

func (x *CommentInboxMessage) GetParentContent() string {
	if x != nil {
		return x.ParentContent
	}
	return ""
}

type FollowInboxMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uid           string                 `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`
	IsRead        bool                   `protobuf:"varint,2,opt,name=is_read,json=isRead,proto3" json:"is_read,omitempty"`
	Actor         *InboxMessageActor     `protobuf:"bytes,3,opt,name=actor,proto3" json:"actor,omitempty"`
	CreatedAt     int64                  `protobuf:"varint,4,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FollowInboxMessage) Reset() {
	*x = FollowInboxMessage{}
	mi := &file_message_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FollowInboxMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FollowInboxMessage) ProtoMessage() {}

func (x *FollowInboxMessage) ProtoReflect() protoreflect.Message {
	mi := &file_message_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FollowInboxMessage.ProtoReflect.Descriptor instead.
func (*FollowInboxMessage) Descriptor() ([]byte, []int) {
	return file_message_proto_rawDescGZIP(), []int{2}
}

func (x *FollowInboxMessage) GetUid() string {
	if x != nil {
		return x.Uid
	}
	return ""
}

func (x *FollowInboxMessage) GetIsRead() bool {
	if x != nil {
		return x.IsRead
	}
	return false
}

func (x *FollowInboxMessage) GetActor() *InboxMessageActor {
	if x != nil {
		return x.Actor
	}
	return nil
}

func (x *FollowInboxMessage) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

type ListCommentInboxMessagesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ReadFilter    InboxMessageReadFilter `protobuf:"varint,1,opt,name=read_filter,json=readFilter,proto3,enum=message.InboxMessageReadFilter" json:"read_filter,omitempty"`
	PageToken     string                 `protobuf:"bytes,2,opt,name=page_token,json=pageToken,proto3" json:"page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListCommentInboxMessagesRequest) Reset() {
	*x = ListCommentInboxMessagesRequest{}
	mi := &file_message_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListCommentInboxMessagesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListCommentInboxMessagesRequest) ProtoMessage() {}

func (x *ListCommentInboxMessagesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_message_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListCommentInboxMessagesRequest.ProtoReflect.Descriptor instead.
func (*ListCommentInboxMessagesRequest) Descriptor() ([]byte, []int) {
	return file_message_proto_rawDescGZIP(), []int{3}
}

func (x *ListCommentInboxMessagesRequest) GetReadFilter() InboxMessageReadFilter {
	if x != nil {
		return x.ReadFilter
	}
	return InboxMessageReadFilter_INBOX_MESSAGE_READ_FILTER_UNSPECIFIED
}

func (x *ListCommentInboxMessagesRequest) GetPageToken() string {
	if x != nil {
		return x.PageToken
	}
	return ""
}

type ListCommentInboxMessagesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Messages      []*CommentInboxMessage `protobuf:"bytes,1,rep,name=messages,proto3" json:"messages,omitempty"`
	NextPageToken string                 `protobuf:"bytes,2,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListCommentInboxMessagesResponse) Reset() {
	*x = ListCommentInboxMessagesResponse{}
	mi := &file_message_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListCommentInboxMessagesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListCommentInboxMessagesResponse) ProtoMessage() {}

func (x *ListCommentInboxMessagesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_message_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListCommentInboxMessagesResponse.ProtoReflect.Descriptor instead.
func (*ListCommentInboxMessagesResponse) Descriptor() ([]byte, []int) {
	return file_message_proto_rawDescGZIP(), []int{4}
}

func (x *ListCommentInboxMessagesResponse) GetMessages() []*CommentInboxMessage {
	if x != nil {
		return x.Messages
	}
	return nil
}

func (x *ListCommentInboxMessagesResponse) GetNextPageToken() string {
	if x != nil {
		return x.NextPageToken
	}
	return ""
}

type ListFollowInboxMessagesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ReadFilter    InboxMessageReadFilter `protobuf:"varint,1,opt,name=read_filter,json=readFilter,proto3,enum=message.InboxMessageReadFilter" json:"read_filter,omitempty"`
	PageToken     string                 `protobuf:"bytes,2,opt,name=page_token,json=pageToken,proto3" json:"page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListFollowInboxMessagesRequest) Reset() {
	*x = ListFollowInboxMessagesRequest{}
	mi := &file_message_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListFollowInboxMessagesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListFollowInboxMessagesRequest) ProtoMessage() {}

func (x *ListFollowInboxMessagesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_message_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListFollowInboxMessagesRequest.ProtoReflect.Descriptor instead.
func (*ListFollowInboxMessagesRequest) Descriptor() ([]byte, []int) {
	return file_message_proto_rawDescGZIP(), []int{5}
}

func (x *ListFollowInboxMessagesRequest) GetReadFilter() InboxMessageReadFilter {
	if x != nil {
		return x.ReadFilter
	}
	return InboxMessageReadFilter_INBOX_MESSAGE_READ_FILTER_UNSPECIFIED
}

func (x *ListFollowInboxMessagesRequest) GetPageToken() string {
	if x != nil {
		return x.PageToken
	}
	return ""
}

type ListFollowInboxMessagesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Messages      []*FollowInboxMessage  `protobuf:"bytes,1,rep,name=messages,proto3" json:"messages,omitempty"`
	NextPageToken string                 `protobuf:"bytes,2,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListFollowInboxMessagesResponse) Reset() {
	*x = ListFollowInboxMessagesResponse{}
	mi := &file_message_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListFollowInboxMessagesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListFollowInboxMessagesResponse) ProtoMessage() {}

func (x *ListFollowInboxMessagesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_message_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListFollowInboxMessagesResponse.ProtoReflect.Descriptor instead.
func (*ListFollowInboxMessagesResponse) Descriptor() ([]byte, []int) {
	return file_message_proto_rawDescGZIP(), []int{6}
}

func (x *ListFollowInboxMessagesResponse) GetMessages() []*FollowInboxMessage {
	if x != nil {
		return x.Messages
	}
	return nil
}

func (x *ListFollowInboxMessagesResponse) GetNextPageToken() string {
	if x != nil {
		return x.NextPageToken
	}
	return ""
}

type DeleteInboxMessageRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uid           string                 `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteInboxMessageRequest) Reset() {
	*x = DeleteInboxMessageRequest{}
	mi := &file_message_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteInboxMessageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteInboxMessageRequest) ProtoMessage() {}

func (x *DeleteInboxMessageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_message_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteInboxMessageRequest.ProtoReflect.Descriptor instead.
func (*DeleteInboxMessageRequest) Descriptor() ([]byte, []int) {
	return file_message_proto_rawDescGZIP(), []int{7}
}

func (x *DeleteInboxMessageRequest) GetUid() string {
	if x != nil {
		return x.Uid
	}
	return ""
}

type MarkAllInboxMessagesReadResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UpdatedCount  int32                  `protobuf:"varint,1,opt,name=updated_count,json=updatedCount,proto3" json:"updated_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MarkAllInboxMessagesReadResponse) Reset() {
	*x = MarkAllInboxMessagesReadResponse{}
	mi := &file_message_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MarkAllInboxMessagesReadResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MarkAllInboxMessagesReadResponse) ProtoMessage() {}

func (x *MarkAllInboxMessagesReadResponse) ProtoReflect() protoreflect.Message {
	mi := &file_message_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MarkAllInboxMessagesReadResponse.ProtoReflect.Descriptor instead.
func (*MarkAllInboxMessagesReadResponse) Descriptor() ([]byte, []int) {
	return file_message_proto_rawDescGZIP(), []int{8}
}

func (x *MarkAllInboxMessagesReadResponse) GetUpdatedCount() int32 {
	if x != nil {
		return x.UpdatedCount
	}
	return 0
}

type CountUnreadInboxMessagesResponse struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	UnreadCount        int32                  `protobuf:"varint,1,opt,name=unread_count,json=unreadCount,proto3" json:"unread_count,omitempty"`
	FollowUnreadCount  int32                  `protobuf:"varint,2,opt,name=follow_unread_count,json=followUnreadCount,proto3" json:"follow_unread_count,omitempty"`
	CommentUnreadCount int32                  `protobuf:"varint,3,opt,name=comment_unread_count,json=commentUnreadCount,proto3" json:"comment_unread_count,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *CountUnreadInboxMessagesResponse) Reset() {
	*x = CountUnreadInboxMessagesResponse{}
	mi := &file_message_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CountUnreadInboxMessagesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CountUnreadInboxMessagesResponse) ProtoMessage() {}

func (x *CountUnreadInboxMessagesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_message_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CountUnreadInboxMessagesResponse.ProtoReflect.Descriptor instead.
func (*CountUnreadInboxMessagesResponse) Descriptor() ([]byte, []int) {
	return file_message_proto_rawDescGZIP(), []int{9}
}

func (x *CountUnreadInboxMessagesResponse) GetUnreadCount() int32 {
	if x != nil {
		return x.UnreadCount
	}
	return 0
}

func (x *CountUnreadInboxMessagesResponse) GetFollowUnreadCount() int32 {
	if x != nil {
		return x.FollowUnreadCount
	}
	return 0
}

func (x *CountUnreadInboxMessagesResponse) GetCommentUnreadCount() int32 {
	if x != nil {
		return x.CommentUnreadCount
	}
	return 0
}

var File_message_proto protoreflect.FileDescriptor

const file_message_proto_rawDesc = "" +
	"\n" +
	"\rmessage.proto\x12\amessage\x1a\x1cgoogle/api/annotations.proto\x1a\x1fgoogle/api/field_behavior.proto\x1a\x1bgoogle/protobuf/empty.proto\"o\n" +
	"\x11InboxMessageActor\x12\x15\n" +
	"\x03uid\x18\x01 \x01(\tB\x03\xe0A\x02R\x03uid\x12\x1f\n" +
	"\bnickname\x18\x02 \x01(\tB\x03\xe0A\x02R\bnickname\x12\"\n" +
	"\n" +
	"avatar_url\x18\x03 \x01(\tB\x03\xe0A\x02R\tavatarUrl\"\xd0\x02\n" +
	"\x13CommentInboxMessage\x12\x15\n" +
	"\x03uid\x18\x01 \x01(\tB\x03\xe0A\x02R\x03uid\x12\x1c\n" +
	"\ais_read\x18\x02 \x01(\bB\x03\xe0A\x02R\x06isRead\x125\n" +
	"\x05actor\x18\x03 \x01(\v2\x1a.message.InboxMessageActorB\x03\xe0A\x02R\x05actor\x12\"\n" +
	"\n" +
	"created_at\x18\x04 \x01(\x03B\x03\xe0A\x02R\tcreatedAt\x12\x1f\n" +
	"\vcomment_uid\x18\x05 \x01(\tR\n" +
	"commentUid\x12'\n" +
	"\x0fcomment_content\x18\x06 \x01(\tR\x0ecommentContent\x12\x19\n" +
	"\bpost_uid\x18\a \x01(\tR\apostUid\x12\x1d\n" +
	"\n" +
	"parent_uid\x18\b \x01(\tR\tparentUid\x12%\n" +
	"\x0eparent_content\x18\t \x01(\tR\rparentContent\"\xa4\x01\n" +
	"\x12FollowInboxMessage\x12\x15\n" +
	"\x03uid\x18\x01 \x01(\tB\x03\xe0A\x02R\x03uid\x12\x1c\n" +
	"\ais_read\x18\x02 \x01(\bB\x03\xe0A\x02R\x06isRead\x125\n" +
	"\x05actor\x18\x03 \x01(\v2\x1a.message.InboxMessageActorB\x03\xe0A\x02R\x05actor\x12\"\n" +
	"\n" +
	"created_at\x18\x04 \x01(\x03B\x03\xe0A\x02R\tcreatedAt\"\x82\x01\n" +
	"\x1fListCommentInboxMessagesRequest\x12@\n" +
	"\vread_filter\x18\x01 \x01(\x0e2\x1f.message.InboxMessageReadFilterR\n" +
	"readFilter\x12\x1d\n" +
	"\n" +
	"page_token\x18\x02 \x01(\tR\tpageToken\"\x8e\x01\n" +
	" ListCommentInboxMessagesResponse\x12=\n" +
	"\bmessages\x18\x01 \x03(\v2\x1c.message.CommentInboxMessageB\x03\xe0A\x02R\bmessages\x12+\n" +
	"\x0fnext_page_token\x18\x02 \x01(\tB\x03\xe0A\x02R\rnextPageToken\"\x81\x01\n" +
	"\x1eListFollowInboxMessagesRequest\x12@\n" +
	"\vread_filter\x18\x01 \x01(\x0e2\x1f.message.InboxMessageReadFilterR\n" +
	"readFilter\x12\x1d\n" +
	"\n" +
	"page_token\x18\x02 \x01(\tR\tpageToken\"\x8c\x01\n" +
	"\x1fListFollowInboxMessagesResponse\x12<\n" +
	"\bmessages\x18\x01 \x03(\v2\x1b.message.FollowInboxMessageB\x03\xe0A\x02R\bmessages\x12+\n" +
	"\x0fnext_page_token\x18\x02 \x01(\tB\x03\xe0A\x02R\rnextPageToken\"2\n" +
	"\x19DeleteInboxMessageRequest\x12\x15\n" +
	"\x03uid\x18\x01 \x01(\tB\x03\xe0A\x02R\x03uid\"L\n" +
	" MarkAllInboxMessagesReadResponse\x12(\n" +
	"\rupdated_count\x18\x01 \x01(\x05B\x03\xe0A\x02R\fupdatedCount\"\xb6\x01\n" +
	" CountUnreadInboxMessagesResponse\x12&\n" +
	"\funread_count\x18\x01 \x01(\x05B\x03\xe0A\x02R\vunreadCount\x123\n" +
	"\x13follow_unread_count\x18\x02 \x01(\x05B\x03\xe0A\x02R\x11followUnreadCount\x125\n" +
	"\x14comment_unread_count\x18\x03 \x01(\x05B\x03\xe0A\x02R\x12commentUnreadCount*\x8d\x01\n" +
	"\x16InboxMessageReadFilter\x12)\n" +
	"%INBOX_MESSAGE_READ_FILTER_UNSPECIFIED\x10\x00\x12$\n" +
	" INBOX_MESSAGE_READ_FILTER_UNREAD\x10\x01\x12\"\n" +
	"\x1eINBOX_MESSAGE_READ_FILTER_READ\x10\x022\xdb\x05\n" +
	"\x0eMessageService\x12\x9b\x01\n" +
	"\x18ListCommentInboxMessages\x12(.message.ListCommentInboxMessagesRequest\x1a).message.ListCommentInboxMessagesResponse\"*\x82\xd3\xe4\x93\x02$\x12\"/api/v1/me/inbox/messages/comments\x12\x97\x01\n" +
	"\x17ListFollowInboxMessages\x12'.message.ListFollowInboxMessagesRequest\x1a(.message.ListFollowInboxMessagesResponse\")\x82\xd3\xe4\x93\x02#\x12!/api/v1/me/inbox/messages/follows\x12y\n" +
	"\x12DeleteInboxMessage\x12\".message.DeleteInboxMessageRequest\x1a\x16.google.protobuf.Empty\"'\x82\xd3\xe4\x93\x02!*\x1f/api/v1/me/inbox/messages/{uid}\x12\x85\x01\n" +
	"\x18MarkAllInboxMessagesRead\x12\x16.google.protobuf.Empty\x1a).message.MarkAllInboxMessagesReadResponse\"&\x82\xd3\xe4\x93\x02 2\x1e/api/v1/me/inbox/messages/read\x12\x8d\x01\n" +
	"\x18CountUnreadInboxMessages\x12\x16.google.protobuf.Empty\x1a).message.CountUnreadInboxMessagesResponse\".\x82\xd3\xe4\x93\x02(\x12&/api/v1/me/inbox/messages/unread/countB\x0fZ\raeibi/api;apib\x06proto3"

var (
	file_message_proto_rawDescOnce sync.Once
	file_message_proto_rawDescData []byte
)

func file_message_proto_rawDescGZIP() []byte {
	file_message_proto_rawDescOnce.Do(func() {
		file_message_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_message_proto_rawDesc), len(file_message_proto_rawDesc)))
	})
	return file_message_proto_rawDescData
}

var file_message_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_message_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_message_proto_goTypes = []any{
	(InboxMessageReadFilter)(0),              // 0: message.InboxMessageReadFilter
	(*InboxMessageActor)(nil),                // 1: message.InboxMessageActor
	(*CommentInboxMessage)(nil),              // 2: message.CommentInboxMessage
	(*FollowInboxMessage)(nil),               // 3: message.FollowInboxMessage
	(*ListCommentInboxMessagesRequest)(nil),  // 4: message.ListCommentInboxMessagesRequest
	(*ListCommentInboxMessagesResponse)(nil), // 5: message.ListCommentInboxMessagesResponse
	(*ListFollowInboxMessagesRequest)(nil),   // 6: message.ListFollowInboxMessagesRequest
	(*ListFollowInboxMessagesResponse)(nil),  // 7: message.ListFollowInboxMessagesResponse
	(*DeleteInboxMessageRequest)(nil),        // 8: message.DeleteInboxMessageRequest
	(*MarkAllInboxMessagesReadResponse)(nil), // 9: message.MarkAllInboxMessagesReadResponse
	(*CountUnreadInboxMessagesResponse)(nil), // 10: message.CountUnreadInboxMessagesResponse
	(*emptypb.Empty)(nil),                    // 11: google.protobuf.Empty
}
var file_message_proto_depIdxs = []int32{
	1,  // 0: message.CommentInboxMessage.actor:type_name -> message.InboxMessageActor
	1,  // 1: message.FollowInboxMessage.actor:type_name -> message.InboxMessageActor
	0,  // 2: message.ListCommentInboxMessagesRequest.read_filter:type_name -> message.InboxMessageReadFilter
	2,  // 3: message.ListCommentInboxMessagesResponse.messages:type_name -> message.CommentInboxMessage
	0,  // 4: message.ListFollowInboxMessagesRequest.read_filter:type_name -> message.InboxMessageReadFilter
	3,  // 5: message.ListFollowInboxMessagesResponse.messages:type_name -> message.FollowInboxMessage
	4,  // 6: message.MessageService.ListCommentInboxMessages:input_type -> message.ListCommentInboxMessagesRequest
	6,  // 7: message.MessageService.ListFollowInboxMessages:input_type -> message.ListFollowInboxMessagesRequest
	8,  // 8: message.MessageService.DeleteInboxMessage:input_type -> message.DeleteInboxMessageRequest
	11, // 9: message.MessageService.MarkAllInboxMessagesRead:input_type -> google.protobuf.Empty
	11, // 10: message.MessageService.CountUnreadInboxMessages:input_type -> google.protobuf.Empty
	5,  // 11: message.MessageService.ListCommentInboxMessages:output_type -> message.ListCommentInboxMessagesResponse
	7,  // 12: message.MessageService.ListFollowInboxMessages:output_type -> message.ListFollowInboxMessagesResponse
	11, // 13: message.MessageService.DeleteInboxMessage:output_type -> google.protobuf.Empty
	9,  // 14: message.MessageService.MarkAllInboxMessagesRead:output_type -> message.MarkAllInboxMessagesReadResponse
	10, // 15: message.MessageService.CountUnreadInboxMessages:output_type -> message.CountUnreadInboxMessagesResponse
	11, // [11:16] is the sub-list for method output_type
	6,  // [6:11] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_message_proto_init() }
func file_message_proto_init() {
	if File_message_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_message_proto_rawDesc), len(file_message_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_message_proto_goTypes,
		DependencyIndexes: file_message_proto_depIdxs,
		EnumInfos:         file_message_proto_enumTypes,
		MessageInfos:      file_message_proto_msgTypes,
	}.Build()
	File_message_proto = out.File
	file_message_proto_goTypes = nil
	file_message_proto_depIdxs = nil
}
