// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             (unknown)
// source: message.proto

package api

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	MessageService_ListCommentInboxMessages_FullMethodName = "/message.MessageService/ListCommentInboxMessages"
	MessageService_ListFollowInboxMessages_FullMethodName  = "/message.MessageService/ListFollowInboxMessages"
	MessageService_DeleteInboxMessage_FullMethodName       = "/message.MessageService/DeleteInboxMessage"
	MessageService_MarkAllInboxMessagesRead_FullMethodName = "/message.MessageService/MarkAllInboxMessagesRead"
	MessageService_CountUnreadInboxMessages_FullMethodName = "/message.MessageService/CountUnreadInboxMessages"
)

// MessageServiceClient is the client API for MessageService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// MessageService
type MessageServiceClient interface {
	// GET /api/v1/me/inbox/messages/comments 当前用户评论消息列表
	ListCommentInboxMessages(ctx context.Context, in *ListCommentInboxMessagesRequest, opts ...grpc.CallOption) (*ListCommentInboxMessagesResponse, error)
	// GET /api/v1/me/inbox/messages/follows 当前用户关注消息列表
	ListFollowInboxMessages(ctx context.Context, in *ListFollowInboxMessagesRequest, opts ...grpc.CallOption) (*ListFollowInboxMessagesResponse, error)
	// DELETE /api/v1/me/inbox/messages/{uid} 归档一条消息
	DeleteInboxMessage(ctx context.Context, in *DeleteInboxMessageRequest, opts ...grpc.CallOption) (*DeleteInboxMessageResponse, error)
	// PATCH /api/v1/me/inbox/messages/read 全部标记为已读
	MarkAllInboxMessagesRead(ctx context.Context, in *MarkAllInboxMessagesReadRequest, opts ...grpc.CallOption) (*MarkAllInboxMessagesReadResponse, error)
	// GET /api/v1/me/inbox/messages/unread/count 未读计数
	CountUnreadInboxMessages(ctx context.Context, in *CountUnreadInboxMessagesRequest, opts ...grpc.CallOption) (*CountUnreadInboxMessagesResponse, error)
}

type messageServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewMessageServiceClient(cc grpc.ClientConnInterface) MessageServiceClient {
	return &messageServiceClient{cc}
}

func (c *messageServiceClient) ListCommentInboxMessages(ctx context.Context, in *ListCommentInboxMessagesRequest, opts ...grpc.CallOption) (*ListCommentInboxMessagesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListCommentInboxMessagesResponse)
	err := c.cc.Invoke(ctx, MessageService_ListCommentInboxMessages_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *messageServiceClient) ListFollowInboxMessages(ctx context.Context, in *ListFollowInboxMessagesRequest, opts ...grpc.CallOption) (*ListFollowInboxMessagesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListFollowInboxMessagesResponse)
	err := c.cc.Invoke(ctx, MessageService_ListFollowInboxMessages_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *messageServiceClient) DeleteInboxMessage(ctx context.Context, in *DeleteInboxMessageRequest, opts ...grpc.CallOption) (*DeleteInboxMessageResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteInboxMessageResponse)
	err := c.cc.Invoke(ctx, MessageService_DeleteInboxMessage_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *messageServiceClient) MarkAllInboxMessagesRead(ctx context.Context, in *MarkAllInboxMessagesReadRequest, opts ...grpc.CallOption) (*MarkAllInboxMessagesReadResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MarkAllInboxMessagesReadResponse)
	err := c.cc.Invoke(ctx, MessageService_MarkAllInboxMessagesRead_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *messageServiceClient) CountUnreadInboxMessages(ctx context.Context, in *CountUnreadInboxMessagesRequest, opts ...grpc.CallOption) (*CountUnreadInboxMessagesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CountUnreadInboxMessagesResponse)
	err := c.cc.Invoke(ctx, MessageService_CountUnreadInboxMessages_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MessageServiceServer is the server API for MessageService service.
// All implementations must embed UnimplementedMessageServiceServer
// for forward compatibility.
//
// MessageService
type MessageServiceServer interface {
	// GET /api/v1/me/inbox/messages/comments 当前用户评论消息列表
	ListCommentInboxMessages(context.Context, *ListCommentInboxMessagesRequest) (*ListCommentInboxMessagesResponse, error)
	// GET /api/v1/me/inbox/messages/follows 当前用户关注消息列表
	ListFollowInboxMessages(context.Context, *ListFollowInboxMessagesRequest) (*ListFollowInboxMessagesResponse, error)
	// DELETE /api/v1/me/inbox/messages/{uid} 归档一条消息
	DeleteInboxMessage(context.Context, *DeleteInboxMessageRequest) (*DeleteInboxMessageResponse, error)
	// PATCH /api/v1/me/inbox/messages/read 全部标记为已读
	MarkAllInboxMessagesRead(context.Context, *MarkAllInboxMessagesReadRequest) (*MarkAllInboxMessagesReadResponse, error)
	// GET /api/v1/me/inbox/messages/unread/count 未读计数
	CountUnreadInboxMessages(context.Context, *CountUnreadInboxMessagesRequest) (*CountUnreadInboxMessagesResponse, error)
	mustEmbedUnimplementedMessageServiceServer()
}

// UnimplementedMessageServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedMessageServiceServer struct{}

func (UnimplementedMessageServiceServer) ListCommentInboxMessages(context.Context, *ListCommentInboxMessagesRequest) (*ListCommentInboxMessagesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListCommentInboxMessages not implemented")
}
func (UnimplementedMessageServiceServer) ListFollowInboxMessages(context.Context, *ListFollowInboxMessagesRequest) (*ListFollowInboxMessagesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListFollowInboxMessages not implemented")
}
func (UnimplementedMessageServiceServer) DeleteInboxMessage(context.Context, *DeleteInboxMessageRequest) (*DeleteInboxMessageResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteInboxMessage not implemented")
}
func (UnimplementedMessageServiceServer) MarkAllInboxMessagesRead(context.Context, *MarkAllInboxMessagesReadRequest) (*MarkAllInboxMessagesReadResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method MarkAllInboxMessagesRead not implemented")
}
func (UnimplementedMessageServiceServer) CountUnreadInboxMessages(context.Context, *CountUnreadInboxMessagesRequest) (*CountUnreadInboxMessagesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CountUnreadInboxMessages not implemented")
}
func (UnimplementedMessageServiceServer) mustEmbedUnimplementedMessageServiceServer() {}
func (UnimplementedMessageServiceServer) testEmbeddedByValue()                        {}

// UnsafeMessageServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MessageServiceServer will
// result in compilation errors.
type UnsafeMessageServiceServer interface {
	mustEmbedUnimplementedMessageServiceServer()
}

func RegisterMessageServiceServer(s grpc.ServiceRegistrar, srv MessageServiceServer) {
	// If the following call panics, it indicates UnimplementedMessageServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&MessageService_ServiceDesc, srv)
}

func _MessageService_ListCommentInboxMessages_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListCommentInboxMessagesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MessageServiceServer).ListCommentInboxMessages(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MessageService_ListCommentInboxMessages_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MessageServiceServer).ListCommentInboxMessages(ctx, req.(*ListCommentInboxMessagesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MessageService_ListFollowInboxMessages_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListFollowInboxMessagesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MessageServiceServer).ListFollowInboxMessages(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MessageService_ListFollowInboxMessages_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MessageServiceServer).ListFollowInboxMessages(ctx, req.(*ListFollowInboxMessagesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MessageService_DeleteInboxMessage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteInboxMessageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MessageServiceServer).DeleteInboxMessage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MessageService_DeleteInboxMessage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MessageServiceServer).DeleteInboxMessage(ctx, req.(*DeleteInboxMessageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MessageService_MarkAllInboxMessagesRead_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MarkAllInboxMessagesReadRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MessageServiceServer).MarkAllInboxMessagesRead(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MessageService_MarkAllInboxMessagesRead_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MessageServiceServer).MarkAllInboxMessagesRead(ctx, req.(*MarkAllInboxMessagesReadRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MessageService_CountUnreadInboxMessages_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CountUnreadInboxMessagesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MessageServiceServer).CountUnreadInboxMessages(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MessageService_CountUnreadInboxMessages_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MessageServiceServer).CountUnreadInboxMessages(ctx, req.(*CountUnreadInboxMessagesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// MessageService_ServiceDesc is the grpc.ServiceDesc for MessageService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MessageService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "message.MessageService",
	HandlerType: (*MessageServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListCommentInboxMessages",
			Handler:    _MessageService_ListCommentInboxMessages_Handler,
		},
		{
			MethodName: "ListFollowInboxMessages",
			Handler:    _MessageService_ListFollowInboxMessages_Handler,
		},
		{
			MethodName: "DeleteInboxMessage",
			Handler:    _MessageService_DeleteInboxMessage_Handler,
		},
		{
			MethodName: "MarkAllInboxMessagesRead",
			Handler:    _MessageService_MarkAllInboxMessagesRead_Handler,
		},
		{
			MethodName: "CountUnreadInboxMessages",
			Handler:    _MessageService_CountUnreadInboxMessages_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "message.proto",
}
