// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: post.proto

package api

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	fieldmaskpb "google.golang.org/protobuf/types/known/fieldmaskpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Models
type PostAuthor struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uid           string                 `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`
	Nickname      string                 `protobuf:"bytes,2,opt,name=nickname,proto3" json:"nickname,omitempty"`
	AvatarUrl     string                 `protobuf:"bytes,3,opt,name=avatar_url,json=avatarUrl,proto3" json:"avatar_url,omitempty"`
	IsFollowing   bool                   `protobuf:"varint,4,opt,name=is_following,json=isFollowing,proto3" json:"is_following,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PostAuthor) Reset() {
	*x = PostAuthor{}
	mi := &file_post_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PostAuthor) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PostAuthor) ProtoMessage() {}

func (x *PostAuthor) ProtoReflect() protoreflect.Message {
	mi := &file_post_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PostAuthor.ProtoReflect.Descriptor instead.
func (*PostAuthor) Descriptor() ([]byte, []int) {
	return file_post_proto_rawDescGZIP(), []int{0}
}

func (x *PostAuthor) GetUid() string {
	if x != nil {
		return x.Uid
	}
	return ""
}

func (x *PostAuthor) GetNickname() string {
	if x != nil {
		return x.Nickname
	}
	return ""
}

func (x *PostAuthor) GetAvatarUrl() string {
	if x != nil {
		return x.AvatarUrl
	}
	return ""
}

func (x *PostAuthor) GetIsFollowing() bool {
	if x != nil {
		return x.IsFollowing
	}
	return false
}

type Attachment struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Url           string                 `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Size          int64                  `protobuf:"varint,3,opt,name=size,proto3" json:"size,omitempty"`
	ContentType   string                 `protobuf:"bytes,4,opt,name=content_type,json=contentType,proto3" json:"content_type,omitempty"`
	Checksum      string                 `protobuf:"bytes,5,opt,name=checksum,proto3" json:"checksum,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Attachment) Reset() {
	*x = Attachment{}
	mi := &file_post_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Attachment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Attachment) ProtoMessage() {}

func (x *Attachment) ProtoReflect() protoreflect.Message {
	mi := &file_post_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Attachment.ProtoReflect.Descriptor instead.
func (*Attachment) Descriptor() ([]byte, []int) {
	return file_post_proto_rawDescGZIP(), []int{1}
}

func (x *Attachment) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *Attachment) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Attachment) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *Attachment) GetContentType() string {
	if x != nil {
		return x.ContentType
	}
	return ""
}

func (x *Attachment) GetChecksum() string {
	if x != nil {
		return x.Checksum
	}
	return ""
}

type Post struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Uid             string                 `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`
	Author          *PostAuthor            `protobuf:"bytes,2,opt,name=author,proto3" json:"author,omitempty"`
	Text            string                 `protobuf:"bytes,3,opt,name=text,proto3" json:"text,omitempty"`
	Images          []string               `protobuf:"bytes,4,rep,name=images,proto3" json:"images,omitempty"`
	Attachments     []*Attachment          `protobuf:"bytes,5,rep,name=attachments,proto3" json:"attachments,omitempty"`
	Tags            []string               `protobuf:"bytes,6,rep,name=tags,proto3" json:"tags,omitempty"`
	CommentCount    int32                  `protobuf:"varint,7,opt,name=comment_count,json=commentCount,proto3" json:"comment_count,omitempty"`
	CollectionCount int32                  `protobuf:"varint,8,opt,name=collection_count,json=collectionCount,proto3" json:"collection_count,omitempty"`
	LikeCount       int32                  `protobuf:"varint,9,opt,name=like_count,json=likeCount,proto3" json:"like_count,omitempty"`
	Visibility      string                 `protobuf:"bytes,10,opt,name=visibility,proto3" json:"visibility,omitempty"`
	LatestRepliedOn int64                  `protobuf:"varint,11,opt,name=latest_replied_on,json=latestRepliedOn,proto3" json:"latest_replied_on,omitempty"`
	Ip              string                 `protobuf:"bytes,12,opt,name=ip,proto3" json:"ip,omitempty"`
	Pinned          bool                   `protobuf:"varint,13,opt,name=pinned,proto3" json:"pinned,omitempty"`
	Liked           bool                   `protobuf:"varint,14,opt,name=liked,proto3" json:"liked,omitempty"`
	Collected       bool                   `protobuf:"varint,15,opt,name=collected,proto3" json:"collected,omitempty"`
	CreatedAt       int64                  `protobuf:"varint,16,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt       int64                  `protobuf:"varint,17,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Post) Reset() {
	*x = Post{}
	mi := &file_post_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Post) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Post) ProtoMessage() {}

func (x *Post) ProtoReflect() protoreflect.Message {
	mi := &file_post_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Post.ProtoReflect.Descriptor instead.
func (*Post) Descriptor() ([]byte, []int) {
	return file_post_proto_rawDescGZIP(), []int{2}
}

func (x *Post) GetUid() string {
	if x != nil {
		return x.Uid
	}
	return ""
}

func (x *Post) GetAuthor() *PostAuthor {
	if x != nil {
		return x.Author
	}
	return nil
}

func (x *Post) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *Post) GetImages() []string {
	if x != nil {
		return x.Images
	}
	return nil
}

func (x *Post) GetAttachments() []*Attachment {
	if x != nil {
		return x.Attachments
	}
	return nil
}

func (x *Post) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *Post) GetCommentCount() int32 {
	if x != nil {
		return x.CommentCount
	}
	return 0
}

func (x *Post) GetCollectionCount() int32 {
	if x != nil {
		return x.CollectionCount
	}
	return 0
}

func (x *Post) GetLikeCount() int32 {
	if x != nil {
		return x.LikeCount
	}
	return 0
}

func (x *Post) GetVisibility() string {
	if x != nil {
		return x.Visibility
	}
	return ""
}

func (x *Post) GetLatestRepliedOn() int64 {
	if x != nil {
		return x.LatestRepliedOn
	}
	return 0
}

func (x *Post) GetIp() string {
	if x != nil {
		return x.Ip
	}
	return ""
}

func (x *Post) GetPinned() bool {
	if x != nil {
		return x.Pinned
	}
	return false
}

func (x *Post) GetLiked() bool {
	if x != nil {
		return x.Liked
	}
	return false
}

func (x *Post) GetCollected() bool {
	if x != nil {
		return x.Collected
	}
	return false
}

func (x *Post) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *Post) GetUpdatedAt() int64 {
	if x != nil {
		return x.UpdatedAt
	}
	return 0
}

type CreatePostRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Text          string                 `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
	Images        []string               `protobuf:"bytes,2,rep,name=images,proto3" json:"images,omitempty"`
	Attachments   []string               `protobuf:"bytes,3,rep,name=attachments,proto3" json:"attachments,omitempty"`
	Tags          []string               `protobuf:"bytes,4,rep,name=tags,proto3" json:"tags,omitempty"`
	Visibility    string                 `protobuf:"bytes,5,opt,name=visibility,proto3" json:"visibility,omitempty"`
	Pinned        bool                   `protobuf:"varint,6,opt,name=pinned,proto3" json:"pinned,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreatePostRequest) Reset() {
	*x = CreatePostRequest{}
	mi := &file_post_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreatePostRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePostRequest) ProtoMessage() {}

func (x *CreatePostRequest) ProtoReflect() protoreflect.Message {
	mi := &file_post_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePostRequest.ProtoReflect.Descriptor instead.
func (*CreatePostRequest) Descriptor() ([]byte, []int) {
	return file_post_proto_rawDescGZIP(), []int{3}
}

func (x *CreatePostRequest) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *CreatePostRequest) GetImages() []string {
	if x != nil {
		return x.Images
	}
	return nil
}

func (x *CreatePostRequest) GetAttachments() []string {
	if x != nil {
		return x.Attachments
	}
	return nil
}

func (x *CreatePostRequest) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *CreatePostRequest) GetVisibility() string {
	if x != nil {
		return x.Visibility
	}
	return ""
}

func (x *CreatePostRequest) GetPinned() bool {
	if x != nil {
		return x.Pinned
	}
	return false
}

type CreatePostResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uid           string                 `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreatePostResponse) Reset() {
	*x = CreatePostResponse{}
	mi := &file_post_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreatePostResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePostResponse) ProtoMessage() {}

func (x *CreatePostResponse) ProtoReflect() protoreflect.Message {
	mi := &file_post_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePostResponse.ProtoReflect.Descriptor instead.
func (*CreatePostResponse) Descriptor() ([]byte, []int) {
	return file_post_proto_rawDescGZIP(), []int{4}
}

func (x *CreatePostResponse) GetUid() string {
	if x != nil {
		return x.Uid
	}
	return ""
}

type ListPostsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Query         string                 `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`
	AuthorUid     string                 `protobuf:"bytes,2,opt,name=author_uid,json=authorUid,proto3" json:"author_uid,omitempty"`
	TagName       string                 `protobuf:"bytes,3,opt,name=tag_name,json=tagName,proto3" json:"tag_name,omitempty"`
	PageToken     string                 `protobuf:"bytes,4,opt,name=page_token,json=pageToken,proto3" json:"page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPostsRequest) Reset() {
	*x = ListPostsRequest{}
	mi := &file_post_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPostsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPostsRequest) ProtoMessage() {}

func (x *ListPostsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_post_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPostsRequest.ProtoReflect.Descriptor instead.
func (*ListPostsRequest) Descriptor() ([]byte, []int) {
	return file_post_proto_rawDescGZIP(), []int{5}
}

func (x *ListPostsRequest) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

func (x *ListPostsRequest) GetAuthorUid() string {
	if x != nil {
		return x.AuthorUid
	}
	return ""
}

func (x *ListPostsRequest) GetTagName() string {
	if x != nil {
		return x.TagName
	}
	return ""
}

func (x *ListPostsRequest) GetPageToken() string {
	if x != nil {
		return x.PageToken
	}
	return ""
}

type SearchPostsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Query         string                 `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`
	AuthorUid     string                 `protobuf:"bytes,2,opt,name=author_uid,json=authorUid,proto3" json:"author_uid,omitempty"`
	TagName       string                 `protobuf:"bytes,3,opt,name=tag_name,json=tagName,proto3" json:"tag_name,omitempty"`
	PageToken     string                 `protobuf:"bytes,4,opt,name=page_token,json=pageToken,proto3" json:"page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchPostsRequest) Reset() {
	*x = SearchPostsRequest{}
	mi := &file_post_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchPostsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchPostsRequest) ProtoMessage() {}

func (x *SearchPostsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_post_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchPostsRequest.ProtoReflect.Descriptor instead.
func (*SearchPostsRequest) Descriptor() ([]byte, []int) {
	return file_post_proto_rawDescGZIP(), []int{6}
}

func (x *SearchPostsRequest) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

func (x *SearchPostsRequest) GetAuthorUid() string {
	if x != nil {
		return x.AuthorUid
	}
	return ""
}

func (x *SearchPostsRequest) GetTagName() string {
	if x != nil {
		return x.TagName
	}
	return ""
}

func (x *SearchPostsRequest) GetPageToken() string {
	if x != nil {
		return x.PageToken
	}
	return ""
}

type ListPostsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Posts         []*Post                `protobuf:"bytes,1,rep,name=posts,proto3" json:"posts,omitempty"`
	NextPageToken string                 `protobuf:"bytes,2,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPostsResponse) Reset() {
	*x = ListPostsResponse{}
	mi := &file_post_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPostsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPostsResponse) ProtoMessage() {}

func (x *ListPostsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_post_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPostsResponse.ProtoReflect.Descriptor instead.
func (*ListPostsResponse) Descriptor() ([]byte, []int) {
	return file_post_proto_rawDescGZIP(), []int{7}
}

func (x *ListPostsResponse) GetPosts() []*Post {
	if x != nil {
		return x.Posts
	}
	return nil
}

func (x *ListPostsResponse) GetNextPageToken() string {
	if x != nil {
		return x.NextPageToken
	}
	return ""
}

type SearchTag struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchTag) Reset() {
	*x = SearchTag{}
	mi := &file_post_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchTag) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchTag) ProtoMessage() {}

func (x *SearchTag) ProtoReflect() protoreflect.Message {
	mi := &file_post_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchTag.ProtoReflect.Descriptor instead.
func (*SearchTag) Descriptor() ([]byte, []int) {
	return file_post_proto_rawDescGZIP(), []int{8}
}

func (x *SearchTag) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type SearchTagsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Query         string                 `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchTagsRequest) Reset() {
	*x = SearchTagsRequest{}
	mi := &file_post_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchTagsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchTagsRequest) ProtoMessage() {}

func (x *SearchTagsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_post_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchTagsRequest.ProtoReflect.Descriptor instead.
func (*SearchTagsRequest) Descriptor() ([]byte, []int) {
	return file_post_proto_rawDescGZIP(), []int{9}
}

func (x *SearchTagsRequest) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

type SearchTagsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tags          []*SearchTag           `protobuf:"bytes,1,rep,name=tags,proto3" json:"tags,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchTagsResponse) Reset() {
	*x = SearchTagsResponse{}
	mi := &file_post_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchTagsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchTagsResponse) ProtoMessage() {}

func (x *SearchTagsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_post_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchTagsResponse.ProtoReflect.Descriptor instead.
func (*SearchTagsResponse) Descriptor() ([]byte, []int) {
	return file_post_proto_rawDescGZIP(), []int{10}
}

func (x *SearchTagsResponse) GetTags() []*SearchTag {
	if x != nil {
		return x.Tags
	}
	return nil
}

type SuggestTagsByPrefixRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Prefix        string                 `protobuf:"bytes,1,opt,name=prefix,proto3" json:"prefix,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SuggestTagsByPrefixRequest) Reset() {
	*x = SuggestTagsByPrefixRequest{}
	mi := &file_post_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SuggestTagsByPrefixRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SuggestTagsByPrefixRequest) ProtoMessage() {}

func (x *SuggestTagsByPrefixRequest) ProtoReflect() protoreflect.Message {
	mi := &file_post_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SuggestTagsByPrefixRequest.ProtoReflect.Descriptor instead.
func (*SuggestTagsByPrefixRequest) Descriptor() ([]byte, []int) {
	return file_post_proto_rawDescGZIP(), []int{11}
}

func (x *SuggestTagsByPrefixRequest) GetPrefix() string {
	if x != nil {
		return x.Prefix
	}
	return ""
}

type SuggestTagsByPrefixResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tags          []*SearchTag           `protobuf:"bytes,1,rep,name=tags,proto3" json:"tags,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SuggestTagsByPrefixResponse) Reset() {
	*x = SuggestTagsByPrefixResponse{}
	mi := &file_post_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SuggestTagsByPrefixResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SuggestTagsByPrefixResponse) ProtoMessage() {}

func (x *SuggestTagsByPrefixResponse) ProtoReflect() protoreflect.Message {
	mi := &file_post_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SuggestTagsByPrefixResponse.ProtoReflect.Descriptor instead.
func (*SuggestTagsByPrefixResponse) Descriptor() ([]byte, []int) {
	return file_post_proto_rawDescGZIP(), []int{12}
}

func (x *SuggestTagsByPrefixResponse) GetTags() []*SearchTag {
	if x != nil {
		return x.Tags
	}
	return nil
}

type GetPostRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uid           string                 `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPostRequest) Reset() {
	*x = GetPostRequest{}
	mi := &file_post_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPostRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPostRequest) ProtoMessage() {}

func (x *GetPostRequest) ProtoReflect() protoreflect.Message {
	mi := &file_post_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPostRequest.ProtoReflect.Descriptor instead.
func (*GetPostRequest) Descriptor() ([]byte, []int) {
	return file_post_proto_rawDescGZIP(), []int{13}
}

func (x *GetPostRequest) GetUid() string {
	if x != nil {
		return x.Uid
	}
	return ""
}

type GetPostResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Post          *Post                  `protobuf:"bytes,1,opt,name=post,proto3" json:"post,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPostResponse) Reset() {
	*x = GetPostResponse{}
	mi := &file_post_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPostResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPostResponse) ProtoMessage() {}

func (x *GetPostResponse) ProtoReflect() protoreflect.Message {
	mi := &file_post_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPostResponse.ProtoReflect.Descriptor instead.
func (*GetPostResponse) Descriptor() ([]byte, []int) {
	return file_post_proto_rawDescGZIP(), []int{14}
}

func (x *GetPostResponse) GetPost() *Post {
	if x != nil {
		return x.Post
	}
	return nil
}

type UpdatePostBody struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Text          string                 `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
	Images        []string               `protobuf:"bytes,2,rep,name=images,proto3" json:"images,omitempty"`
	Attachments   []string               `protobuf:"bytes,3,rep,name=attachments,proto3" json:"attachments,omitempty"`
	Tags          []string               `protobuf:"bytes,4,rep,name=tags,proto3" json:"tags,omitempty"`
	Visibility    string                 `protobuf:"bytes,5,opt,name=visibility,proto3" json:"visibility,omitempty"`
	Pinned        bool                   `protobuf:"varint,6,opt,name=pinned,proto3" json:"pinned,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdatePostBody) Reset() {
	*x = UpdatePostBody{}
	mi := &file_post_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdatePostBody) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdatePostBody) ProtoMessage() {}

func (x *UpdatePostBody) ProtoReflect() protoreflect.Message {
	mi := &file_post_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdatePostBody.ProtoReflect.Descriptor instead.
func (*UpdatePostBody) Descriptor() ([]byte, []int) {
	return file_post_proto_rawDescGZIP(), []int{15}
}

func (x *UpdatePostBody) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *UpdatePostBody) GetImages() []string {
	if x != nil {
		return x.Images
	}
	return nil
}

func (x *UpdatePostBody) GetAttachments() []string {
	if x != nil {
		return x.Attachments
	}
	return nil
}

func (x *UpdatePostBody) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *UpdatePostBody) GetVisibility() string {
	if x != nil {
		return x.Visibility
	}
	return ""
}

func (x *UpdatePostBody) GetPinned() bool {
	if x != nil {
		return x.Pinned
	}
	return false
}

type UpdatePostRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uid           string                 `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`
	Post          *UpdatePostBody        `protobuf:"bytes,2,opt,name=post,proto3" json:"post,omitempty"`
	UpdateMask    *fieldmaskpb.FieldMask `protobuf:"bytes,3,opt,name=update_mask,json=updateMask,proto3" json:"update_mask,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdatePostRequest) Reset() {
	*x = UpdatePostRequest{}
	mi := &file_post_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdatePostRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdatePostRequest) ProtoMessage() {}

func (x *UpdatePostRequest) ProtoReflect() protoreflect.Message {
	mi := &file_post_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdatePostRequest.ProtoReflect.Descriptor instead.
func (*UpdatePostRequest) Descriptor() ([]byte, []int) {
	return file_post_proto_rawDescGZIP(), []int{16}
}

func (x *UpdatePostRequest) GetUid() string {
	if x != nil {
		return x.Uid
	}
	return ""
}

func (x *UpdatePostRequest) GetPost() *UpdatePostBody {
	if x != nil {
		return x.Post
	}
	return nil
}

func (x *UpdatePostRequest) GetUpdateMask() *fieldmaskpb.FieldMask {
	if x != nil {
		return x.UpdateMask
	}
	return nil
}

type DeletePostRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uid           string                 `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeletePostRequest) Reset() {
	*x = DeletePostRequest{}
	mi := &file_post_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeletePostRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeletePostRequest) ProtoMessage() {}

func (x *DeletePostRequest) ProtoReflect() protoreflect.Message {
	mi := &file_post_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeletePostRequest.ProtoReflect.Descriptor instead.
func (*DeletePostRequest) Descriptor() ([]byte, []int) {
	return file_post_proto_rawDescGZIP(), []int{17}
}

func (x *DeletePostRequest) GetUid() string {
	if x != nil {
		return x.Uid
	}
	return ""
}

type LikePostRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uid           string                 `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`
	Action        ToggleAction           `protobuf:"varint,2,opt,name=action,proto3,enum=common.ToggleAction" json:"action,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LikePostRequest) Reset() {
	*x = LikePostRequest{}
	mi := &file_post_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LikePostRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LikePostRequest) ProtoMessage() {}

func (x *LikePostRequest) ProtoReflect() protoreflect.Message {
	mi := &file_post_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LikePostRequest.ProtoReflect.Descriptor instead.
func (*LikePostRequest) Descriptor() ([]byte, []int) {
	return file_post_proto_rawDescGZIP(), []int{18}
}

func (x *LikePostRequest) GetUid() string {
	if x != nil {
		return x.Uid
	}
	return ""
}

func (x *LikePostRequest) GetAction() ToggleAction {
	if x != nil {
		return x.Action
	}
	return ToggleAction_TOGGLE_ACTION_ADD
}

type LikePostResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LikePostResponse) Reset() {
	*x = LikePostResponse{}
	mi := &file_post_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LikePostResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LikePostResponse) ProtoMessage() {}

func (x *LikePostResponse) ProtoReflect() protoreflect.Message {
	mi := &file_post_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LikePostResponse.ProtoReflect.Descriptor instead.
func (*LikePostResponse) Descriptor() ([]byte, []int) {
	return file_post_proto_rawDescGZIP(), []int{19}
}

type CollectPostRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uid           string                 `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`
	Action        ToggleAction           `protobuf:"varint,2,opt,name=action,proto3,enum=common.ToggleAction" json:"action,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CollectPostRequest) Reset() {
	*x = CollectPostRequest{}
	mi := &file_post_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CollectPostRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CollectPostRequest) ProtoMessage() {}

func (x *CollectPostRequest) ProtoReflect() protoreflect.Message {
	mi := &file_post_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CollectPostRequest.ProtoReflect.Descriptor instead.
func (*CollectPostRequest) Descriptor() ([]byte, []int) {
	return file_post_proto_rawDescGZIP(), []int{20}
}

func (x *CollectPostRequest) GetUid() string {
	if x != nil {
		return x.Uid
	}
	return ""
}

func (x *CollectPostRequest) GetAction() ToggleAction {
	if x != nil {
		return x.Action
	}
	return ToggleAction_TOGGLE_ACTION_ADD
}

type CollectPostResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CollectPostResponse) Reset() {
	*x = CollectPostResponse{}
	mi := &file_post_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CollectPostResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CollectPostResponse) ProtoMessage() {}

func (x *CollectPostResponse) ProtoReflect() protoreflect.Message {
	mi := &file_post_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CollectPostResponse.ProtoReflect.Descriptor instead.
func (*CollectPostResponse) Descriptor() ([]byte, []int) {
	return file_post_proto_rawDescGZIP(), []int{21}
}

var File_post_proto protoreflect.FileDescriptor

const file_post_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"post.proto\x12\x04post\x1a\x1cgoogle/api/annotations.proto\x1a\x1fgoogle/api/field_behavior.proto\x1a\x1bgoogle/protobuf/empty.proto\x1a google/protobuf/field_mask.proto\x1a\fcommon.proto\"\x90\x01\n" +
	"\n" +
	"PostAuthor\x12\x15\n" +
	"\x03uid\x18\x01 \x01(\tB\x03\xe0A\x02R\x03uid\x12\x1f\n" +
	"\bnickname\x18\x02 \x01(\tB\x03\xe0A\x02R\bnickname\x12\"\n" +
	"\n" +
	"avatar_url\x18\x03 \x01(\tB\x03\xe0A\x02R\tavatarUrl\x12&\n" +
	"\fis_following\x18\x04 \x01(\bB\x03\xe0A\x02R\visFollowing\"\x9e\x01\n" +
	"\n" +
	"Attachment\x12\x15\n" +
	"\x03url\x18\x01 \x01(\tB\x03\xe0A\x02R\x03url\x12\x17\n" +
	"\x04name\x18\x02 \x01(\tB\x03\xe0A\x02R\x04name\x12\x17\n" +
	"\x04size\x18\x03 \x01(\x03B\x03\xe0A\x02R\x04size\x12&\n" +
	"\fcontent_type\x18\x04 \x01(\tB\x03\xe0A\x02R\vcontentType\x12\x1f\n" +
	"\bchecksum\x18\x05 \x01(\tB\x03\xe0A\x02R\bchecksum\"\xe0\x04\n" +
	"\x04Post\x12\x15\n" +
	"\x03uid\x18\x01 \x01(\tB\x03\xe0A\x02R\x03uid\x12-\n" +
	"\x06author\x18\x02 \x01(\v2\x10.post.PostAuthorB\x03\xe0A\x02R\x06author\x12\x17\n" +
	"\x04text\x18\x03 \x01(\tB\x03\xe0A\x02R\x04text\x12\x1b\n" +
	"\x06images\x18\x04 \x03(\tB\x03\xe0A\x02R\x06images\x127\n" +
	"\vattachments\x18\x05 \x03(\v2\x10.post.AttachmentB\x03\xe0A\x02R\vattachments\x12\x17\n" +
	"\x04tags\x18\x06 \x03(\tB\x03\xe0A\x02R\x04tags\x12(\n" +
	"\rcomment_count\x18\a \x01(\x05B\x03\xe0A\x02R\fcommentCount\x12.\n" +
	"\x10collection_count\x18\b \x01(\x05B\x03\xe0A\x02R\x0fcollectionCount\x12\"\n" +
	"\n" +
	"like_count\x18\t \x01(\x05B\x03\xe0A\x02R\tlikeCount\x12#\n" +
	"\n" +
	"visibility\x18\n" +
	" \x01(\tB\x03\xe0A\x02R\n" +
	"visibility\x12/\n" +
	"\x11latest_replied_on\x18\v \x01(\x03B\x03\xe0A\x02R\x0flatestRepliedOn\x12\x13\n" +
	"\x02ip\x18\f \x01(\tB\x03\xe0A\x02R\x02ip\x12\x1b\n" +
	"\x06pinned\x18\r \x01(\bB\x03\xe0A\x02R\x06pinned\x12\x19\n" +
	"\x05liked\x18\x0e \x01(\bB\x03\xe0A\x02R\x05liked\x12!\n" +
	"\tcollected\x18\x0f \x01(\bB\x03\xe0A\x02R\tcollected\x12\"\n" +
	"\n" +
	"created_at\x18\x10 \x01(\x03B\x03\xe0A\x02R\tcreatedAt\x12\"\n" +
	"\n" +
	"updated_at\x18\x11 \x01(\x03B\x03\xe0A\x02R\tupdatedAt\"\xb2\x01\n" +
	"\x11CreatePostRequest\x12\x17\n" +
	"\x04text\x18\x01 \x01(\tB\x03\xe0A\x02R\x04text\x12\x16\n" +
	"\x06images\x18\x02 \x03(\tR\x06images\x12 \n" +
	"\vattachments\x18\x03 \x03(\tR\vattachments\x12\x12\n" +
	"\x04tags\x18\x04 \x03(\tR\x04tags\x12\x1e\n" +
	"\n" +
	"visibility\x18\x05 \x01(\tR\n" +
	"visibility\x12\x16\n" +
	"\x06pinned\x18\x06 \x01(\bR\x06pinned\"+\n" +
	"\x12CreatePostResponse\x12\x15\n" +
	"\x03uid\x18\x01 \x01(\tB\x03\xe0A\x02R\x03uid\"\x81\x01\n" +
	"\x10ListPostsRequest\x12\x14\n" +
	"\x05query\x18\x01 \x01(\tR\x05query\x12\x1d\n" +
	"\n" +
	"author_uid\x18\x02 \x01(\tR\tauthorUid\x12\x19\n" +
	"\btag_name\x18\x03 \x01(\tR\atagName\x12\x1d\n" +
	"\n" +
	"page_token\x18\x04 \x01(\tR\tpageToken\"\x83\x01\n" +
	"\x12SearchPostsRequest\x12\x14\n" +
	"\x05query\x18\x01 \x01(\tR\x05query\x12\x1d\n" +
	"\n" +
	"author_uid\x18\x02 \x01(\tR\tauthorUid\x12\x19\n" +
	"\btag_name\x18\x03 \x01(\tR\atagName\x12\x1d\n" +
	"\n" +
	"page_token\x18\x04 \x01(\tR\tpageToken\"g\n" +
	"\x11ListPostsResponse\x12%\n" +
	"\x05posts\x18\x01 \x03(\v2\n" +
	".post.PostB\x03\xe0A\x02R\x05posts\x12+\n" +
	"\x0fnext_page_token\x18\x02 \x01(\tB\x03\xe0A\x02R\rnextPageToken\"$\n" +
	"\tSearchTag\x12\x17\n" +
	"\x04name\x18\x01 \x01(\tB\x03\xe0A\x02R\x04name\".\n" +
	"\x11SearchTagsRequest\x12\x19\n" +
	"\x05query\x18\x01 \x01(\tB\x03\xe0A\x02R\x05query\">\n" +
	"\x12SearchTagsResponse\x12(\n" +
	"\x04tags\x18\x01 \x03(\v2\x0f.post.SearchTagB\x03\xe0A\x02R\x04tags\"9\n" +
	"\x1aSuggestTagsByPrefixRequest\x12\x1b\n" +
	"\x06prefix\x18\x01 \x01(\tB\x03\xe0A\x02R\x06prefix\"G\n" +
	"\x1bSuggestTagsByPrefixResponse\x12(\n" +
	"\x04tags\x18\x01 \x03(\v2\x0f.post.SearchTagB\x03\xe0A\x02R\x04tags\"'\n" +
	"\x0eGetPostRequest\x12\x15\n" +
	"\x03uid\x18\x01 \x01(\tB\x03\xe0A\x02R\x03uid\"6\n" +
	"\x0fGetPostResponse\x12#\n" +
	"\x04post\x18\x01 \x01(\v2\n" +
	".post.PostB\x03\xe0A\x02R\x04post\"\xaa\x01\n" +
	"\x0eUpdatePostBody\x12\x12\n" +
	"\x04text\x18\x01 \x01(\tR\x04text\x12\x16\n" +
	"\x06images\x18\x02 \x03(\tR\x06images\x12 \n" +
	"\vattachments\x18\x03 \x03(\tR\vattachments\x12\x12\n" +
	"\x04tags\x18\x04 \x03(\tR\x04tags\x12\x1e\n" +
	"\n" +
	"visibility\x18\x05 \x01(\tR\n" +
	"visibility\x12\x16\n" +
	"\x06pinned\x18\x06 \x01(\bR\x06pinned\"\x9b\x01\n" +
	"\x11UpdatePostRequest\x12\x15\n" +
	"\x03uid\x18\x01 \x01(\tB\x03\xe0A\x02R\x03uid\x12-\n" +
	"\x04post\x18\x02 \x01(\v2\x14.post.UpdatePostBodyB\x03\xe0A\x02R\x04post\x12@\n" +
	"\vupdate_mask\x18\x03 \x01(\v2\x1a.google.protobuf.FieldMaskB\x03\xe0A\x02R\n" +
	"updateMask\"*\n" +
	"\x11DeletePostRequest\x12\x15\n" +
	"\x03uid\x18\x01 \x01(\tB\x03\xe0A\x02R\x03uid\"V\n" +
	"\x0fLikePostRequest\x12\x15\n" +
	"\x03uid\x18\x01 \x01(\tB\x03\xe0A\x02R\x03uid\x12,\n" +
	"\x06action\x18\x02 \x01(\x0e2\x14.common.ToggleActionR\x06action\"\x12\n" +
	"\x10LikePostResponse\"Y\n" +
	"\x12CollectPostRequest\x12\x15\n" +
	"\x03uid\x18\x01 \x01(\tB\x03\xe0A\x02R\x03uid\x12,\n" +
	"\x06action\x18\x02 \x01(\x0e2\x14.common.ToggleActionR\x06action\"\x15\n" +
	"\x13CollectPostResponse2\xbe\b\n" +
	"\vPostService\x12Y\n" +
	"\n" +
	"CreatePost\x12\x17.post.CreatePostRequest\x1a\x18.post.CreatePostResponse\"\x18\x82\xd3\xe4\x93\x02\x12:\x01*\"\r/api/v1/posts\x12S\n" +
	"\tListPosts\x12\x16.post.ListPostsRequest\x1a\x17.post.ListPostsResponse\"\x15\x82\xd3\xe4\x93\x02\x0f\x12\r/api/v1/posts\x12^\n" +
	"\vSearchPosts\x12\x18.post.SearchPostsRequest\x1a\x17.post.ListPostsResponse\"\x1c\x82\xd3\xe4\x93\x02\x16\x12\x14/api/v1/search/posts\x12d\n" +
	"\x11ListMyCollections\x12\x16.post.ListPostsRequest\x1a\x17.post.ListPostsResponse\"\x1e\x82\xd3\xe4\x93\x02\x18\x12\x16/api/v1/me/collections\x12\\\n" +
	"\n" +
	"SearchTags\x12\x17.post.SearchTagsRequest\x1a\x18.post.SearchTagsResponse\"\x1b\x82\xd3\xe4\x93\x02\x15\x12\x13/api/v1/search/tags\x12|\n" +
	"\x13SuggestTagsByPrefix\x12 .post.SuggestTagsByPrefixRequest\x1a!.post.SuggestTagsByPrefixResponse\" \x82\xd3\xe4\x93\x02\x1a\x12\x18/api/v1/suggestions/tags\x12S\n" +
	"\aGetPost\x12\x14.post.GetPostRequest\x1a\x15.post.GetPostResponse\"\x1b\x82\xd3\xe4\x93\x02\x15\x12\x13/api/v1/posts/{uid}\x12`\n" +
	"\n" +
	"UpdatePost\x12\x17.post.UpdatePostRequest\x1a\x16.google.protobuf.Empty\"!\x82\xd3\xe4\x93\x02\x1b:\x04post2\x13/api/v1/posts/{uid}\x12Z\n" +
	"\n" +
	"DeletePost\x12\x17.post.DeletePostRequest\x1a\x16.google.protobuf.Empty\"\x1b\x82\xd3\xe4\x93\x02\x15*\x13/api/v1/posts/{uid}\x12^\n" +
	"\bLikePost\x12\x15.post.LikePostRequest\x1a\x16.post.LikePostResponse\"#\x82\xd3\xe4\x93\x02\x1d:\x01*\"\x18/api/v1/posts/{uid}/like\x12j\n" +
	"\vCollectPost\x12\x18.post.CollectPostRequest\x1a\x19.post.CollectPostResponse\"&\x82\xd3\xe4\x93\x02 :\x01*\"\x1b/api/v1/posts/{uid}/collectB\x0fZ\raeibi/api;apib\x06proto3"

var (
	file_post_proto_rawDescOnce sync.Once
	file_post_proto_rawDescData []byte
)

func file_post_proto_rawDescGZIP() []byte {
	file_post_proto_rawDescOnce.Do(func() {
		file_post_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_post_proto_rawDesc), len(file_post_proto_rawDesc)))
	})
	return file_post_proto_rawDescData
}

var file_post_proto_msgTypes = make([]protoimpl.MessageInfo, 22)
var file_post_proto_goTypes = []any{
	(*PostAuthor)(nil),                  // 0: post.PostAuthor
	(*Attachment)(nil),                  // 1: post.Attachment
	(*Post)(nil),                        // 2: post.Post
	(*CreatePostRequest)(nil),           // 3: post.CreatePostRequest
	(*CreatePostResponse)(nil),          // 4: post.CreatePostResponse
	(*ListPostsRequest)(nil),            // 5: post.ListPostsRequest
	(*SearchPostsRequest)(nil),          // 6: post.SearchPostsRequest
	(*ListPostsResponse)(nil),           // 7: post.ListPostsResponse
	(*SearchTag)(nil),                   // 8: post.SearchTag
	(*SearchTagsRequest)(nil),           // 9: post.SearchTagsRequest
	(*SearchTagsResponse)(nil),          // 10: post.SearchTagsResponse
	(*SuggestTagsByPrefixRequest)(nil),  // 11: post.SuggestTagsByPrefixRequest
	(*SuggestTagsByPrefixResponse)(nil), // 12: post.SuggestTagsByPrefixResponse
	(*GetPostRequest)(nil),              // 13: post.GetPostRequest
	(*GetPostResponse)(nil),             // 14: post.GetPostResponse
	(*UpdatePostBody)(nil),              // 15: post.UpdatePostBody
	(*UpdatePostRequest)(nil),           // 16: post.UpdatePostRequest
	(*DeletePostRequest)(nil),           // 17: post.DeletePostRequest
	(*LikePostRequest)(nil),             // 18: post.LikePostRequest
	(*LikePostResponse)(nil),            // 19: post.LikePostResponse
	(*CollectPostRequest)(nil),          // 20: post.CollectPostRequest
	(*CollectPostResponse)(nil),         // 21: post.CollectPostResponse
	(*fieldmaskpb.FieldMask)(nil),       // 22: google.protobuf.FieldMask
	(ToggleAction)(0),                   // 23: common.ToggleAction
	(*emptypb.Empty)(nil),               // 24: google.protobuf.Empty
}
var file_post_proto_depIdxs = []int32{
	0,  // 0: post.Post.author:type_name -> post.PostAuthor
	1,  // 1: post.Post.attachments:type_name -> post.Attachment
	2,  // 2: post.ListPostsResponse.posts:type_name -> post.Post
	8,  // 3: post.SearchTagsResponse.tags:type_name -> post.SearchTag
	8,  // 4: post.SuggestTagsByPrefixResponse.tags:type_name -> post.SearchTag
	2,  // 5: post.GetPostResponse.post:type_name -> post.Post
	15, // 6: post.UpdatePostRequest.post:type_name -> post.UpdatePostBody
	22, // 7: post.UpdatePostRequest.update_mask:type_name -> google.protobuf.FieldMask
	23, // 8: post.LikePostRequest.action:type_name -> common.ToggleAction
	23, // 9: post.CollectPostRequest.action:type_name -> common.ToggleAction
	3,  // 10: post.PostService.CreatePost:input_type -> post.CreatePostRequest
	5,  // 11: post.PostService.ListPosts:input_type -> post.ListPostsRequest
	6,  // 12: post.PostService.SearchPosts:input_type -> post.SearchPostsRequest
	5,  // 13: post.PostService.ListMyCollections:input_type -> post.ListPostsRequest
	9,  // 14: post.PostService.SearchTags:input_type -> post.SearchTagsRequest
	11, // 15: post.PostService.SuggestTagsByPrefix:input_type -> post.SuggestTagsByPrefixRequest
	13, // 16: post.PostService.GetPost:input_type -> post.GetPostRequest
	16, // 17: post.PostService.UpdatePost:input_type -> post.UpdatePostRequest
	17, // 18: post.PostService.DeletePost:input_type -> post.DeletePostRequest
	18, // 19: post.PostService.LikePost:input_type -> post.LikePostRequest
	20, // 20: post.PostService.CollectPost:input_type -> post.CollectPostRequest
	4,  // 21: post.PostService.CreatePost:output_type -> post.CreatePostResponse
	7,  // 22: post.PostService.ListPosts:output_type -> post.ListPostsResponse
	7,  // 23: post.PostService.SearchPosts:output_type -> post.ListPostsResponse
	7,  // 24: post.PostService.ListMyCollections:output_type -> post.ListPostsResponse
	10, // 25: post.PostService.SearchTags:output_type -> post.SearchTagsResponse
	12, // 26: post.PostService.SuggestTagsByPrefix:output_type -> post.SuggestTagsByPrefixResponse
	14, // 27: post.PostService.GetPost:output_type -> post.GetPostResponse
	24, // 28: post.PostService.UpdatePost:output_type -> google.protobuf.Empty
	24, // 29: post.PostService.DeletePost:output_type -> google.protobuf.Empty
	19, // 30: post.PostService.LikePost:output_type -> post.LikePostResponse
	21, // 31: post.PostService.CollectPost:output_type -> post.CollectPostResponse
	21, // [21:32] is the sub-list for method output_type
	10, // [10:21] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_post_proto_init() }
func file_post_proto_init() {
	if File_post_proto != nil {
		return
	}
	file_common_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_post_proto_rawDesc), len(file_post_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   22,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_post_proto_goTypes,
		DependencyIndexes: file_post_proto_depIdxs,
		MessageInfos:      file_post_proto_msgTypes,
	}.Build()
	File_post_proto = out.File
	file_post_proto_goTypes = nil
	file_post_proto_depIdxs = nil
}
