// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: report.proto

package api

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ReportTargetType int32

const (
	ReportTargetType_REPORT_TARGET_TYPE_UNSPECIFIED ReportTargetType = 0
	ReportTargetType_REPORT_TARGET_TYPE_POST        ReportTargetType = 1
	ReportTargetType_REPORT_TARGET_TYPE_COMMENT     ReportTargetType = 2
	ReportTargetType_REPORT_TARGET_TYPE_USER        ReportTargetType = 3
)

// Enum value maps for ReportTargetType.
var (
	ReportTargetType_name = map[int32]string{
		0: "REPORT_TARGET_TYPE_UNSPECIFIED",
		1: "REPORT_TARGET_TYPE_POST",
		2: "REPORT_TARGET_TYPE_COMMENT",
		3: "REPORT_TARGET_TYPE_USER",
	}
	ReportTargetType_value = map[string]int32{
		"REPORT_TARGET_TYPE_UNSPECIFIED": 0,
		"REPORT_TARGET_TYPE_POST":        1,
		"REPORT_TARGET_TYPE_COMMENT":     2,
		"REPORT_TARGET_TYPE_USER":        3,
	}
)

func (x ReportTargetType) Enum() *ReportTargetType {
	p := new(ReportTargetType)
	*p = x
	return p
}

func (x ReportTargetType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ReportTargetType) Descriptor() protoreflect.EnumDescriptor {
	return file_report_proto_enumTypes[0].Descriptor()
}

func (ReportTargetType) Type() protoreflect.EnumType {
	return &file_report_proto_enumTypes[0]
}

func (x ReportTargetType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ReportTargetType.Descriptor instead.
func (ReportTargetType) EnumDescriptor() ([]byte, []int) {
	return file_report_proto_rawDescGZIP(), []int{0}
}

type CreateReportRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	ReportTargetType ReportTargetType       `protobuf:"varint,1,opt,name=report_target_type,json=reportTargetType,proto3,enum=report.ReportTargetType" json:"report_target_type,omitempty"`
	TargetUid        string                 `protobuf:"bytes,2,opt,name=target_uid,json=targetUid,proto3" json:"target_uid,omitempty"`
	Content          string                 `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *CreateReportRequest) Reset() {
	*x = CreateReportRequest{}
	mi := &file_report_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateReportRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateReportRequest) ProtoMessage() {}

func (x *CreateReportRequest) ProtoReflect() protoreflect.Message {
	mi := &file_report_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateReportRequest.ProtoReflect.Descriptor instead.
func (*CreateReportRequest) Descriptor() ([]byte, []int) {
	return file_report_proto_rawDescGZIP(), []int{0}
}

func (x *CreateReportRequest) GetReportTargetType() ReportTargetType {
	if x != nil {
		return x.ReportTargetType
	}
	return ReportTargetType_REPORT_TARGET_TYPE_UNSPECIFIED
}

func (x *CreateReportRequest) GetTargetUid() string {
	if x != nil {
		return x.TargetUid
	}
	return ""
}

func (x *CreateReportRequest) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

var File_report_proto protoreflect.FileDescriptor

const file_report_proto_rawDesc = "" +
	"\n" +
	"\freport.proto\x12\x06report\x1a\x1cgoogle/api/annotations.proto\x1a\x1fgoogle/api/field_behavior.proto\x1a\x1bgoogle/protobuf/empty.proto\"\xa5\x01\n" +
	"\x13CreateReportRequest\x12K\n" +
	"\x12report_target_type\x18\x01 \x01(\x0e2\x18.report.ReportTargetTypeB\x03\xe0A\x02R\x10reportTargetType\x12\"\n" +
	"\n" +
	"target_uid\x18\x02 \x01(\tB\x03\xe0A\x02R\ttargetUid\x12\x1d\n" +
	"\acontent\x18\x03 \x01(\tB\x03\xe0A\x02R\acontent*\x90\x01\n" +
	"\x10ReportTargetType\x12\"\n" +
	"\x1eREPORT_TARGET_TYPE_UNSPECIFIED\x10\x00\x12\x1b\n" +
	"\x17REPORT_TARGET_TYPE_POST\x10\x01\x12\x1e\n" +
	"\x1aREPORT_TARGET_TYPE_COMMENT\x10\x02\x12\x1b\n" +
	"\x17REPORT_TARGET_TYPE_USER\x10\x032p\n" +
	"\rReportService\x12_\n" +
	"\fCreateReport\x12\x1b.report.CreateReportRequest\x1a\x16.google.protobuf.Empty\"\x1a\x82\xd3\xe4\x93\x02\x14:\x01*\"\x0f/api/v1/reportsB\x0fZ\raeibi/api;apib\x06proto3"

var (
	file_report_proto_rawDescOnce sync.Once
	file_report_proto_rawDescData []byte
)

func file_report_proto_rawDescGZIP() []byte {
	file_report_proto_rawDescOnce.Do(func() {
		file_report_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_report_proto_rawDesc), len(file_report_proto_rawDesc)))
	})
	return file_report_proto_rawDescData
}

var file_report_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_report_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_report_proto_goTypes = []any{
	(ReportTargetType)(0),       // 0: report.ReportTargetType
	(*CreateReportRequest)(nil), // 1: report.CreateReportRequest
	(*emptypb.Empty)(nil),       // 2: google.protobuf.Empty
}
var file_report_proto_depIdxs = []int32{
	0, // 0: report.CreateReportRequest.report_target_type:type_name -> report.ReportTargetType
	1, // 1: report.ReportService.CreateReport:input_type -> report.CreateReportRequest
	2, // 2: report.ReportService.CreateReport:output_type -> google.protobuf.Empty
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_report_proto_init() }
func file_report_proto_init() {
	if File_report_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_report_proto_rawDesc), len(file_report_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_report_proto_goTypes,
		DependencyIndexes: file_report_proto_depIdxs,
		EnumInfos:         file_report_proto_enumTypes,
		MessageInfos:      file_report_proto_msgTypes,
	}.Build()
	File_report_proto = out.File
	file_report_proto_goTypes = nil
	file_report_proto_depIdxs = nil
}
